import type { Allergen, IngredientCategory, Unit } from '@/types/domain';

/**
 * Canonical ingredient catalogue for the Egyptian launch market.
 *
 * This file is the SINGLE SOURCE OF TRUTH for ingredients. It is:
 *   1. bundled into the app for offline autocomplete and matching, and
 *   2. compiled into `supabase/seed.sql` by `scripts/generate-seed.ts`.
 *
 * After editing, run `npm run seed:generate` and commit the regenerated SQL.
 *
 * NOTE: this module must only use `import type` so the seed generator can load
 * it with Node's type-stripping loader.
 */

export type CatalogueIngredient = {
  /** Stable slug. Becomes the ingredient's natural key in Postgres. */
  slug: string;
  name: string;
  nameAr: string;
  category: IngredientCategory;
  defaultUnit: Unit;
  /** Grams in one `piece`. Null for ingredients that are not countable. */
  gramsPerPiece: number | null;
  allergens: Allergen[];
  /** Match aliases: transliterations, Arabic spellings, regional names, plurals. */
  aliases: string[];
  /** Assumed present in most kitchens unless the user says otherwise. */
  isCommonStaple: boolean;
  /** Spoils quickly; expiry dates are enforced strictly for these. */
  isPerishable: boolean;
  /**
   * Typical Egyptian retail price, in PIASTRES per the `priceUnit` below.
   * These seed `ingredient_price_estimates`; they are estimates, never live
   * prices, and are dated in the seed file.
   */
  priceLowMinor: number;
  priceAvgMinor: number;
  priceHighMinor: number;
  /** Unit the prices above are quoted per. */
  priceUnit: Unit;
  priceQuantity: number;
};

/**
 * Prices reflect typical Cairo supermarket shelf prices and are illustrative
 * seed data for development. They are NOT live prices and must always be
 * surfaced to users as estimates.
 */
export const INGREDIENT_CATALOGUE: CatalogueIngredient[] = [
  // --- Protein -------------------------------------------------------------
  {
    slug: 'chicken-breast',
    name: 'chicken breast',
    nameAr: 'صدور فراخ',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: 180,
    allergens: [],
    aliases: ['chicken', 'chicken breasts', 'firakh', 'farkha', 'فراخ', 'صدر فراخ', 'دجاج'],
    isCommonStaple: false,
    isPerishable: true,
    priceLowMinor: 16000,
    priceAvgMinor: 19000,
    priceHighMinor: 23000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'chicken-thigh',
    name: 'chicken thighs',
    nameAr: 'أوراك فراخ',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: 130,
    allergens: [],
    aliases: ['chicken thigh', 'drumsticks', 'أوراك', 'وراك فراخ'],
    isCommonStaple: false,
    isPerishable: true,
    priceLowMinor: 11000,
    priceAvgMinor: 13500,
    priceHighMinor: 16000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'ground-beef',
    name: 'ground beef',
    nameAr: 'لحمة مفرومة',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['minced beef', 'mince', 'minced meat', 'kofta meat', 'لحمة مفرومه', 'مفروم'],
    isCommonStaple: false,
    isPerishable: true,
    priceLowMinor: 32000,
    priceAvgMinor: 38000,
    priceHighMinor: 45000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'beef-cubes',
    name: 'beef cubes',
    nameAr: 'لحمة مكعبات',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['stewing beef', 'beef chunks', 'لحمة', 'لحم بقري'],
    isCommonStaple: false,
    isPerishable: true,
    priceLowMinor: 34000,
    priceAvgMinor: 40000,
    priceHighMinor: 48000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'eggs',
    name: 'eggs',
    nameAr: 'بيض',
    category: 'protein',
    defaultUnit: 'piece',
    gramsPerPiece: 55,
    allergens: ['eggs'],
    aliases: ['egg', 'beid', 'بيضة', 'بيضه'],
    isCommonStaple: true,
    isPerishable: true,
    priceLowMinor: 450,
    priceAvgMinor: 550,
    priceHighMinor: 700,
    priceUnit: 'piece',
    priceQuantity: 1,
  },
  {
    slug: 'tuna-can',
    name: 'canned tuna',
    nameAr: 'تونة',
    category: 'protein',
    defaultUnit: 'can',
    gramsPerPiece: 140,
    allergens: ['fish'],
    aliases: ['tuna', 'tuna can', 'تونه'],
    isCommonStaple: false,
    isPerishable: false,
    priceLowMinor: 4500,
    priceAvgMinor: 5800,
    priceHighMinor: 7500,
    priceUnit: 'can',
    priceQuantity: 1,
  },
  {
    slug: 'tilapia',
    name: 'tilapia',
    nameAr: 'بلطي',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: 300,
    allergens: ['fish'],
    aliases: ['fish', 'bolti', 'بلطى', 'سمك'],
    isCommonStaple: false,
    isPerishable: true,
    priceLowMinor: 9000,
    priceAvgMinor: 12000,
    priceHighMinor: 15000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'shrimp',
    name: 'shrimp',
    nameAr: 'جمبري',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: 12,
    allergens: ['shellfish'],
    aliases: ['prawns', 'gambari', 'جمبرى'],
    isCommonStaple: false,
    isPerishable: true,
    priceLowMinor: 32000,
    priceAvgMinor: 42000,
    priceHighMinor: 55000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'sausage',
    name: 'beef sausage',
    nameAr: 'سجق',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: 40,
    allergens: [],
    aliases: ['sogo2', 'sogok', 'سجق بلدي'],
    isCommonStaple: false,
    isPerishable: true,
    priceLowMinor: 22000,
    priceAvgMinor: 27000,
    priceHighMinor: 33000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'liver',
    name: 'beef liver',
    nameAr: 'كبدة',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['kebda', 'كبده', 'كبدة اسكندراني'],
    isCommonStaple: false,
    isPerishable: true,
    priceLowMinor: 20000,
    priceAvgMinor: 24000,
    priceHighMinor: 29000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },

  // --- Legumes / pulses (Egyptian staples) --------------------------------
  {
    slug: 'fava-beans',
    name: 'fava beans',
    nameAr: 'فول',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['foul', 'ful', 'ful medames', 'foul medames', 'فول مدمس'],
    isCommonStaple: true,
    isPerishable: false,
    priceLowMinor: 3500,
    priceAvgMinor: 4500,
    priceHighMinor: 6000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'lentils',
    name: 'red lentils',
    nameAr: 'عدس',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['lentil', 'ads', 'عدس أصفر', 'عدس احمر'],
    isCommonStaple: true,
    isPerishable: false,
    priceLowMinor: 5000,
    priceAvgMinor: 6500,
    priceHighMinor: 8500,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'chickpeas',
    name: 'chickpeas',
    nameAr: 'حمص',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['garbanzo', 'hummus beans', 'حمص حب'],
    isCommonStaple: false,
    isPerishable: false,
    priceLowMinor: 6000,
    priceAvgMinor: 7500,
    priceHighMinor: 9500,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'white-beans',
    name: 'white beans',
    nameAr: 'فاصوليا بيضاء',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['fasolia', 'cannellini', 'فاصوليا'],
    isCommonStaple: false,
    isPerishable: false,
    priceLowMinor: 5500,
    priceAvgMinor: 7000,
    priceHighMinor: 9000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'black-eyed-peas',
    name: 'black-eyed peas',
    nameAr: 'لوبيا',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['lobia', 'لوبيا مجففة'],
    isCommonStaple: false,
    isPerishable: false,
    priceLowMinor: 5500,
    priceAvgMinor: 7000,
    priceHighMinor: 9000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },

  // --- Carbs ---------------------------------------------------------------
  {
    slug: 'rice',
    name: 'rice',
    nameAr: 'أرز',
    category: 'carbs',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['egyptian rice', 'white rice', 'roz', 'رز'],
    isCommonStaple: true,
    isPerishable: false,
    priceLowMinor: 3000,
    priceAvgMinor: 3800,
    priceHighMinor: 5000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'pasta',
    name: 'pasta',
    nameAr: 'مكرونة',
    category: 'carbs',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['gluten'],
    aliases: ['macaroni', 'spaghetti', 'penne', 'makarona', 'مكرونه'],
    isCommonStaple: true,
    isPerishable: false,
    priceLowMinor: 2200,
    priceAvgMinor: 3000,
    priceHighMinor: 4200,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'baladi-bread',
    name: 'baladi bread',
    nameAr: 'عيش بلدي',
    category: 'bakery',
    defaultUnit: 'piece',
    gramsPerPiece: 90,
    allergens: ['gluten'],
    aliases: [
      'aish',
      'aish baladi',
      'eish',
      'eish baladi',
      'pita',
      'flatbread',
      'bread',
      'عيش',
      'خبز',
    ],
    isCommonStaple: true,
    isPerishable: true,
    priceLowMinor: 100,
    priceAvgMinor: 150,
    priceHighMinor: 300,
    priceUnit: 'piece',
    priceQuantity: 1,
  },
  {
    slug: 'toast-bread',
    name: 'sliced bread',
    nameAr: 'عيش توست',
    category: 'bakery',
    defaultUnit: 'slice',
    gramsPerPiece: 30,
    allergens: ['gluten'],
    aliases: ['toast', 'white bread', 'sandwich bread', 'توست'],
    isCommonStaple: false,
    isPerishable: true,
    priceLowMinor: 2500,
    priceAvgMinor: 3500,
    priceHighMinor: 4500,
    priceUnit: 'pack',
    priceQuantity: 1,
  },
  {
    slug: 'potatoes',
    name: 'potatoes',
    nameAr: 'بطاطس',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: 150,
    allergens: [],
    aliases: ['potato', 'batates', 'بطاطا'],
    isCommonStaple: true,
    isPerishable: false,
    priceLowMinor: 1200,
    priceAvgMinor: 1800,
    priceHighMinor: 2600,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'bulgur',
    name: 'bulgur',
    nameAr: 'برغل',
    category: 'carbs',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['gluten'],
    aliases: ['borghol', 'cracked wheat', 'برغل ناعم'],
    isCommonStaple: false,
    isPerishable: false,
    priceLowMinor: 4000,
    priceAvgMinor: 5200,
    priceHighMinor: 6800,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'flour',
    name: 'flour',
    nameAr: 'دقيق',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['gluten'],
    aliases: ['all purpose flour', 'plain flour', 'دقيق فاخر'],
    isCommonStaple: true,
    isPerishable: false,
    priceLowMinor: 1800,
    priceAvgMinor: 2400,
    priceHighMinor: 3200,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'vermicelli',
    name: 'vermicelli',
    nameAr: 'شعرية',
    category: 'carbs',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['gluten'],
    aliases: ['sha3reya', 'shaareya', 'شعريه'],
    isCommonStaple: false,
    isPerishable: false,
    priceLowMinor: 2500,
    priceAvgMinor: 3200,
    priceHighMinor: 4200,
    priceUnit: 'pack',
    priceQuantity: 1,
  },

  // --- Vegetables ----------------------------------------------------------
  {
    slug: 'tomatoes',
    name: 'tomatoes',
    nameAr: 'طماطم',
    category: 'vegetables',
    defaultUnit: 'piece',
    gramsPerPiece: 120,
    allergens: [],
    aliases: ['tomato', 'oota', 'طماطم حمراء', 'قوطة'],
    isCommonStaple: true,
    isPerishable: true,
    priceLowMinor: 1000,
    priceAvgMinor: 1600,
    priceHighMinor: 2600,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'onions',
    name: 'onions',
    nameAr: 'بصل',
    category: 'vegetables',
    defaultUnit: 'piece',
    gramsPerPiece: 110,
    allergens: [],
    aliases: ['onion', 'basal', 'بصل أحمر', 'بصل أبيض'],
    isCommonStaple: true,
    isPerishable: false,
    priceLowMinor: 1200,
    priceAvgMinor: 1800,
    priceHighMinor: 2800,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'garlic',
    name: 'garlic',
    nameAr: 'ثوم',
    category: 'vegetables',
    defaultUnit: 'clove',
    gramsPerPiece: 5,
    allergens: [],
    aliases: ['toum', 'tom', 'garlic cloves', 'فص ثوم'],
    isCommonStaple: true,
    isPerishable: false,
    priceLowMinor: 6000,
    priceAvgMinor: 8000,
    priceHighMinor: 11000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'cucumber',
    name: 'cucumber',
    nameAr: 'خيار',
    category: 'vegetables',
    defaultUnit: 'piece',
    gramsPerPiece: 100,
    allergens: [],
    aliases: ['cucumbers', 'khiar', 'خيار بلدي'],
    isCommonStaple: false,
    isPerishable: true,
    priceLowMinor: 1200,
    priceAvgMinor: 1800,
    priceHighMinor: 2800,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'bell-pepper',
    name: 'bell pepper',
    nameAr: 'فلفل ألوان',
    category: 'vegetables',
    defaultUnit: 'piece',
    gramsPerPiece: 140,
    allergens: [],
    aliases: ['capsicum', 'peppers', 'sweet pepper', 'فلفل رومي'],
    isCommonStaple: false,
    isPerishable: true,
    priceLowMinor: 2500,
    priceAvgMinor: 3500,
    priceHighMinor: 5000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'zucchini',
    name: 'zucchini',
    nameAr: 'كوسة',
    category: 'vegetables',
    defaultUnit: 'piece',
    gramsPerPiece: 160,
    allergens: [],
    aliases: ['courgette', 'kosa', 'كوسه'],
    isCommonStaple: false,
    isPerishable: true,
    priceLowMinor: 1400,
    priceAvgMinor: 2000,
    priceHighMinor: 3000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'eggplant',
    name: 'eggplant',
    nameAr: 'باذنجان',
    category: 'vegetables',
    defaultUnit: 'piece',
    gramsPerPiece: 220,
    allergens: [],
    aliases: ['aubergine', 'betingan', 'بتنجان'],
    isCommonStaple: false,
    isPerishable: true,
    priceLowMinor: 1200,
    priceAvgMinor: 1800,
    priceHighMinor: 2800,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'carrots',
    name: 'carrots',
    nameAr: 'جزر',
    category: 'vegetables',
    defaultUnit: 'piece',
    gramsPerPiece: 70,
    allergens: [],
    aliases: ['carrot', 'gazar', 'جزر بلدي'],
    isCommonStaple: false,
    isPerishable: true,
    priceLowMinor: 1400,
    priceAvgMinor: 2000,
    priceHighMinor: 3000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'molokhia',
    name: 'molokhia',
    nameAr: 'ملوخية',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['mulukhiyah', 'jute leaves', 'ملوخيه', 'ملوخية مفرومة'],
    isCommonStaple: false,
    isPerishable: true,
    priceLowMinor: 2500,
    priceAvgMinor: 3500,
    priceHighMinor: 4800,
    priceUnit: 'pack',
    priceQuantity: 1,
  },
  {
    slug: 'okra',
    name: 'okra',
    nameAr: 'بامية',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['bamya', 'lady fingers', 'باميه'],
    isCommonStaple: false,
    isPerishable: true,
    priceLowMinor: 3000,
    priceAvgMinor: 4200,
    priceHighMinor: 5800,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'spinach',
    name: 'spinach',
    nameAr: 'سبانخ',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['sabanekh', 'سبانخ مفرومة'],
    isCommonStaple: false,
    isPerishable: true,
    priceLowMinor: 1500,
    priceAvgMinor: 2200,
    priceHighMinor: 3200,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'lettuce',
    name: 'lettuce',
    nameAr: 'خس',
    category: 'vegetables',
    defaultUnit: 'piece',
    gramsPerPiece: 350,
    allergens: [],
    aliases: ['khass', 'romaine', 'خس بلدي'],
    isCommonStaple: false,
    isPerishable: true,
    priceLowMinor: 1000,
    priceAvgMinor: 1500,
    priceHighMinor: 2200,
    priceUnit: 'piece',
    priceQuantity: 1,
  },
  {
    slug: 'parsley',
    name: 'parsley',
    nameAr: 'بقدونس',
    category: 'vegetables',
    defaultUnit: 'bunch',
    gramsPerPiece: 60,
    allergens: [],
    aliases: ['ba2dounes', 'بقدونس أخضر'],
    isCommonStaple: false,
    isPerishable: true,
    priceLowMinor: 300,
    priceAvgMinor: 500,
    priceHighMinor: 800,
    priceUnit: 'bunch',
    priceQuantity: 1,
  },
  {
    slug: 'coriander',
    name: 'coriander',
    nameAr: 'كزبرة',
    category: 'vegetables',
    defaultUnit: 'bunch',
    gramsPerPiece: 50,
    allergens: [],
    aliases: ['cilantro', 'kozbara', 'كزبره خضراء'],
    isCommonStaple: false,
    isPerishable: true,
    priceLowMinor: 300,
    priceAvgMinor: 500,
    priceHighMinor: 800,
    priceUnit: 'bunch',
    priceQuantity: 1,
  },
  {
    slug: 'green-onion',
    name: 'green onion',
    nameAr: 'بصل أخضر',
    category: 'vegetables',
    defaultUnit: 'bunch',
    gramsPerPiece: 80,
    allergens: [],
    aliases: ['scallion', 'spring onion', 'بصل اخضر'],
    isCommonStaple: false,
    isPerishable: true,
    priceLowMinor: 400,
    priceAvgMinor: 700,
    priceHighMinor: 1000,
    priceUnit: 'bunch',
    priceQuantity: 1,
  },
  {
    slug: 'green-peas',
    name: 'green peas',
    nameAr: 'بسلة',
    category: 'frozen',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['peas', 'besella', 'بسله'],
    isCommonStaple: false,
    isPerishable: false,
    priceLowMinor: 4000,
    priceAvgMinor: 5200,
    priceHighMinor: 6800,
    priceUnit: 'kg',
    priceQuantity: 1,
  },

  // --- Fruit ---------------------------------------------------------------
  {
    slug: 'lemon',
    name: 'lemon',
    nameAr: 'ليمون',
    category: 'fruit',
    defaultUnit: 'piece',
    gramsPerPiece: 60,
    allergens: [],
    aliases: ['lemons', 'lime', 'lamoun', 'ليمون أخضر'],
    isCommonStaple: true,
    isPerishable: true,
    priceLowMinor: 2000,
    priceAvgMinor: 3000,
    priceHighMinor: 5000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'bananas',
    name: 'bananas',
    nameAr: 'موز',
    category: 'fruit',
    defaultUnit: 'piece',
    gramsPerPiece: 120,
    allergens: [],
    aliases: ['banana', 'moz', 'موزة'],
    isCommonStaple: false,
    isPerishable: true,
    priceLowMinor: 2000,
    priceAvgMinor: 2800,
    priceHighMinor: 4000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'dates',
    name: 'dates',
    nameAr: 'تمر',
    category: 'fruit',
    defaultUnit: 'piece',
    gramsPerPiece: 8,
    allergens: [],
    aliases: ['balah', 'tamr', 'بلح'],
    isCommonStaple: false,
    isPerishable: false,
    priceLowMinor: 6000,
    priceAvgMinor: 9000,
    priceHighMinor: 14000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'apples',
    name: 'apples',
    nameAr: 'تفاح',
    category: 'fruit',
    defaultUnit: 'piece',
    gramsPerPiece: 160,
    allergens: [],
    aliases: ['apple', 'tofah', 'تفاحة'],
    isCommonStaple: false,
    isPerishable: true,
    priceLowMinor: 5000,
    priceAvgMinor: 7000,
    priceHighMinor: 10000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },

  // --- Dairy ---------------------------------------------------------------
  {
    slug: 'milk',
    name: 'milk',
    nameAr: 'لبن',
    category: 'dairy',
    defaultUnit: 'ml',
    gramsPerPiece: null,
    allergens: ['dairy'],
    aliases: ['laban', 'full cream milk', 'حليب'],
    isCommonStaple: true,
    isPerishable: true,
    priceLowMinor: 3500,
    priceAvgMinor: 4500,
    priceHighMinor: 5800,
    priceUnit: 'l',
    priceQuantity: 1,
  },
  {
    slug: 'white-cheese',
    name: 'white cheese',
    nameAr: 'جبنة بيضاء',
    category: 'dairy',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['dairy'],
    aliases: ['feta', 'gebna beida', 'domiati', 'جبنه بيضاء', 'جبنة فيتا'],
    isCommonStaple: true,
    isPerishable: true,
    priceLowMinor: 9000,
    priceAvgMinor: 12000,
    priceHighMinor: 16000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'mozzarella',
    name: 'mozzarella',
    nameAr: 'موتزاريلا',
    category: 'dairy',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['dairy'],
    aliases: ['mozarella', 'pizza cheese', 'جبنة موتزاريلا', 'جبنه موزاريلا'],
    isCommonStaple: false,
    isPerishable: true,
    priceLowMinor: 18000,
    priceAvgMinor: 23000,
    priceHighMinor: 29000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'roumy-cheese',
    name: 'roumy cheese',
    nameAr: 'جبنة رومي',
    category: 'dairy',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['dairy'],
    aliases: ['romy', 'ras cheese', 'جبنه رومي'],
    isCommonStaple: false,
    isPerishable: true,
    priceLowMinor: 28000,
    priceAvgMinor: 34000,
    priceHighMinor: 42000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'yogurt',
    name: 'yogurt',
    nameAr: 'زبادي',
    category: 'dairy',
    defaultUnit: 'g',
    gramsPerPiece: 105,
    allergens: ['dairy'],
    aliases: ['zabady', 'plain yoghurt', 'زبادى'],
    isCommonStaple: true,
    isPerishable: true,
    priceLowMinor: 800,
    priceAvgMinor: 1100,
    priceHighMinor: 1500,
    priceUnit: 'piece',
    priceQuantity: 1,
  },
  {
    slug: 'cream',
    name: 'cooking cream',
    nameAr: 'كريمة طهي',
    category: 'dairy',
    defaultUnit: 'ml',
    gramsPerPiece: null,
    allergens: ['dairy'],
    aliases: ['heavy cream', 'double cream', 'krema', 'كريمه'],
    isCommonStaple: false,
    isPerishable: true,
    priceLowMinor: 4500,
    priceAvgMinor: 6000,
    priceHighMinor: 8000,
    priceUnit: 'pack',
    priceQuantity: 1,
  },
  {
    slug: 'butter',
    name: 'butter',
    nameAr: 'زبدة',
    category: 'dairy',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['dairy'],
    aliases: ['zebda', 'زبده'],
    isCommonStaple: true,
    isPerishable: true,
    priceLowMinor: 28000,
    priceAvgMinor: 36000,
    priceHighMinor: 46000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },

  // --- Pantry / sauces / fats ---------------------------------------------
  {
    slug: 'olive-oil',
    name: 'olive oil',
    nameAr: 'زيت زيتون',
    category: 'sauces',
    defaultUnit: 'ml',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['zeit zeitoun', 'extra virgin olive oil', 'زيت الزيتون'],
    isCommonStaple: true,
    isPerishable: false,
    priceLowMinor: 30000,
    priceAvgMinor: 42000,
    priceHighMinor: 60000,
    priceUnit: 'l',
    priceQuantity: 1,
  },
  {
    slug: 'sunflower-oil',
    name: 'vegetable oil',
    nameAr: 'زيت',
    category: 'sauces',
    defaultUnit: 'ml',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['oil', 'sunflower oil', 'cooking oil', 'زيت عباد الشمس'],
    isCommonStaple: true,
    isPerishable: false,
    priceLowMinor: 6500,
    priceAvgMinor: 8000,
    priceHighMinor: 10000,
    priceUnit: 'l',
    priceQuantity: 1,
  },
  {
    slug: 'tomato-paste',
    name: 'tomato paste',
    nameAr: 'صلصة طماطم',
    category: 'sauces',
    defaultUnit: 'tbsp',
    gramsPerPiece: 16,
    allergens: [],
    aliases: ['salsa', 'tomato puree', 'صلصه'],
    isCommonStaple: true,
    isPerishable: false,
    priceLowMinor: 2000,
    priceAvgMinor: 2800,
    priceHighMinor: 3800,
    priceUnit: 'can',
    priceQuantity: 1,
  },
  {
    slug: 'vinegar',
    name: 'vinegar',
    nameAr: 'خل',
    category: 'sauces',
    defaultUnit: 'ml',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['khal', 'white vinegar', 'خل أبيض'],
    isCommonStaple: true,
    isPerishable: false,
    priceLowMinor: 1500,
    priceAvgMinor: 2200,
    priceHighMinor: 3000,
    priceUnit: 'l',
    priceQuantity: 1,
  },
  {
    slug: 'tahini',
    name: 'tahini',
    nameAr: 'طحينة',
    category: 'sauces',
    defaultUnit: 'tbsp',
    gramsPerPiece: 15,
    allergens: ['sesame'],
    aliases: ['tehina', 'sesame paste', 'طحينه'],
    isCommonStaple: false,
    isPerishable: false,
    priceLowMinor: 6000,
    priceAvgMinor: 8000,
    priceHighMinor: 11000,
    priceUnit: 'pack',
    priceQuantity: 1,
  },
  {
    slug: 'honey',
    name: 'honey',
    nameAr: 'عسل',
    category: 'pantry',
    defaultUnit: 'tbsp',
    gramsPerPiece: 21,
    allergens: [],
    aliases: ['asal', 'عسل نحل'],
    isCommonStaple: false,
    isPerishable: false,
    priceLowMinor: 12000,
    priceAvgMinor: 18000,
    priceHighMinor: 28000,
    priceUnit: 'pack',
    priceQuantity: 1,
  },
  {
    slug: 'sugar',
    name: 'sugar',
    nameAr: 'سكر',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['sokkar', 'white sugar', 'سكر أبيض'],
    isCommonStaple: true,
    isPerishable: false,
    priceLowMinor: 2800,
    priceAvgMinor: 3400,
    priceHighMinor: 4200,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'peanut-butter',
    name: 'peanut butter',
    nameAr: 'زبدة فول سوداني',
    category: 'pantry',
    defaultUnit: 'tbsp',
    gramsPerPiece: 16,
    allergens: ['peanuts'],
    aliases: ['pb', 'زبده فول سوداني'],
    isCommonStaple: false,
    isPerishable: false,
    priceLowMinor: 12000,
    priceAvgMinor: 16000,
    priceHighMinor: 22000,
    priceUnit: 'pack',
    priceQuantity: 1,
  },
  {
    slug: 'oats',
    name: 'oats',
    nameAr: 'شوفان',
    category: 'carbs',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['gluten'],
    aliases: ['oatmeal', 'rolled oats', 'شوفان مجروش'],
    isCommonStaple: false,
    isPerishable: false,
    priceLowMinor: 7000,
    priceAvgMinor: 9500,
    priceHighMinor: 13000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'walnuts',
    name: 'walnuts',
    nameAr: 'عين جمل',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['nuts'],
    aliases: ['walnut', 'ein gamal', 'عين الجمل'],
    isCommonStaple: false,
    isPerishable: false,
    priceLowMinor: 45000,
    priceAvgMinor: 60000,
    priceHighMinor: 80000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },

  // --- Spices --------------------------------------------------------------
  {
    slug: 'salt',
    name: 'salt',
    nameAr: 'ملح',
    category: 'spices',
    defaultUnit: 'tsp',
    gramsPerPiece: 6,
    allergens: [],
    aliases: ['malh', 'table salt', 'ملح طعام'],
    isCommonStaple: true,
    isPerishable: false,
    priceLowMinor: 500,
    priceAvgMinor: 800,
    priceHighMinor: 1200,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'black-pepper',
    name: 'black pepper',
    nameAr: 'فلفل أسود',
    category: 'spices',
    defaultUnit: 'tsp',
    gramsPerPiece: 2,
    allergens: [],
    aliases: ['pepper', 'felfel eswed', 'فلفل اسود'],
    isCommonStaple: true,
    isPerishable: false,
    priceLowMinor: 20000,
    priceAvgMinor: 28000,
    priceHighMinor: 38000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'cumin',
    name: 'cumin',
    nameAr: 'كمون',
    category: 'spices',
    defaultUnit: 'tsp',
    gramsPerPiece: 2,
    allergens: [],
    aliases: ['kamoun', 'كمون مطحون'],
    isCommonStaple: true,
    isPerishable: false,
    priceLowMinor: 15000,
    priceAvgMinor: 20000,
    priceHighMinor: 28000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'paprika',
    name: 'paprika',
    nameAr: 'بابريكا',
    category: 'spices',
    defaultUnit: 'tsp',
    gramsPerPiece: 2,
    allergens: [],
    aliases: ['sweet paprika', 'فلفل أحمر مطحون'],
    isCommonStaple: false,
    isPerishable: false,
    priceLowMinor: 14000,
    priceAvgMinor: 19000,
    priceHighMinor: 26000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'coriander-ground',
    name: 'ground coriander',
    nameAr: 'كزبرة ناشفة',
    category: 'spices',
    defaultUnit: 'tsp',
    gramsPerPiece: 2,
    allergens: [],
    aliases: ['dry coriander', 'كزبره ناشفه'],
    isCommonStaple: true,
    isPerishable: false,
    priceLowMinor: 10000,
    priceAvgMinor: 14000,
    priceHighMinor: 19000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'cinnamon',
    name: 'cinnamon',
    nameAr: 'قرفة',
    category: 'spices',
    defaultUnit: 'tsp',
    gramsPerPiece: 2,
    allergens: [],
    aliases: ['erfa', 'قرفه'],
    isCommonStaple: false,
    isPerishable: false,
    priceLowMinor: 16000,
    priceAvgMinor: 22000,
    priceHighMinor: 30000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'bay-leaf',
    name: 'bay leaf',
    nameAr: 'ورق لورا',
    category: 'spices',
    defaultUnit: 'piece',
    gramsPerPiece: 1,
    allergens: [],
    aliases: ['laurel', 'ورق لوري'],
    isCommonStaple: true,
    isPerishable: false,
    priceLowMinor: 8000,
    priceAvgMinor: 12000,
    priceHighMinor: 18000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'chili-flakes',
    name: 'chili flakes',
    nameAr: 'شطة',
    category: 'spices',
    defaultUnit: 'tsp',
    gramsPerPiece: 2,
    allergens: [],
    aliases: ['shatta', 'red pepper flakes', 'شطه'],
    isCommonStaple: false,
    isPerishable: false,
    priceLowMinor: 14000,
    priceAvgMinor: 19000,
    priceHighMinor: 26000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
  {
    slug: 'dukkah',
    name: 'dukkah',
    nameAr: 'دقة',
    category: 'spices',
    defaultUnit: 'tbsp',
    gramsPerPiece: 10,
    allergens: ['nuts', 'sesame'],
    aliases: ['duqqa', 'دقه'],
    isCommonStaple: false,
    isPerishable: false,
    priceLowMinor: 18000,
    priceAvgMinor: 24000,
    priceHighMinor: 32000,
    priceUnit: 'kg',
    priceQuantity: 1,
  },
];

/** Fast lookup by slug. */
export const INGREDIENTS_BY_SLUG = new Map(
  INGREDIENT_CATALOGUE.map((ingredient) => [ingredient.slug, ingredient]),
);

/** Ingredients assumed present in nearly every kitchen. */
export const COMMON_STAPLE_SLUGS = INGREDIENT_CATALOGUE.filter((i) => i.isCommonStaple).map(
  (i) => i.slug,
);
