// GENERATED FILE — do not edit.
//
// Source: data/ingredients/catalogue.csv
// Regenerate: npm run ingredients:import
//
// Recognition data only: canonical name, Arabic name, aliases, category,
// default unit. Prices live in src/features/pricing/price-data.ts, because an
// ingredient the app can recognise does not have to be one it can price.
import type { CatalogueIngredient } from './catalogue.ts';

export const GENERATED_INGREDIENTS: readonly CatalogueIngredient[] = [
  {
    slug: 'almonds',
    name: 'almonds',
    nameAr: 'لوز',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['nuts'],
    aliases: ['لوز', 'loz', 'almond'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'anchovy',
    name: 'anchovies',
    nameAr: 'أنشوجة',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['fish'],
    aliases: ['anchovies', 'أنشوجة', 'انشوفي'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'anise',
    name: 'anise',
    nameAr: 'ينسون',
    category: 'spices',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['ينسون', 'yansoon', 'aniseed'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'apples',
    name: 'apples',
    nameAr: 'تفاح',
    category: 'fruit',
    defaultUnit: 'piece',
    gramsPerPiece: 160,
    allergens: [],
    aliases: ['apple', 'tofah', 'تفاحة'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'apricot',
    name: 'apricots',
    nameAr: 'مشمش',
    category: 'fruit',
    defaultUnit: 'piece',
    gramsPerPiece: 40,
    allergens: [],
    aliases: ['apricot', 'مشمش', 'meshmesh'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'artichoke',
    name: 'artichoke',
    nameAr: 'خرشوف',
    category: 'vegetables',
    defaultUnit: 'piece',
    gramsPerPiece: 130,
    allergens: [],
    aliases: ['kharshouf', 'خرشوف', 'ardi shawki'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'asparagus',
    name: 'asparagus',
    nameAr: 'هليون',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['هليون', 'اسبراجوس'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'avocado',
    name: 'avocado',
    nameAr: 'أفوكادو',
    category: 'vegetables',
    defaultUnit: 'piece',
    gramsPerPiece: 200,
    allergens: [],
    aliases: ['افوكادو', 'أفوكادو', 'avocados'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'baba-ganoush',
    name: 'baba ganoush',
    nameAr: 'بابا غنوج',
    category: 'sauces',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['sesame'],
    aliases: ['بابا غنوج', 'متبل'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'bacon-beef',
    name: 'beef bacon',
    nameAr: 'بيكون بقري',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: 20,
    allergens: [],
    aliases: ['beef bacon', 'بيكون'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'baguette',
    name: 'baguette',
    nameAr: 'عيش فينو',
    category: 'bakery',
    defaultUnit: 'piece',
    gramsPerPiece: 120,
    allergens: ['gluten'],
    aliases: ['fino', 'عيش فينو', 'فينو'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'baking-chocolate',
    name: 'dark chocolate',
    nameAr: 'شوكولاتة داكنة',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['soy'],
    aliases: ['شوكولاتة دارك', 'dark chocolate'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'baking-powder',
    name: 'baking powder',
    nameAr: 'بيكنج بودر',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['بيكنج بودر', 'baking soda', 'بيكربونات'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'baladi-bread',
    name: 'baladi bread',
    nameAr: 'عيش بلدي',
    category: 'bakery',
    defaultUnit: 'piece',
    gramsPerPiece: 90,
    allergens: ['gluten'],
    aliases: ['aish', 'aish baladi', 'eish', 'eish baladi', 'pita', 'flatbread', 'bread', 'عيش', 'خبز'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'bananas',
    name: 'bananas',
    nameAr: 'موز',
    category: 'fruit',
    defaultUnit: 'piece',
    gramsPerPiece: 120,
    allergens: [],
    aliases: ['banana', 'moz', 'موزة'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'barley',
    name: 'barley',
    nameAr: 'شعير',
    category: 'carbs',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['gluten'],
    aliases: ['شعير', 'shaeer'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'basil',
    name: 'basil',
    nameAr: 'ريحان',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['ريحان', 'rihan', 'basilica'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'basmati-rice',
    name: 'basmati rice',
    nameAr: 'أرز بسمتي',
    category: 'carbs',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['بسمتي', 'basmati'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'bay-leaf',
    name: 'bay leaf',
    nameAr: 'ورق لورا',
    category: 'spices',
    defaultUnit: 'piece',
    gramsPerPiece: 1,
    allergens: [],
    aliases: ['laurel', 'ورق لوري'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'bbq-sauce',
    name: 'barbecue sauce',
    nameAr: 'صوص باربكيو',
    category: 'sauces',
    defaultUnit: 'ml',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['باربكيو', 'bbq'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'beef-cubes',
    name: 'beef cubes',
    nameAr: 'لحمة مكعبات',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['stewing beef', 'beef chunks', 'لحمة', 'لحم بقري'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'beef-steak',
    name: 'beef steak',
    nameAr: 'استيك بقري',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: 250,
    allergens: [],
    aliases: ['steak', 'beef steaks', 'entrecote', 'انتريكوت', 'استيك'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'beetroot',
    name: 'beetroot',
    nameAr: 'بنجر',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: 150,
    allergens: [],
    aliases: ['beets', 'beet', 'بنجر', 'شمندر'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'bell-pepper',
    name: 'bell pepper',
    nameAr: 'فلفل ألوان',
    category: 'vegetables',
    defaultUnit: 'piece',
    gramsPerPiece: 140,
    allergens: [],
    aliases: ['capsicum', 'sweet pepper', 'فلفل رومي'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'black-eyed-peas',
    name: 'black-eyed peas',
    nameAr: 'لوبيا',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['lobia', 'لوبيا مجففة'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'black-pepper',
    name: 'black pepper',
    nameAr: 'فلفل أسود',
    category: 'spices',
    defaultUnit: 'tsp',
    gramsPerPiece: 2,
    allergens: [],
    aliases: ['pepper', 'felfel eswed', 'فلفل اسود'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'breadcrumbs',
    name: 'breadcrumbs',
    nameAr: 'بقسماط',
    category: 'bakery',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['gluten'],
    aliases: ['بقسماط', 'bosmat', 'rusk'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'broccoli',
    name: 'broccoli',
    nameAr: 'بروكلي',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: 400,
    allergens: [],
    aliases: ['بروكلي', 'broccolli'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'brown-rice',
    name: 'brown rice',
    nameAr: 'أرز بني',
    category: 'carbs',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['ارز بني'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'brown-sugar',
    name: 'brown sugar',
    nameAr: 'سكر بني',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['سكر بني', 'demerara'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'bulgur',
    name: 'bulgur',
    nameAr: 'برغل',
    category: 'carbs',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['gluten'],
    aliases: ['borghol', 'cracked wheat', 'برغل ناعم'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'butter',
    name: 'butter',
    nameAr: 'زبدة',
    category: 'dairy',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['dairy'],
    aliases: ['zebda', 'زبده'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'buttermilk',
    name: 'buttermilk',
    nameAr: 'لبن رايب',
    category: 'dairy',
    defaultUnit: 'ml',
    gramsPerPiece: null,
    allergens: ['dairy'],
    aliases: ['لبن رايب', 'rayeb'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'cabbage',
    name: 'cabbage',
    nameAr: 'كرنب',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: 1000,
    allergens: [],
    aliases: ['koronb', 'كرنب', 'ملفوف'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'calamari',
    name: 'calamari',
    nameAr: 'كاليماري',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['shellfish'],
    aliases: ['squid', 'كاليماري', 'حبار', 'سبيط'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'capers',
    name: 'capers',
    nameAr: 'كبر',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['كبر', 'كبار'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'caraway',
    name: 'caraway',
    nameAr: 'كراوية',
    category: 'spices',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['كراوية', 'karawya'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'cardamom',
    name: 'cardamom',
    nameAr: 'حبهان',
    category: 'spices',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['حبهان', 'hab han', 'hail'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'carrots',
    name: 'carrots',
    nameAr: 'جزر',
    category: 'vegetables',
    defaultUnit: 'piece',
    gramsPerPiece: 70,
    allergens: [],
    aliases: ['carrot', 'gazar', 'جزر بلدي'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'cashews',
    name: 'cashews',
    nameAr: 'كاجو',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['nuts'],
    aliases: ['كاجو', 'cashew'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'cauliflower',
    name: 'cauliflower',
    nameAr: 'قرنبيط',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: 800,
    allergens: [],
    aliases: ['arnabeet', 'قرنبيط', 'زهرة'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'celery',
    name: 'celery',
    nameAr: 'كرفس',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: 50,
    allergens: [],
    aliases: ['كرفس', 'karafs'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'cheddar',
    name: 'cheddar cheese',
    nameAr: 'جبنة شيدر',
    category: 'dairy',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['dairy'],
    aliases: ['cheddar', 'شيدر', 'جبنة شيدر'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'cherry-tomato',
    name: 'cherry tomatoes',
    nameAr: 'طماطم شيري',
    category: 'vegetables',
    defaultUnit: 'piece',
    gramsPerPiece: 15,
    allergens: [],
    aliases: ['شيري', 'طماطم شيري', 'cherry tomatos'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'chia',
    name: 'chia seeds',
    nameAr: 'بذور الشيا',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['شيا', 'chia'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'chicken-breast',
    name: 'chicken breast',
    nameAr: 'صدور فراخ',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: 180,
    allergens: [],
    aliases: ['chicken', 'chicken breasts', 'firakh', 'فراخ', 'صدر فراخ', 'دجاج'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'chicken-liver',
    name: 'chicken livers',
    nameAr: 'كبدة فراخ',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['kebda farakh', 'كبدة فراخ'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'chicken-thigh',
    name: 'chicken thighs',
    nameAr: 'أوراك فراخ',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: 130,
    allergens: [],
    aliases: ['chicken thigh', 'drumsticks', 'أوراك', 'وراك فراخ'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'chicken-wings',
    name: 'chicken wings',
    nameAr: 'أجنحة فراخ',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: 40,
    allergens: [],
    aliases: ['wings', 'اجنحة', 'جوانح'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'chickpeas',
    name: 'chickpeas',
    nameAr: 'حمص',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['garbanzo', 'hummus beans', 'حمص حب'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'chili-flakes',
    name: 'chili flakes',
    nameAr: 'شطة',
    category: 'spices',
    defaultUnit: 'tsp',
    gramsPerPiece: 2,
    allergens: [],
    aliases: ['shatta', 'red pepper flakes', 'شطه'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'chili-pepper',
    name: 'chili pepper',
    nameAr: 'شطة خضراء',
    category: 'vegetables',
    defaultUnit: 'piece',
    gramsPerPiece: 15,
    allergens: [],
    aliases: ['chilli', 'hot pepper', 'فلفل حار', 'فلفل أخضر حار'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'chili-powder',
    name: 'chili powder',
    nameAr: 'شطة مطحونة',
    category: 'spices',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['red pepper powder'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'chocolate',
    name: 'chocolate',
    nameAr: 'شوكولاتة',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['dairy', 'soy'],
    aliases: ['شوكولاتة', 'شيكولاتة', 'chocolate bar'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'cinnamon',
    name: 'cinnamon',
    nameAr: 'قرفة',
    category: 'spices',
    defaultUnit: 'tsp',
    gramsPerPiece: 2,
    allergens: [],
    aliases: ['erfa', 'قرفه'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'cloves',
    name: 'cloves',
    nameAr: 'قرنفل',
    category: 'spices',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['قرنفل', 'عويدة'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'cocoa',
    name: 'cocoa powder',
    nameAr: 'كاكاو',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['كاكاو', 'cocoa'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'coconut',
    name: 'coconut',
    nameAr: 'جوز الهند',
    category: 'fruit',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['جوز الهند', 'coconut flesh', 'كوكونت'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'coconut-flakes',
    name: 'desiccated coconut',
    nameAr: 'جوز هند مبشور',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['جوز هند مبشور', 'coconut flakes'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'coconut-milk',
    name: 'coconut milk',
    nameAr: 'لبن جوز الهند',
    category: 'sauces',
    defaultUnit: 'ml',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['لبن جوز الهند', 'coconut cream'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'coffee',
    name: 'coffee',
    nameAr: 'بن',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['قهوة', 'بن', 'coffee beans'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'condensed-milk',
    name: 'condensed milk',
    nameAr: 'لبن مكثف',
    category: 'dairy',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['dairy'],
    aliases: ['لبن مكثف', 'sweetened condensed milk'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'coriander',
    name: 'coriander',
    nameAr: 'كزبرة',
    category: 'vegetables',
    defaultUnit: 'bunch',
    gramsPerPiece: 50,
    allergens: [],
    aliases: ['cilantro', 'kozbara', 'كزبره خضراء'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'coriander-ground',
    name: 'coriander seeds',
    nameAr: 'كزبرة ناشفة',
    category: 'spices',
    defaultUnit: 'tsp',
    gramsPerPiece: 2,
    allergens: [],
    aliases: ['كزبره ناشفه'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'corn',
    name: 'sweetcorn',
    nameAr: 'ذرة',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['corn', 'maize', 'ذرة', 'درة'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'corn-oil',
    name: 'corn oil',
    nameAr: 'زيت ذرة',
    category: 'pantry',
    defaultUnit: 'ml',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['زيت ذرة', 'زيت الذرة'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'corn-syrup',
    name: 'corn syrup',
    nameAr: 'شراب الذرة',
    category: 'pantry',
    defaultUnit: 'ml',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['شراب ذرة', 'glucose syrup'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'cornflour',
    name: 'cornflour',
    nameAr: 'نشا',
    category: 'carbs',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['cornstarch', 'نشا', 'نشاء'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'cornmeal',
    name: 'cornmeal',
    nameAr: 'دقيق ذرة',
    category: 'carbs',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['دقيق ذرة', 'polenta'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'couscous',
    name: 'couscous',
    nameAr: 'كسكسي',
    category: 'carbs',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['gluten'],
    aliases: ['كسكسي', 'kuskusi'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'crab',
    name: 'crab',
    nameAr: 'كابوريا',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['shellfish'],
    aliases: ['kabouria', 'كابوريا', 'سلطعون'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'cream',
    name: 'cooking cream',
    nameAr: 'كريمة طهي',
    category: 'dairy',
    defaultUnit: 'ml',
    gramsPerPiece: null,
    allergens: ['dairy'],
    aliases: ['heavy cream', 'double cream', 'krema', 'كريمه'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'cream-cheese',
    name: 'cream cheese',
    nameAr: 'جبنة كريمي',
    category: 'dairy',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['dairy'],
    aliases: ['جبنة كريمي', 'philadelphia', 'كيري'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'croissant',
    name: 'croissant',
    nameAr: 'كرواسون',
    category: 'bakery',
    defaultUnit: 'piece',
    gramsPerPiece: 60,
    allergens: ['gluten', 'dairy', 'eggs'],
    aliases: ['كرواسون', 'كروسان'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'cucumber',
    name: 'cucumber',
    nameAr: 'خيار',
    category: 'vegetables',
    defaultUnit: 'piece',
    gramsPerPiece: 100,
    allergens: [],
    aliases: ['cucumbers', 'khiar', 'خيار بلدي'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'cumin',
    name: 'cumin',
    nameAr: 'كمون',
    category: 'spices',
    defaultUnit: 'tsp',
    gramsPerPiece: 2,
    allergens: [],
    aliases: ['kamoun', 'كمون مطحون'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'curry-powder',
    name: 'curry powder',
    nameAr: 'كاري',
    category: 'spices',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['كاري', 'curry'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'date-syrup',
    name: 'date syrup',
    nameAr: 'دبس التمر',
    category: 'sauces',
    defaultUnit: 'ml',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['دبس تمر', 'date molasses'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'dates',
    name: 'dates',
    nameAr: 'تمر',
    category: 'fruit',
    defaultUnit: 'piece',
    gramsPerPiece: 8,
    allergens: [],
    aliases: ['balah', 'tamr', 'بلح'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'dill',
    name: 'dill',
    nameAr: 'شبت',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['shabat', 'شبت', 'شبنت'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'dried-apricot',
    name: 'qamar el din',
    nameAr: 'قمر الدين',
    category: 'fruit',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['قمر الدين', 'مشمش مجفف', 'amar el din'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'duck',
    name: 'duck',
    nameAr: 'بط',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['بطة', 'لحم بط'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'dukkah',
    name: 'dukkah',
    nameAr: 'دقة',
    category: 'spices',
    defaultUnit: 'tbsp',
    gramsPerPiece: 10,
    allergens: ['nuts', 'sesame'],
    aliases: ['duqqa', 'دقه'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'edamame',
    name: 'edamame',
    nameAr: 'إدامامي',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['soy'],
    aliases: ['ادامامي', 'edamame beans'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'egg-white',
    name: 'egg whites',
    nameAr: 'بياض بيض',
    category: 'dairy',
    defaultUnit: 'piece',
    gramsPerPiece: 33,
    allergens: ['eggs'],
    aliases: ['بياض البيض', 'egg white'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'egg-yolk',
    name: 'egg yolks',
    nameAr: 'صفار بيض',
    category: 'dairy',
    defaultUnit: 'piece',
    gramsPerPiece: 17,
    allergens: ['eggs'],
    aliases: ['صفار البيض', 'egg yolk'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'eggplant',
    name: 'eggplant',
    nameAr: 'باذنجان',
    category: 'vegetables',
    defaultUnit: 'piece',
    gramsPerPiece: 220,
    allergens: [],
    aliases: ['aubergine', 'betingan', 'بتنجان'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'eggs',
    name: 'eggs',
    nameAr: 'بيض',
    category: 'protein',
    defaultUnit: 'piece',
    gramsPerPiece: 55,
    allergens: ['eggs'],
    aliases: ['egg', 'beid', 'بيضة', 'بيضه'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'falafel-mix',
    name: 'falafel mix',
    nameAr: 'دقيق طعمية',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['taameya mix', 'طعمية', 'دقيق الطعمية'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'fava-beans',
    name: 'fava beans',
    nameAr: 'فول',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['foul', 'ful', 'ful medames', 'foul medames', 'فول مدمس'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'fennel-seed',
    name: 'fennel seeds',
    nameAr: 'شمر',
    category: 'spices',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['شمر', 'fennel'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'fenugreek',
    name: 'fenugreek',
    nameAr: 'حلبة',
    category: 'spices',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['حلبة', 'helba'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'figs',
    name: 'figs',
    nameAr: 'تين',
    category: 'fruit',
    defaultUnit: 'piece',
    gramsPerPiece: 50,
    allergens: [],
    aliases: ['fig', 'تين', 'teen'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'flaxseed',
    name: 'flaxseed',
    nameAr: 'بذر الكتان',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['بذرة الكتان', 'linseed'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'flour',
    name: 'flour',
    nameAr: 'دقيق',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['gluten'],
    aliases: ['all purpose flour', 'plain flour', 'دقيق فاخر'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'freekeh',
    name: 'freekeh',
    nameAr: 'فريك',
    category: 'carbs',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['gluten'],
    aliases: ['فريك', 'frikeh', 'farik'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'frozen-fries',
    name: 'frozen fries',
    nameAr: 'بطاطس مجمدة',
    category: 'frozen',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['بطاطس محمرة', 'french fries', 'شيبسي'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'frozen-mixed-veg',
    name: 'frozen mixed vegetables',
    nameAr: 'خضار مشكل مجمد',
    category: 'frozen',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['خضار مجمد', 'mixed veg'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'garlic',
    name: 'garlic',
    nameAr: 'ثوم',
    category: 'vegetables',
    defaultUnit: 'clove',
    gramsPerPiece: 5,
    allergens: [],
    aliases: ['toum', 'tom', 'garlic cloves', 'فص ثوم'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'garlic-powder',
    name: 'garlic powder',
    nameAr: 'ثوم بودرة',
    category: 'spices',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['ثوم بودرة', 'garlic granules'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'gelatin',
    name: 'gelatin',
    nameAr: 'جيلاتين',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['جيلاتين', 'jelly powder'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'ghee',
    name: 'ghee',
    nameAr: 'سمنة',
    category: 'dairy',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['dairy'],
    aliases: ['samna', 'سمنة', 'clarified butter', 'سمن'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'ginger',
    name: 'ginger',
    nameAr: 'زنجبيل',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['زنجبيل', 'ganzabeel', 'root ginger'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'ginger-ground',
    name: 'ground ginger',
    nameAr: 'زنجبيل مطحون',
    category: 'spices',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['زنجبيل مطحون'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'grapes',
    name: 'grapes',
    nameAr: 'عنب',
    category: 'fruit',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['عنب', 'enab', 'grape'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'green-beans',
    name: 'green beans',
    nameAr: 'فاصوليا خضراء',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['فاصوليا خضراء', 'french beans'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'green-lentils',
    name: 'green lentils',
    nameAr: 'عدس أخضر',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['عدس اخضر', 'brown lentils', 'عدس بجبة'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'green-onion',
    name: 'green onion',
    nameAr: 'بصل أخضر',
    category: 'vegetables',
    defaultUnit: 'bunch',
    gramsPerPiece: 80,
    allergens: [],
    aliases: ['scallion', 'spring onion', 'بصل اخضر'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'green-peas',
    name: 'green peas',
    nameAr: 'بسلة',
    category: 'frozen',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['peas', 'besella', 'بسله'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'ground-beef',
    name: 'ground beef',
    nameAr: 'لحمة مفرومة',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['minced beef', 'mince', 'minced meat', 'kofta meat', 'لحمة مفرومه', 'مفروم'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'guava',
    name: 'guava',
    nameAr: 'جوافة',
    category: 'fruit',
    defaultUnit: 'piece',
    gramsPerPiece: 120,
    allergens: [],
    aliases: ['جوافة', 'gawafa', 'guavas'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'halloumi',
    name: 'halloumi',
    nameAr: 'حلومي',
    category: 'dairy',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['dairy'],
    aliases: ['حلومي', 'halloum'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'hazelnuts',
    name: 'hazelnuts',
    nameAr: 'بندق',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['nuts'],
    aliases: ['بندق', 'bondok', 'hazelnut'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'herring',
    name: 'herring',
    nameAr: 'رنجة',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['fish'],
    aliases: ['renga', 'رنجة', 'ringa'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'hibiscus',
    name: 'hibiscus',
    nameAr: 'كركديه',
    category: 'spices',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['كركديه', 'karkade'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'honey',
    name: 'honey',
    nameAr: 'عسل',
    category: 'pantry',
    defaultUnit: 'tbsp',
    gramsPerPiece: 21,
    allergens: [],
    aliases: ['asal', 'عسل نحل'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'hot-dog',
    name: 'hot dog sausage',
    nameAr: 'هوت دوج',
    category: 'protein',
    defaultUnit: 'piece',
    gramsPerPiece: 50,
    allergens: [],
    aliases: ['hotdog', 'frankfurter', 'هوت دوج'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'hot-sauce',
    name: 'hot sauce',
    nameAr: 'صوص حار',
    category: 'sauces',
    defaultUnit: 'ml',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['شطة سائلة', 'tabasco', 'صوص حار'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'hummus-dip',
    name: 'hummus',
    nameAr: 'حمص بالطحينة',
    category: 'sauces',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['sesame'],
    aliases: ['hommos', 'حمص', 'houmous'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'ice',
    name: 'ice',
    nameAr: 'ثلج',
    category: 'other',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['ثلج', 'ice cubes'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'ice-cream',
    name: 'ice cream',
    nameAr: 'آيس كريم',
    category: 'frozen',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['dairy'],
    aliases: ['ايس كريم', 'آيس كريم', 'gelato'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'icing-sugar',
    name: 'icing sugar',
    nameAr: 'سكر بودرة',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['سكر بودرة', 'powdered sugar'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'kashkaval',
    name: 'kashkaval',
    nameAr: 'جبنة قشقوان',
    category: 'dairy',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['dairy'],
    aliases: ['قشقوان', 'kashkawan'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'ketchup',
    name: 'ketchup',
    nameAr: 'كاتشب',
    category: 'sauces',
    defaultUnit: 'ml',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['كاتشب', 'catsup', 'صوص طماطم'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'kidney-beans',
    name: 'kidney beans',
    nameAr: 'فاصوليا حمراء',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['red beans', 'فاصوليا حمراء', 'rajma'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'kiwi',
    name: 'kiwi',
    nameAr: 'كيوي',
    category: 'fruit',
    defaultUnit: 'piece',
    gramsPerPiece: 80,
    allergens: [],
    aliases: ['كيوي', 'kiwifruit'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'kofta',
    name: 'kofta',
    nameAr: 'كفتة',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: 60,
    allergens: [],
    aliases: ['kufta', 'كفتة', 'كفته'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'labneh',
    name: 'labneh',
    nameAr: 'لبنة',
    category: 'dairy',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['dairy'],
    aliases: ['لبنة', 'labne'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'lamb',
    name: 'lamb',
    nameAr: 'لحم ضاني',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['mutton', 'lamb meat', 'ضاني', 'لحم غنم', 'خروف'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'lamb-chops',
    name: 'lamb chops',
    nameAr: 'ريش ضاني',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: 90,
    allergens: [],
    aliases: ['chops', 'riyash', 'ريش', 'ريش لحم'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'lasagne-sheets',
    name: 'lasagne sheets',
    nameAr: 'شرائح لازانيا',
    category: 'carbs',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['gluten'],
    aliases: ['lasagna', 'لازانيا'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'leek',
    name: 'leek',
    nameAr: 'كرات',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: 120,
    allergens: [],
    aliases: ['كرات', 'korrat', 'leeks'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'lemon',
    name: 'lemon',
    nameAr: 'ليمون',
    category: 'fruit',
    defaultUnit: 'piece',
    gramsPerPiece: 60,
    allergens: [],
    aliases: ['lemons', 'lime', 'lamoun', 'ليمون أخضر'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'lemon-juice',
    name: 'lemon juice',
    nameAr: 'عصير ليمون',
    category: 'pantry',
    defaultUnit: 'ml',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['عصير الليمون', 'lime juice'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'lentils',
    name: 'red lentils',
    nameAr: 'عدس',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['lentil', 'ads', 'عدس أصفر', 'عدس احمر'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'lettuce',
    name: 'lettuce',
    nameAr: 'خس',
    category: 'vegetables',
    defaultUnit: 'piece',
    gramsPerPiece: 350,
    allergens: [],
    aliases: ['khass', 'romaine', 'خس بلدي'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'liver',
    name: 'beef liver',
    nameAr: 'كبدة',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['kebda', 'كبده', 'كبدة اسكندراني'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'luncheon-meat',
    name: 'luncheon meat',
    nameAr: 'لانشون',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: 20,
    allergens: [],
    aliases: ['luncheon', 'لانشون', 'لحم بارد'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'mackerel',
    name: 'mackerel',
    nameAr: 'ماكريل',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: 250,
    allergens: ['fish'],
    aliases: ['ماكريل', 'scomber', 'سمك ماكريل'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'mandarin',
    name: 'mandarins',
    nameAr: 'يوسفي',
    category: 'fruit',
    defaultUnit: 'piece',
    gramsPerPiece: 90,
    allergens: [],
    aliases: ['tangerine', 'يوسفي', 'مندرين'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'mango',
    name: 'mango',
    nameAr: 'مانجو',
    category: 'fruit',
    defaultUnit: 'piece',
    gramsPerPiece: 250,
    allergens: [],
    aliases: ['مانجو', 'manga', 'mangoes'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'mayonnaise',
    name: 'mayonnaise',
    nameAr: 'مايونيز',
    category: 'sauces',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['eggs'],
    aliases: ['مايونيز', 'mayo'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'melon',
    name: 'melon',
    nameAr: 'شمام',
    category: 'fruit',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['cantaloupe', 'شمام', 'كانتالوب'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'milk',
    name: 'milk',
    nameAr: 'لبن',
    category: 'dairy',
    defaultUnit: 'ml',
    gramsPerPiece: null,
    allergens: ['dairy'],
    aliases: ['laban', 'full cream milk', 'حليب'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'mint',
    name: 'mint',
    nameAr: 'نعناع',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['naana', 'نعناع', 'نعنع'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'mixed-spice',
    name: 'mixed spice',
    nameAr: 'بهارات مشكلة',
    category: 'spices',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['بهارات', 'mixed spices', 'seven spices'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'molasses',
    name: 'black molasses',
    nameAr: 'عسل أسود',
    category: 'sauces',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['عسل اسود', 'asal eswed', 'treacle'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'molokhia',
    name: 'molokhia',
    nameAr: 'ملوخية',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['mulukhiyah', 'jute leaves', 'ملوخيه', 'ملوخية مفرومة'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'mozzarella',
    name: 'mozzarella',
    nameAr: 'موتزاريلا',
    category: 'dairy',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['dairy'],
    aliases: ['mozarella', 'pizza cheese', 'جبنة موتزاريلا', 'جبنه موزاريلا'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'mullet',
    name: 'mullet',
    nameAr: 'بوري',
    category: 'protein',
    defaultUnit: 'piece',
    gramsPerPiece: 300,
    allergens: ['fish'],
    aliases: ['bouri', 'بوري', 'grey mullet'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'mushroom',
    name: 'mushrooms',
    nameAr: 'مشروم',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: 20,
    allergens: [],
    aliases: ['mushroom', 'عيش الغراب', 'مشروم', 'champignon'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'mussels',
    name: 'mussels',
    nameAr: 'بلح البحر',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['shellfish'],
    aliases: ['بلح البحر', 'mussel'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'mustard',
    name: 'mustard',
    nameAr: 'مسطردة',
    category: 'sauces',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['مسطردة', 'خردل', 'dijon'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'mustard-seed',
    name: 'mustard seeds',
    nameAr: 'حب الخردل',
    category: 'spices',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['خردل حب', 'mustard seeds'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'nigella',
    name: 'nigella seeds',
    nameAr: 'حبة البركة',
    category: 'spices',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['حبة البركة', 'black seed', 'حبة بركة'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'noodles',
    name: 'noodles',
    nameAr: 'نودلز',
    category: 'carbs',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['gluten'],
    aliases: ['نودلز', 'instant noodles', 'indomie'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'nutmeg',
    name: 'nutmeg',
    nameAr: 'جوزة الطيب',
    category: 'spices',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['جوزة الطيب', 'جوز الطيب'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'oats',
    name: 'oats',
    nameAr: 'شوفان',
    category: 'carbs',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['gluten'],
    aliases: ['oatmeal', 'rolled oats', 'شوفان مجروش'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'okra',
    name: 'okra',
    nameAr: 'بامية',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['bamya', 'lady fingers', 'باميه'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'olive-oil',
    name: 'olive oil',
    nameAr: 'زيت زيتون',
    category: 'sauces',
    defaultUnit: 'ml',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['zeit zeitoun', 'extra virgin olive oil', 'زيت الزيتون'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'olives',
    name: 'olives',
    nameAr: 'زيتون',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: 5,
    allergens: [],
    aliases: ['zeitoun', 'زيتون', 'green olives', 'black olives'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'onion-powder',
    name: 'onion powder',
    nameAr: 'بصل بودرة',
    category: 'spices',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['بصل بودرة'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'onions',
    name: 'onions',
    nameAr: 'بصل',
    category: 'vegetables',
    defaultUnit: 'piece',
    gramsPerPiece: 110,
    allergens: [],
    aliases: ['onion', 'basal', 'بصل أحمر', 'بصل أبيض'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'orange-blossom',
    name: 'orange blossom water',
    nameAr: 'ماء زهر',
    category: 'pantry',
    defaultUnit: 'ml',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['ماء الزهر', 'mazaher'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'oranges',
    name: 'oranges',
    nameAr: 'برتقال',
    category: 'fruit',
    defaultUnit: 'piece',
    gramsPerPiece: 180,
    allergens: [],
    aliases: ['orange', 'برتقال', 'برتقاله'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'oregano',
    name: 'oregano',
    nameAr: 'أوريجانو',
    category: 'spices',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['اوريجانو', 'زعتر بري'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'paprika',
    name: 'paprika',
    nameAr: 'بابريكا',
    category: 'spices',
    defaultUnit: 'tsp',
    gramsPerPiece: 2,
    allergens: [],
    aliases: ['sweet paprika', 'فلفل أحمر مطحون'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'parmesan',
    name: 'parmesan',
    nameAr: 'جبنة بارميزان',
    category: 'dairy',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['dairy'],
    aliases: ['parmigiano', 'بارميزان', 'بارمزان'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'parsley',
    name: 'parsley',
    nameAr: 'بقدونس',
    category: 'vegetables',
    defaultUnit: 'bunch',
    gramsPerPiece: 60,
    allergens: [],
    aliases: ['ba2dounes', 'بقدونس أخضر'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'pasta',
    name: 'pasta',
    nameAr: 'مكرونة',
    category: 'carbs',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['gluten'],
    aliases: ['macaroni', 'spaghetti', 'penne', 'makarona', 'مكرونه'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'pastrami',
    name: 'basterma',
    nameAr: 'بسطرمة',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['basterma', 'pastirma', 'بسطرمه', 'بسطرمة'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'peach',
    name: 'peaches',
    nameAr: 'خوخ',
    category: 'fruit',
    defaultUnit: 'piece',
    gramsPerPiece: 150,
    allergens: [],
    aliases: ['peach', 'خوخ'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'peanut-butter',
    name: 'peanut butter',
    nameAr: 'زبدة فول سوداني',
    category: 'pantry',
    defaultUnit: 'tbsp',
    gramsPerPiece: 16,
    allergens: ['peanuts'],
    aliases: ['pb', 'زبده فول سوداني'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'peanuts',
    name: 'peanuts',
    nameAr: 'فول سوداني',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['peanuts'],
    aliases: ['فول سوداني', 'sudani', 'peanut'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'pear',
    name: 'pears',
    nameAr: 'كمثرى',
    category: 'fruit',
    defaultUnit: 'piece',
    gramsPerPiece: 170,
    allergens: [],
    aliases: ['pear', 'كمثرى', 'كمترى'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'phyllo',
    name: 'filo pastry',
    nameAr: 'عجينة جلاش',
    category: 'bakery',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['gluten'],
    aliases: ['goulash', 'جلاش', 'filo', 'phyllo'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'pickles',
    name: 'pickles',
    nameAr: 'مخلل',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['torshi', 'مخلل', 'طرشي', 'pickle'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'pigeon',
    name: 'pigeon',
    nameAr: 'حمام',
    category: 'protein',
    defaultUnit: 'piece',
    gramsPerPiece: 300,
    allergens: [],
    aliases: ['hamam', 'حمام', 'حمامة'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'pine-nuts',
    name: 'pine nuts',
    nameAr: 'صنوبر',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['nuts'],
    aliases: ['صنوبر', 'snoubar'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'pineapple',
    name: 'pineapple',
    nameAr: 'أناناس',
    category: 'fruit',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['اناناس', 'أناناس'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'pistachios',
    name: 'pistachios',
    nameAr: 'فستق',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['nuts'],
    aliases: ['فستق', 'fostok', 'pistachio'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'pita-bread',
    name: 'pita bread',
    nameAr: 'عيش شامي',
    category: 'bakery',
    defaultUnit: 'piece',
    gramsPerPiece: 80,
    allergens: ['gluten'],
    aliases: ['شامي', 'عيش شامي', 'pitta'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'plum',
    name: 'plums',
    nameAr: 'برقوق',
    category: 'fruit',
    defaultUnit: 'piece',
    gramsPerPiece: 60,
    allergens: [],
    aliases: ['plum', 'برقوق'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'pomegranate',
    name: 'pomegranate',
    nameAr: 'رمان',
    category: 'fruit',
    defaultUnit: 'piece',
    gramsPerPiece: 280,
    allergens: [],
    aliases: ['رمان', 'romman'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'pomegranate-molasses',
    name: 'pomegranate molasses',
    nameAr: 'دبس رمان',
    category: 'sauces',
    defaultUnit: 'ml',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['دبس الرمان', 'debs romman'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'potatoes',
    name: 'potatoes',
    nameAr: 'بطاطس',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: 150,
    allergens: [],
    aliases: ['potato', 'batates'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'powdered-milk',
    name: 'powdered milk',
    nameAr: 'لبن بودرة',
    category: 'dairy',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['dairy'],
    aliases: ['milk powder', 'لبن بودرة', 'بودرة لبن'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'prunes',
    name: 'prunes',
    nameAr: 'برقوق مجفف',
    category: 'fruit',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['برقوق مجفف'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'puff-pastry',
    name: 'puff pastry',
    nameAr: 'عجينة باف',
    category: 'bakery',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['gluten', 'dairy'],
    aliases: ['باف باستري', 'عجين مورق'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'pumpkin',
    name: 'pumpkin',
    nameAr: 'قرع عسلي',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['قرع', 'قرع عسلي', 'squash'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'pumpkin-seeds',
    name: 'pumpkin seeds',
    nameAr: 'لب أبيض',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['لب ابيض', 'pepitas'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'quinoa',
    name: 'quinoa',
    nameAr: 'كينوا',
    category: 'carbs',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['كينوا', 'quinua'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'rabbit',
    name: 'rabbit',
    nameAr: 'أرنب',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['أرانب', 'لحم أرنب'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'radish',
    name: 'radish',
    nameAr: 'فجل',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: 20,
    allergens: [],
    aliases: ['فجل', 'figl'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'raisins',
    name: 'raisins',
    nameAr: 'زبيب',
    category: 'fruit',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['zabib', 'زبيب', 'sultanas'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'rice',
    name: 'rice',
    nameAr: 'أرز',
    category: 'carbs',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['egyptian rice', 'white rice', 'roz', 'رز'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'rocket',
    name: 'rocket',
    nameAr: 'جرجير',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['arugula', 'gargeer', 'جرجير'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'rose-water',
    name: 'rose water',
    nameAr: 'ماء ورد',
    category: 'pantry',
    defaultUnit: 'ml',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['ماء الورد', 'maward'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'rosemary',
    name: 'rosemary',
    nameAr: 'روزماري',
    category: 'spices',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['روزماري', 'حصى البان'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'roumy-cheese',
    name: 'roumy cheese',
    nameAr: 'جبنة رومي',
    category: 'dairy',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['dairy'],
    aliases: ['romy', 'ras cheese', 'جبنه رومي'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'saffron',
    name: 'saffron',
    nameAr: 'زعفران',
    category: 'spices',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['زعفران', 'zaafaran'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'salmon',
    name: 'salmon',
    nameAr: 'سالمون',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: 180,
    allergens: ['fish'],
    aliases: ['salmon fillet', 'سلمون', 'سالمون', 'samak salmon'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'salt',
    name: 'salt',
    nameAr: 'ملح',
    category: 'spices',
    defaultUnit: 'tsp',
    gramsPerPiece: 6,
    allergens: [],
    aliases: ['malh', 'table salt', 'ملح طعام'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'salted-fish',
    name: 'fesikh',
    nameAr: 'فسيخ',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['fish'],
    aliases: ['fesikh', 'فسيخ', 'salted mullet'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'sardines',
    name: 'sardines',
    nameAr: 'سردين',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['fish'],
    aliases: ['sardine', 'سردين', 'سردينة'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'sausage',
    name: 'beef sausage',
    nameAr: 'سجق',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: 40,
    allergens: [],
    aliases: ['sogo2', 'sogok', 'سجق بلدي'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'sea-bass',
    name: 'sea bass',
    nameAr: 'قاروص',
    category: 'protein',
    defaultUnit: 'piece',
    gramsPerPiece: 400,
    allergens: ['fish'],
    aliases: ['qaros', 'قاروص', 'وقار', 'branzino'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'sea-bream',
    name: 'sea bream',
    nameAr: 'دنيس',
    category: 'protein',
    defaultUnit: 'piece',
    gramsPerPiece: 350,
    allergens: ['fish'],
    aliases: ['denis', 'دنيس', 'gilthead'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'semolina',
    name: 'semolina',
    nameAr: 'سميد',
    category: 'carbs',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['gluten'],
    aliases: ['سميد', 'smeed', 'farina'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'sesame-oil',
    name: 'sesame oil',
    nameAr: 'زيت سمسم',
    category: 'pantry',
    defaultUnit: 'ml',
    gramsPerPiece: null,
    allergens: ['sesame'],
    aliases: ['زيت السمسم'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'sesame-seeds',
    name: 'sesame seeds',
    nameAr: 'سمسم',
    category: 'spices',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['sesame'],
    aliases: ['سمسم', 'simsim'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'shrimp',
    name: 'shrimp',
    nameAr: 'جمبري',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: 12,
    allergens: ['shellfish'],
    aliases: ['prawns', 'gambari', 'جمبرى'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'soy-sauce',
    name: 'soy sauce',
    nameAr: 'صوص الصويا',
    category: 'sauces',
    defaultUnit: 'ml',
    gramsPerPiece: null,
    allergens: ['soy', 'gluten'],
    aliases: ['صويا صوص', 'soya sauce', 'صوص صويا'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'soybeans',
    name: 'soybeans',
    nameAr: 'فول الصويا',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['soy'],
    aliases: ['soya', 'فول صويا', 'soy beans'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'spinach',
    name: 'spinach',
    nameAr: 'سبانخ',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['sabanekh', 'سبانخ مفرومة'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'split-peas',
    name: 'split peas',
    nameAr: 'بسلة مجروشة',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['بسلة مجروشة', 'yellow split peas'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'spring-garlic',
    name: 'spring garlic',
    nameAr: 'ثوم أخضر',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['ثوم اخضر', 'green garlic'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'stock-cube',
    name: 'stock cube',
    nameAr: 'مكعب مرقة',
    category: 'pantry',
    defaultUnit: 'piece',
    gramsPerPiece: 10,
    allergens: [],
    aliases: ['maggi', 'مكعب مرقة', 'bouillon', 'شوربة مكعبات'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'strawberry',
    name: 'strawberries',
    nameAr: 'فراولة',
    category: 'fruit',
    defaultUnit: 'g',
    gramsPerPiece: 20,
    allergens: [],
    aliases: ['strawberry', 'فراولة', 'فراوله'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'sugar',
    name: 'sugar',
    nameAr: 'سكر',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['sokkar', 'white sugar', 'سكر أبيض'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'sumac',
    name: 'sumac',
    nameAr: 'سماق',
    category: 'spices',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['سماق', 'summaq'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'sun-dried-tomato',
    name: 'sun-dried tomatoes',
    nameAr: 'طماطم مجففة',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['طماطم مجففة', 'sundried tomato'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'sunflower-oil',
    name: 'vegetable oil',
    nameAr: 'زيت',
    category: 'sauces',
    defaultUnit: 'ml',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['oil', 'sunflower oil', 'cooking oil', 'زيت عباد الشمس'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'sunflower-seeds',
    name: 'sunflower seeds',
    nameAr: 'لب',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['لب', 'seeds', 'لب سوري'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'sweet-potato',
    name: 'sweet potato',
    nameAr: 'بطاطا',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: 180,
    allergens: [],
    aliases: ['batata', 'بطاطا', 'yam'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'tahini',
    name: 'tahini',
    nameAr: 'طحينة',
    category: 'sauces',
    defaultUnit: 'tbsp',
    gramsPerPiece: 15,
    allergens: ['sesame'],
    aliases: ['tehina', 'sesame paste', 'طحينه'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'tahini-salad',
    name: 'tahina salad',
    nameAr: 'صلصة طحينة',
    category: 'sauces',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['sesame'],
    aliases: ['tahina'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'taro',
    name: 'taro',
    nameAr: 'قلقاس',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['olocas', 'قلقاس', 'colocasia'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'tea',
    name: 'tea',
    nameAr: 'شاي',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['شاي', 'shay', 'tea leaves'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'thyme-dried',
    name: 'thyme',
    nameAr: 'زعتر',
    category: 'spices',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['زعتر', 'zaatar', 'zatar'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'tilapia',
    name: 'tilapia',
    nameAr: 'بلطي',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: 300,
    allergens: ['fish'],
    aliases: ['fish', 'bolti', 'بلطى', 'سمك'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'toast-bread',
    name: 'toast bread',
    nameAr: 'عيش توست',
    category: 'bakery',
    defaultUnit: 'slice',
    gramsPerPiece: 30,
    allergens: ['gluten'],
    aliases: ['toast', 'white bread', 'sandwich bread', 'توست'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'tofu',
    name: 'tofu',
    nameAr: 'توفو',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['soy'],
    aliases: ['توفو', 'bean curd'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'tomato-paste',
    name: 'tomato paste',
    nameAr: 'صلصة طماطم',
    category: 'sauces',
    defaultUnit: 'tbsp',
    gramsPerPiece: 16,
    allergens: [],
    aliases: ['salsa', 'tomato puree', 'صلصه'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'tomato-sauce',
    name: 'tomato sauce',
    nameAr: 'صلصة طماطم',
    category: 'sauces',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['passata', 'صوص طماطم مطبوخ'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'tomatoes',
    name: 'tomatoes',
    nameAr: 'طماطم',
    category: 'vegetables',
    defaultUnit: 'piece',
    gramsPerPiece: 120,
    allergens: [],
    aliases: ['tomato', 'oota', 'طماطم حمراء', 'قوطة'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'tortilla',
    name: 'tortilla',
    nameAr: 'تورتيلا',
    category: 'bakery',
    defaultUnit: 'piece',
    gramsPerPiece: 60,
    allergens: ['gluten'],
    aliases: ['تورتيلا', 'wrap', 'خبز تورتيلا'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'tuna-can',
    name: 'canned tuna',
    nameAr: 'تونة',
    category: 'protein',
    defaultUnit: 'can',
    gramsPerPiece: 140,
    allergens: ['fish'],
    aliases: ['tuna', 'tuna can', 'تونه'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'turkey',
    name: 'turkey',
    nameAr: 'ديك رومي',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['turkey breast', 'رومي', 'ديك رومي'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'turmeric',
    name: 'turmeric',
    nameAr: 'كركم',
    category: 'spices',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['كركم', 'kurkum'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'turnip',
    name: 'turnip',
    nameAr: 'لفت',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: 120,
    allergens: [],
    aliases: ['لفت', 'left'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'vanilla',
    name: 'vanilla',
    nameAr: 'فانيليا',
    category: 'spices',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['فانيليا', 'vanilla extract', 'فانيلا'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'veal',
    name: 'veal',
    nameAr: 'بتلو',
    category: 'protein',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['bitello', 'بتلو', 'لحم بتلو'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'vermicelli',
    name: 'vermicelli',
    nameAr: 'شعرية',
    category: 'carbs',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['gluten'],
    aliases: ['sha3reya', 'shaareya', 'شعريه'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'vinegar',
    name: 'vinegar',
    nameAr: 'خل',
    category: 'sauces',
    defaultUnit: 'ml',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['khal', 'white vinegar', 'خل أبيض'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'vinegar-apple',
    name: 'apple cider vinegar',
    nameAr: 'خل تفاح',
    category: 'pantry',
    defaultUnit: 'ml',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['خل التفاح', 'cider vinegar'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'walnuts',
    name: 'walnuts',
    nameAr: 'عين جمل',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['nuts'],
    aliases: ['walnut', 'ein gamal', 'عين الجمل'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'water',
    name: 'water',
    nameAr: 'ماء',
    category: 'other',
    defaultUnit: 'ml',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['مياه', 'ماء', 'maya'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'watercress',
    name: 'watercress',
    nameAr: 'بقدونس مائي',
    category: 'vegetables',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['cress', 'حريف', 'رشاد'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'watermelon',
    name: 'watermelon',
    nameAr: 'بطيخ',
    category: 'fruit',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['بطيخ', 'batikh'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'white-beans',
    name: 'white beans',
    nameAr: 'فاصوليا بيضاء',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['fasolia', 'cannellini', 'فاصوليا'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'white-cheese',
    name: 'white cheese',
    nameAr: 'جبنة بيضاء',
    category: 'dairy',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: ['dairy'],
    aliases: ['feta', 'gebna beida', 'domiati', 'جبنه بيضاء', 'جبنة فيتا'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'white-pepper',
    name: 'white pepper',
    nameAr: 'فلفل أبيض',
    category: 'spices',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['فلفل ابيض'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'worcestershire',
    name: 'worcestershire sauce',
    nameAr: 'صوص ورشستر',
    category: 'sauces',
    defaultUnit: 'ml',
    gramsPerPiece: null,
    allergens: ['fish'],
    aliases: ['ورشستر', 'worcester'],
    isCommonStaple: false,
    isPerishable: false,
  },
  {
    slug: 'yeast',
    name: 'yeast',
    nameAr: 'خميرة',
    category: 'pantry',
    defaultUnit: 'g',
    gramsPerPiece: null,
    allergens: [],
    aliases: ['خميرة', 'khamira', 'instant yeast'],
    isCommonStaple: true,
    isPerishable: false,
  },
  {
    slug: 'yogurt',
    name: 'yogurt',
    nameAr: 'زبادي',
    category: 'dairy',
    defaultUnit: 'g',
    gramsPerPiece: 105,
    allergens: ['dairy'],
    aliases: ['zabady', 'plain yoghurt', 'زبادى'],
    isCommonStaple: false,
    isPerishable: true,
  },
  {
    slug: 'zucchini',
    name: 'zucchini',
    nameAr: 'كوسة',
    category: 'vegetables',
    defaultUnit: 'piece',
    gramsPerPiece: 160,
    allergens: [],
    aliases: ['courgette', 'kosa', 'كوسه'],
    isCommonStaple: false,
    isPerishable: true,
  },
];
