import { GENERATED_INGREDIENTS } from './catalogue.generated.ts';
import type { Allergen, IngredientCategory, Unit } from '@/types/domain';

/**
 * Canonical ingredient catalogue for the Egyptian launch market.
 *
 * The catalogue data itself lives in data/ingredients/catalogue.csv and is
 * generated into `catalogue.generated.ts`; this file owns the type, the
 * derived indexes, and nothing else. The catalogue is:
 *   1. bundled into the app for offline autocomplete and matching, and
 *   2. compiled into `supabase/seed.sql` by `scripts/generate-seed.ts`.
 *
 * After editing, run `npm run seed:generate` and commit the regenerated SQL.
 *
 * NOTE: this module must only use `import type` so the seed generator can load
 * it with Node's type-stripping loader.
 */

export type CatalogueIngredient = {
  /** Stable slug. Becomes the ingredient's natural key in Postgres. */
  slug: string;
  name: string;
  nameAr: string;
  category: IngredientCategory;
  defaultUnit: Unit;
  /** Grams in one `piece`. Null for ingredients that are not countable. */
  gramsPerPiece: number | null;
  allergens: Allergen[];
  /** Match aliases: transliterations, Arabic spellings, regional names, plurals. */
  aliases: string[];
  /** Assumed present in most kitchens unless the user says otherwise. */
  isCommonStaple: boolean;
  /** Spoils quickly; expiry dates are enforced strictly for these. */
  isPerishable: boolean;
};

/*
 * NOTE: prices deliberately do NOT live here.
 *
 * Recognising an ingredient and knowing what it costs are separate problems
 * with separate data. Keeping them in one record meant every new ingredient
 * needed a price before it could be added — which is how you end up inventing
 * figures to fill a table. Prices live in data/prices/eg.csv, are imported by
 * `npm run prices:import`, and are keyed by the slug above. An ingredient with
 * no price row is a normal, supported state.
 */

/**
 * Every ingredient the app can recognise.
 *
 * Authored in data/ingredients/catalogue.csv and generated by
 * `npm run ingredients:import`, so adding a food is a row in a sheet rather
 * than an edit to application code. The importer rejects duplicate slugs,
 * unknown categories and — most importantly — any alias claimed by two
 * ingredients, which would otherwise silently bind a word to whichever entry
 * loaded first.
 */
export const INGREDIENT_CATALOGUE: readonly CatalogueIngredient[] = GENERATED_INGREDIENTS;

/** Fast lookup by slug. */
export const INGREDIENTS_BY_SLUG = new Map(
  INGREDIENT_CATALOGUE.map((ingredient) => [ingredient.slug, ingredient]),
);

/** Ingredients assumed present in nearly every kitchen. */
export const COMMON_STAPLE_SLUGS = INGREDIENT_CATALOGUE.filter((i) => i.isCommonStaple).map(
  (i) => i.slug,
);

/**
 * Non-seasoning things that are nonetheless always there.
 *
 * The line: a thing may be assumed if it is a cooking medium, an aromatic, or
 * a small-quantity cupboard support that keeps indefinitely. It may NOT be
 * assumed if it forms the substance of a dish — because that is precisely the
 * thing you run out of, and precisely the thing the user is telling us about.
 *
 * So oil, water, onions and garlic are here; rice, pasta, potatoes, lentils
 * and fava beans are deliberately not, even though the catalogue marks all of
 * them "staple" for the pantry UI. You can plan a meal around having rice. You
 * cannot plan one around having salt.
 */
/**
 * The only things assumed present in every kitchen, ever.
 *
 * TWO ENTRIES, AND THAT IS THE POINT. This list was much longer and it made
 * the product lie. Someone with rice and tomatoes opened Tomato Rice and was
 * told they had six of seven ingredients and needed only coriander — because
 * onions, garlic, stock cube, cumin, tomato paste and oil were all silently on
 * hand. They are not. Every one of those is something you can be out of, and
 * being out of it is exactly what the user opened the app to find out.
 *
 * The test for membership is not "is this common?". Nearly everything in a
 * kitchen is common. It is: **would anyone ever fail to cook because they
 * lacked it, and would they want to be told?** Water, no. Salt, no — a kitchen
 * without salt is not a kitchen, and a results screen that says "you are
 * missing salt" is noise that trains people to ignore missing-ingredient
 * counts entirely.
 *
 * Everything else — oil, onions, garlic, cumin, pepper, sugar, flour, stock —
 * is a real ingredient. If a particular cook always has them, that is a fact
 * about that cook, and they say so: `UserPreferences.alwaysAvailableIngredients`
 * or a pantry item marked "assume I have this". It is never inferred for them.
 */
const UNIVERSAL_BASIC_SLUGS: ReadonlySet<string> = new Set(['water', 'salt']);

/**
 * May this be assumed present without the user saying so?
 *
 * See `UNIVERSAL_BASIC_SLUGS`. The answer is almost always no.
 */
export function isUniversalBasic(ingredient: CatalogueIngredient): boolean {
  // A perishable is never assumed, whatever else is true of it.
  if (ingredient.isPerishable) return false;
  return UNIVERSAL_BASIC_SLUGS.has(ingredient.slug);
}

/**
 * What the app OFFERS as "things I always have", pre-ticked during onboarding.
 *
 * The difference from the list above is who decides. These are suggestions on
 * a screen the user looks at and can untick; they become available because
 * somebody chose them, and the app can say so when asked why a recipe counts
 * as cookable. Nothing here is assumed for a user who has not made that
 * choice.
 *
 * Chosen for an Egyptian kitchen: the things that live in the cupboard beside
 * the stove and get replaced without thinking about it. Deliberately short —
 * a list of forty is not reviewed, it is accepted.
 */
export const SUGGESTED_KITCHEN_BASICS: readonly string[] = [
  // The cupboard beside the stove.
  'sunflower-oil',
  'olive-oil',
  'onions',
  'garlic',
  'sugar',
  'flour',
  'tomato-paste',
  'stock-cube',
  'vinegar',
  // The spice rack. Present in most kitchens that cook Egyptian food, and
  // nobody abandons a recipe for want of a bay leaf — but that is still a
  // fact about the cook, not about the world, so it is offered rather than
  // assumed. Saffron, cardamom and sumac are deliberately NOT here: those are
  // bought for a dish, and telling someone they have saffron is a lie with
  // consequences at the till.
  'black-pepper',
  'cumin',
  'cinnamon',
  'paprika',
  'chili-flakes',
  'turmeric',
  'oregano',
  'bay-leaf',
  'coriander-ground',
];

/** Slugs the matching engine treats as present in every kitchen. Two of them. */
export const UNIVERSAL_BASICS: ReadonlySet<string> = new Set(
  INGREDIENT_CATALOGUE.filter(isUniversalBasic).map((i) => i.slug),
);
