import { GENERATED_INGREDIENTS } from './catalogue.generated.ts';
import type { Allergen, IngredientCategory, Unit } from '@/types/domain';

/**
 * Canonical ingredient catalogue for the Egyptian launch market.
 *
 * The catalogue data itself lives in data/ingredients/catalogue.csv and is
 * generated into `catalogue.generated.ts`; this file owns the type, the
 * derived indexes, and nothing else. The catalogue is:
 *   1. bundled into the app for offline autocomplete and matching, and
 *   2. compiled into `supabase/seed.sql` by `scripts/generate-seed.ts`.
 *
 * After editing, run `npm run seed:generate` and commit the regenerated SQL.
 *
 * NOTE: this module must only use `import type` so the seed generator can load
 * it with Node's type-stripping loader.
 */

export type CatalogueIngredient = {
  /** Stable slug. Becomes the ingredient's natural key in Postgres. */
  slug: string;
  name: string;
  nameAr: string;
  category: IngredientCategory;
  defaultUnit: Unit;
  /** Grams in one `piece`. Null for ingredients that are not countable. */
  gramsPerPiece: number | null;
  allergens: Allergen[];
  /** Match aliases: transliterations, Arabic spellings, regional names, plurals. */
  aliases: string[];
  /** Assumed present in most kitchens unless the user says otherwise. */
  isCommonStaple: boolean;
  /** Spoils quickly; expiry dates are enforced strictly for these. */
  isPerishable: boolean;
};

/*
 * NOTE: prices deliberately do NOT live here.
 *
 * Recognising an ingredient and knowing what it costs are separate problems
 * with separate data. Keeping them in one record meant every new ingredient
 * needed a price before it could be added — which is how you end up inventing
 * figures to fill a table. Prices live in data/prices/eg.csv, are imported by
 * `npm run prices:import`, and are keyed by the slug above. An ingredient with
 * no price row is a normal, supported state.
 */

/**
 * Every ingredient the app can recognise.
 *
 * Authored in data/ingredients/catalogue.csv and generated by
 * `npm run ingredients:import`, so adding a food is a row in a sheet rather
 * than an edit to application code. The importer rejects duplicate slugs,
 * unknown categories and — most importantly — any alias claimed by two
 * ingredients, which would otherwise silently bind a word to whichever entry
 * loaded first.
 */
export const INGREDIENT_CATALOGUE: readonly CatalogueIngredient[] = GENERATED_INGREDIENTS;

/** Fast lookup by slug. */
export const INGREDIENTS_BY_SLUG = new Map(
  INGREDIENT_CATALOGUE.map((ingredient) => [ingredient.slug, ingredient]),
);

/** Ingredients assumed present in nearly every kitchen. */
export const COMMON_STAPLE_SLUGS = INGREDIENT_CATALOGUE.filter((i) => i.isCommonStaple).map(
  (i) => i.slug,
);

/**
 * Non-seasoning things that are nonetheless always there.
 *
 * The line: a thing may be assumed if it is a cooking medium, an aromatic, or
 * a small-quantity cupboard support that keeps indefinitely. It may NOT be
 * assumed if it forms the substance of a dish — because that is precisely the
 * thing you run out of, and precisely the thing the user is telling us about.
 *
 * So oil, water, onions and garlic are here; rice, pasta, potatoes, lentils
 * and fava beans are deliberately not, even though the catalogue marks all of
 * them "staple" for the pantry UI. You can plan a meal around having rice. You
 * cannot plan one around having salt.
 */
const ALWAYS_ON_HAND_SLUGS: ReadonlySet<string> = new Set([
  // Cooking media.
  'water',
  'olive-oil',
  'sunflower-oil',
  'corn-oil',
  'vinegar',
  // Aromatics. Present in essentially every kitchen that cooks at all, and
  // nobody decides what to make based on having an onion. Without these,
  // "chicken, rice, tomato" matched nothing even allowing a missing
  // ingredient, because almost every savoury recipe starts with one of them.
  'onions',
  'garlic',
  // Cupboard supports, used in spoonfuls and kept for months. Distinct from
  // the carbohydrates above: nobody's dinner plan hinges on baking powder.
  'sugar',
  'flour',
  'stock-cube',
  'yeast',
  'baking-powder',
  'tomato-paste',
]);

/**
 * May this be assumed present without the user saying so?
 *
 * **This is NOT `isCommonStaple`, and conflating the two was a release-blocking
 * bug.** `isCommonStaple` marks a cupboard item for the PANTRY UI — it is what
 * pre-ticks "always assume I have this" when someone adds rice. Reusing it for
 * the matching engine meant rice, pasta, potatoes, onions, garlic, lentils,
 * fava beans, flour, sugar, yeast, stock cubes and tomato paste were all
 * silently on hand for everybody. The consequence was not subtle: three
 * recipes became cookable from a COMPLETELY EMPTY KITCHEN, and since they
 * needed nothing they matched every search — so "what can I cook with chicken
 * and rice" and "what can I cook with banana and oats" both answered koshari.
 *
 * The line drawn here is: can you plan a meal around it? Rice, yes — you can
 * be out of rice, and being out of it changes what you cook. Cumin, no.
 *
 * Only seasonings, cooking media and water. Everything with substance is a
 * real ingredient the user has to actually have, or that counts as missing.
 */
export function isAssumedOnHand(ingredient: CatalogueIngredient): boolean {
  // A perishable is never assumed, whatever else is true of it.
  if (ingredient.isPerishable) return false;
  return ingredient.category === 'spices' || ALWAYS_ON_HAND_SLUGS.has(ingredient.slug);
}

/** Slugs the matching engine treats as present in every kitchen. */
export const ASSUMED_ON_HAND_SLUGS: ReadonlySet<string> = new Set(
  INGREDIENT_CATALOGUE.filter(isAssumedOnHand).map((i) => i.slug),
);
