// GENERATED FILE — do not edit.
//
// Source: data/commerce-demo/
// Regenerate: npm run commerce:demo
//
// A DEVELOPMENT CATALOGUE, NOT A SUPERMARKET. No company named here exists,
// no commercial agreement stands behind it, and no price is real. The merchant
// is flagged `isDemo` and is never enabled, so nothing can mistake it for a
// partner by reading the data.
import type { Allergen, Availability, Unit } from '@/types/domain';
import type { MappingSource } from '@/types/commerce';

export type DemoProductRow = {
  readonly externalId: string;
  readonly sku: string | null;
  readonly name: string;
  readonly nameAr: string | null;
  readonly brand: string | null;
  readonly packQuantity: number | null;
  readonly packUnit: Unit | null;
  readonly priceMinor: number;
  readonly availability: Availability;
  /**
   * NULL MEANS THE MERCHANT PUBLISHES NO ALLERGEN DATA, which is not the same
   * as an empty array. Empty is a declaration of none; null is an absence of
   * one, and the sourcing engine refuses to auto-select a null for a customer
   * with allergies rather than assuming it is safe.
   */
  readonly allergens: readonly Allergen[] | null;
  readonly isActive: boolean;
};

export type DemoMappingRow = {
  readonly ingredientSlug: string;
  readonly productExternalId: string;
  readonly source: MappingSource;
  readonly confidence: number;
  readonly isVerified: boolean;
  readonly isBlocked: boolean;
};

export const DEMO_MERCHANT = {
  "slug": "akalt-demo-market",
  "name": "AKALT Demo Market (development only)",
  "nameAr": "سوق أكلت التجريبي (للتطوير فقط)",
  "country": "EG",
  "currency": "EGP",
  "fulfilmentMode": "dashboard",
  "commissionRateBasisPoints": 1000,
  "merchantKeepsDeliveryFee": true,
  "isEnabled": false,
  "isDemo": true
} as const;

export const DEMO_LOCATION = {
  "externalId": "demo-branch-1",
  "name": "Demo Branch — Maadi",
  "nameAr": "فرع التجربة — المعادي",
  "city": "Cairo",
  "deliveryAreas": [
    "Maadi",
    "Degla",
    "Sarayat El Maadi"
  ],
  "deliveryFeeMinor": 2500,
  "minimumOrderMinor": 10000,
  "estimatedDeliveryMinutes": 55,
  "isAcceptingOrders": false
} as const;

export const DEMO_PRODUCTS: readonly DemoProductRow[] = [
  {
    externalId: 'dm-chk-500',
    sku: 'DM-CHK-500',
    name: 'Fresh Chicken Breast 500g',
    nameAr: 'صدور فراخ طازة ٥٠٠ جم',
    brand: 'Demo Farms',
    packQuantity: 500,
    packUnit: 'g',
    priceMinor: 9000,
    availability: 'in_stock',
    allergens: [],
    isActive: true,
  },
  {
    externalId: 'dm-chk-1000',
    sku: 'DM-CHK-1000',
    name: 'Fresh Chicken Breast 1kg',
    nameAr: 'صدور فراخ طازة ١ كجم',
    brand: 'Demo Farms',
    packQuantity: 1,
    packUnit: 'kg',
    priceMinor: 17000,
    availability: 'in_stock',
    allergens: [],
    isActive: true,
  },
  {
    externalId: 'dm-chk-mar-500',
    sku: 'DM-CHK-MAR-500',
    name: 'Marinated Chicken Breast 500g',
    nameAr: 'صدور فراخ متبلة ٥٠٠ جم',
    brand: 'Demo Farms',
    packQuantity: 500,
    packUnit: 'g',
    priceMinor: 10500,
    availability: 'in_stock',
    allergens: ['dairy'],
    isActive: true,
  },
  {
    externalId: 'dm-rice-1000',
    sku: 'DM-RICE-1000',
    name: 'Egyptian Short Grain Rice 1kg',
    nameAr: 'رز مصري ١ كجم',
    brand: 'Demo Mills',
    packQuantity: 1,
    packUnit: 'kg',
    priceMinor: 4500,
    availability: 'in_stock',
    allergens: [],
    isActive: true,
  },
  {
    externalId: 'dm-rice-5000',
    sku: 'DM-RICE-5000',
    name: 'Egyptian Short Grain Rice 5kg',
    nameAr: 'رز مصري ٥ كجم',
    brand: 'Demo Mills',
    packQuantity: 5,
    packUnit: 'kg',
    priceMinor: 21000,
    availability: 'in_stock',
    allergens: [],
    isActive: true,
  },
  {
    externalId: 'dm-tom-1000',
    sku: 'DM-TOM-1000',
    name: 'Fresh Tomatoes 1kg',
    nameAr: 'طماطم طازة ١ كجم',
    brand: null,
    packQuantity: 1,
    packUnit: 'kg',
    priceMinor: 2200,
    availability: 'in_stock',
    allergens: [],
    isActive: true,
  },
  {
    externalId: 'dm-tom-500',
    sku: 'DM-TOM-500',
    name: 'Fresh Tomatoes 500g',
    nameAr: 'طماطم طازة ٥٠٠ جم',
    brand: null,
    packQuantity: 500,
    packUnit: 'g',
    priceMinor: 1300,
    availability: 'low_stock',
    allergens: [],
    isActive: true,
  },
  {
    externalId: 'dm-oni-1000',
    sku: 'DM-ONI-1000',
    name: 'Yellow Onions 1kg',
    nameAr: 'بصل أصفر ١ كجم',
    brand: null,
    packQuantity: 1,
    packUnit: 'kg',
    priceMinor: 1800,
    availability: 'in_stock',
    allergens: [],
    isActive: true,
  },
  {
    externalId: 'dm-milk-1000',
    sku: 'DM-MILK-1000',
    name: 'Full Cream Milk 1L',
    nameAr: 'لبن كامل الدسم ١ لتر',
    brand: 'Demo Dairy',
    packQuantity: 1,
    packUnit: 'l',
    priceMinor: 4000,
    availability: 'in_stock',
    allergens: ['dairy'],
    isActive: true,
  },
  {
    externalId: 'dm-milk-250',
    sku: 'DM-MILK-250',
    name: 'Full Cream Milk 250ml',
    nameAr: 'لبن كامل الدسم ٢٥٠ مل',
    brand: 'Demo Dairy',
    packQuantity: 250,
    packUnit: 'ml',
    priceMinor: 1400,
    availability: 'in_stock',
    allergens: ['dairy'],
    isActive: true,
  },
  {
    externalId: 'dm-egg-12',
    sku: 'DM-EGG-12',
    name: 'Table Eggs 12 pieces',
    nameAr: 'بيض مائدة ١٢ بيضة',
    brand: 'Demo Farms',
    packQuantity: 12,
    packUnit: 'piece',
    priceMinor: 9000,
    availability: 'in_stock',
    allergens: ['eggs'],
    isActive: true,
  },
  {
    externalId: 'dm-egg-30',
    sku: 'DM-EGG-30',
    name: 'Table Eggs 30 pieces',
    nameAr: 'بيض مائدة ٣٠ بيضة',
    brand: 'Demo Farms',
    packQuantity: 30,
    packUnit: 'piece',
    priceMinor: 20500,
    availability: 'in_stock',
    allergens: ['eggs'],
    isActive: true,
  },
  {
    externalId: 'dm-flour-1000',
    sku: 'DM-FLOUR-1000',
    name: 'All Purpose Flour 1kg',
    nameAr: 'دقيق فاخر ١ كجم',
    brand: 'Demo Mills',
    packQuantity: 1,
    packUnit: 'kg',
    priceMinor: 3200,
    availability: 'in_stock',
    allergens: ['gluten'],
    isActive: true,
  },
  {
    externalId: 'dm-sunoil-1000',
    sku: 'DM-SUNOIL-1000',
    name: 'Sunflower Oil 1L',
    nameAr: 'زيت عباد الشمس ١ لتر',
    brand: 'Demo Oils',
    packQuantity: 1,
    packUnit: 'l',
    priceMinor: 8500,
    availability: 'in_stock',
    allergens: [],
    isActive: true,
  },
  {
    externalId: 'dm-sunoil-2700',
    sku: 'DM-SUNOIL-2700',
    name: 'Sunflower Oil 2.7L',
    nameAr: 'زيت عباد الشمس ٢.٧ لتر',
    brand: 'Demo Oils',
    packQuantity: 2.7,
    packUnit: 'l',
    priceMinor: 21500,
    availability: 'in_stock',
    allergens: [],
    isActive: true,
  },
  {
    externalId: 'dm-olive-500',
    sku: 'DM-OLIVE-500',
    name: 'Extra Virgin Olive Oil 500ml',
    nameAr: 'زيت زيتون بكر ٥٠٠ مل',
    brand: 'Demo Groves',
    packQuantity: 500,
    packUnit: 'ml',
    priceMinor: 19000,
    availability: 'in_stock',
    allergens: [],
    isActive: true,
  },
  {
    externalId: 'dm-pasta-400',
    sku: 'DM-PASTA-400',
    name: 'Spaghetti 400g',
    nameAr: 'مكرونة اسباجتي ٤٠٠ جم',
    brand: 'Demo Pasta',
    packQuantity: 400,
    packUnit: 'g',
    priceMinor: 2400,
    availability: 'in_stock',
    allergens: ['gluten'],
    isActive: true,
  },
  {
    externalId: 'dm-cream-200',
    sku: 'DM-CREAM-200',
    name: 'Cooking Cream 200ml',
    nameAr: 'كريمة طهي ٢٠٠ مل',
    brand: 'Demo Dairy',
    packQuantity: 200,
    packUnit: 'ml',
    priceMinor: 5500,
    availability: 'in_stock',
    allergens: ['dairy'],
    isActive: true,
  },
  {
    externalId: 'dm-cream-500',
    sku: 'DM-CREAM-500',
    name: 'Cooking Cream 500ml',
    nameAr: 'كريمة طهي ٥٠٠ مل',
    brand: 'Demo Dairy',
    packQuantity: 500,
    packUnit: 'ml',
    priceMinor: 12000,
    availability: 'out_of_stock',
    allergens: ['dairy'],
    isActive: true,
  },
  {
    externalId: 'dm-parm-100',
    sku: 'DM-PARM-100',
    name: 'Grated Parmesan 100g',
    nameAr: 'جبنة بارميزان مبشورة ١٠٠ جم',
    brand: 'Demo Dairy',
    packQuantity: 100,
    packUnit: 'g',
    priceMinor: 14000,
    availability: 'in_stock',
    allergens: ['dairy'],
    isActive: true,
  },
  {
    externalId: 'dm-lentil-500',
    sku: 'DM-LENTIL-500',
    name: 'Red Lentils 500g',
    nameAr: 'عدس أحمر ٥٠٠ جم',
    brand: 'Demo Mills',
    packQuantity: 500,
    packUnit: 'g',
    priceMinor: 3800,
    availability: 'in_stock',
    allergens: [],
    isActive: true,
  },
  {
    externalId: 'dm-garlic-200',
    sku: 'DM-GARLIC-200',
    name: 'Garlic 200g',
    nameAr: 'توم ٢٠٠ جم',
    brand: null,
    packQuantity: 200,
    packUnit: 'g',
    priceMinor: 2600,
    availability: 'in_stock',
    allergens: [],
    isActive: true,
  },
  {
    externalId: 'dm-pot-2000',
    sku: 'DM-POT-2000',
    name: 'Potatoes 2kg',
    nameAr: 'بطاطس ٢ كجم',
    brand: null,
    packQuantity: 2,
    packUnit: 'kg',
    priceMinor: 3400,
    availability: 'out_of_stock',
    allergens: [],
    isActive: true,
  },
  {
    externalId: 'dm-yog-1000',
    sku: 'DM-YOG-1000',
    name: 'Plain Yoghurt 1kg',
    nameAr: 'زبادي سادة ١ كجم',
    brand: 'Demo Dairy',
    packQuantity: 1,
    packUnit: 'kg',
    priceMinor: 6000,
    availability: 'in_stock',
    allergens: ['dairy'],
    isActive: true,
  },
  {
    externalId: 'dm-butter-200',
    sku: 'DM-BUTTER-200',
    name: 'Butter 200g',
    nameAr: 'زبدة ٢٠٠ جم',
    brand: 'Demo Dairy',
    packQuantity: 200,
    packUnit: 'g',
    priceMinor: 11000,
    availability: 'in_stock',
    allergens: ['dairy'],
    isActive: true,
  },
  {
    externalId: 'dm-moz-250',
    sku: 'DM-MOZ-250',
    name: 'Mozzarella 250g',
    nameAr: 'موتزاريلا ٢٥٠ جم',
    brand: 'Demo Dairy',
    packQuantity: 250,
    packUnit: 'g',
    priceMinor: 9500,
    availability: 'in_stock',
    allergens: ['dairy'],
    isActive: true,
  },
  {
    externalId: 'dm-cumin-100',
    sku: 'DM-CUMIN-100',
    name: 'Ground Cumin 100g',
    nameAr: 'كمون مطحون ١٠٠ جم',
    brand: 'Demo Spices',
    packQuantity: 100,
    packUnit: 'g',
    priceMinor: 2800,
    availability: 'in_stock',
    allergens: [],
    isActive: true,
  },
  {
    externalId: 'dm-chick-400',
    sku: 'DM-CHICK-400',
    name: 'Canned Chickpeas 400g',
    nameAr: 'حمص معلب ٤٠٠ جم',
    brand: 'Demo Cans',
    packQuantity: 400,
    packUnit: 'g',
    priceMinor: 2900,
    availability: 'in_stock',
    allergens: [],
    isActive: true,
  },
  {
    externalId: 'dm-sugar-1000',
    sku: 'DM-SUGAR-1000',
    name: 'White Sugar 1kg',
    nameAr: 'سكر أبيض ١ كجم',
    brand: 'Demo Mills',
    packQuantity: 1,
    packUnit: 'kg',
    priceMinor: 3600,
    availability: 'in_stock',
    allergens: [],
    isActive: true,
  },
  {
    externalId: 'dm-legacy-chk',
    sku: 'DM-LEGACY-CHK',
    name: 'Discontinued Chicken Pack',
    nameAr: 'عبوة فراخ موقوفة',
    brand: 'Demo Farms',
    packQuantity: 500,
    packUnit: 'g',
    priceMinor: 7000,
    availability: 'unknown',
    allergens: [],
    isActive: false,
  },
  {
    externalId: 'dm-bakery-baladi',
    sku: 'DM-BAK-BALADI',
    name: 'Baladi Bread 5 loaves',
    nameAr: 'عيش بلدي ٥ أرغفة',
    brand: null,
    packQuantity: 5,
    packUnit: 'piece',
    priceMinor: 1500,
    availability: 'in_stock',
    allergens: null,
    isActive: true,
  },
];

export const DEMO_MAPPINGS: readonly DemoMappingRow[] = [
  {
    ingredientSlug: 'chicken-breast',
    productExternalId: 'dm-chk-500',
    source: 'manual',
    confidence: 1,
    isVerified: true,
    isBlocked: false,
  },
  {
    ingredientSlug: 'chicken-breast',
    productExternalId: 'dm-chk-1000',
    source: 'manual',
    confidence: 1,
    isVerified: true,
    isBlocked: false,
  },
  {
    ingredientSlug: 'chicken-breast',
    productExternalId: 'dm-chk-mar-500',
    source: 'name_match',
    confidence: 0.8,
    isVerified: false,
    isBlocked: false,
  },
  {
    ingredientSlug: 'chicken-breast',
    productExternalId: 'dm-legacy-chk',
    source: 'name_match',
    confidence: 0.7,
    isVerified: false,
    isBlocked: false,
  },
  {
    ingredientSlug: 'rice',
    productExternalId: 'dm-rice-1000',
    source: 'manual',
    confidence: 1,
    isVerified: true,
    isBlocked: false,
  },
  {
    ingredientSlug: 'rice',
    productExternalId: 'dm-rice-5000',
    source: 'manual',
    confidence: 1,
    isVerified: false,
    isBlocked: false,
  },
  {
    ingredientSlug: 'tomatoes',
    productExternalId: 'dm-tom-1000',
    source: 'manual',
    confidence: 1,
    isVerified: true,
    isBlocked: false,
  },
  {
    ingredientSlug: 'tomatoes',
    productExternalId: 'dm-tom-500',
    source: 'manual',
    confidence: 1,
    isVerified: false,
    isBlocked: false,
  },
  {
    ingredientSlug: 'onions',
    productExternalId: 'dm-oni-1000',
    source: 'manual',
    confidence: 1,
    isVerified: true,
    isBlocked: false,
  },
  {
    ingredientSlug: 'milk',
    productExternalId: 'dm-milk-1000',
    source: 'manual',
    confidence: 1,
    isVerified: true,
    isBlocked: false,
  },
  {
    ingredientSlug: 'milk',
    productExternalId: 'dm-milk-250',
    source: 'manual',
    confidence: 1,
    isVerified: false,
    isBlocked: false,
  },
  {
    ingredientSlug: 'eggs',
    productExternalId: 'dm-egg-12',
    source: 'manual',
    confidence: 1,
    isVerified: true,
    isBlocked: false,
  },
  {
    ingredientSlug: 'eggs',
    productExternalId: 'dm-egg-30',
    source: 'manual',
    confidence: 1,
    isVerified: false,
    isBlocked: false,
  },
  {
    ingredientSlug: 'flour',
    productExternalId: 'dm-flour-1000',
    source: 'manual',
    confidence: 1,
    isVerified: true,
    isBlocked: false,
  },
  {
    ingredientSlug: 'sunflower-oil',
    productExternalId: 'dm-sunoil-1000',
    source: 'manual',
    confidence: 1,
    isVerified: true,
    isBlocked: false,
  },
  {
    ingredientSlug: 'sunflower-oil',
    productExternalId: 'dm-sunoil-2700',
    source: 'manual',
    confidence: 1,
    isVerified: false,
    isBlocked: false,
  },
  {
    ingredientSlug: 'olive-oil',
    productExternalId: 'dm-olive-500',
    source: 'manual',
    confidence: 1,
    isVerified: true,
    isBlocked: false,
  },
  {
    ingredientSlug: 'pasta',
    productExternalId: 'dm-pasta-400',
    source: 'manual',
    confidence: 1,
    isVerified: true,
    isBlocked: false,
  },
  {
    ingredientSlug: 'cream',
    productExternalId: 'dm-cream-200',
    source: 'manual',
    confidence: 1,
    isVerified: true,
    isBlocked: false,
  },
  {
    ingredientSlug: 'cream',
    productExternalId: 'dm-cream-500',
    source: 'manual',
    confidence: 1,
    isVerified: false,
    isBlocked: false,
  },
  {
    ingredientSlug: 'parmesan',
    productExternalId: 'dm-parm-100',
    source: 'manual',
    confidence: 1,
    isVerified: true,
    isBlocked: false,
  },
  {
    ingredientSlug: 'lentils',
    productExternalId: 'dm-lentil-500',
    source: 'manual',
    confidence: 1,
    isVerified: true,
    isBlocked: false,
  },
  {
    ingredientSlug: 'garlic',
    productExternalId: 'dm-garlic-200',
    source: 'manual',
    confidence: 1,
    isVerified: true,
    isBlocked: false,
  },
  {
    ingredientSlug: 'potatoes',
    productExternalId: 'dm-pot-2000',
    source: 'manual',
    confidence: 1,
    isVerified: true,
    isBlocked: false,
  },
  {
    ingredientSlug: 'yogurt',
    productExternalId: 'dm-yog-1000',
    source: 'manual',
    confidence: 1,
    isVerified: true,
    isBlocked: false,
  },
  {
    ingredientSlug: 'butter',
    productExternalId: 'dm-butter-200',
    source: 'manual',
    confidence: 1,
    isVerified: true,
    isBlocked: false,
  },
  {
    ingredientSlug: 'mozzarella',
    productExternalId: 'dm-moz-250',
    source: 'manual',
    confidence: 1,
    isVerified: true,
    isBlocked: false,
  },
  {
    ingredientSlug: 'cumin',
    productExternalId: 'dm-cumin-100',
    source: 'manual',
    confidence: 1,
    isVerified: true,
    isBlocked: false,
  },
  {
    ingredientSlug: 'chickpeas',
    productExternalId: 'dm-chick-400',
    source: 'manual',
    confidence: 1,
    isVerified: true,
    isBlocked: false,
  },
  {
    ingredientSlug: 'sugar',
    productExternalId: 'dm-sugar-1000',
    source: 'manual',
    confidence: 1,
    isVerified: true,
    isBlocked: false,
  },
  {
    ingredientSlug: 'butter',
    productExternalId: 'dm-olive-500',
    source: 'category_fallback',
    confidence: 0.3,
    isVerified: false,
    isBlocked: true,
  },
  {
    ingredientSlug: 'baladi-bread',
    productExternalId: 'dm-bakery-baladi',
    source: 'manual',
    confidence: 1,
    isVerified: true,
    isBlocked: false,
  },
];
