import type { SupabaseClient } from '@supabase/supabase-js';

import { toAppError } from '@/lib/errors';
import type { Database } from '@/lib/supabase/database.types';
import type { CurrencyCode, Money } from '@/types/domain';

/**
 * THE UNPAID ORDER DRAFT.
 *
 * The last step Commerce-4 goes to. A draft is a real `orders` row in
 * `fulfilment_state = 'draft'`, `payment_state = 'unpaid'`, with server-priced
 * items — and it is NOT any of the following:
 *
 *   NOT A PAYMENT      — nothing has been charged and no provider was called.
 *   NOT A RESERVATION  — no stock is held; the shelf can still move underneath.
 *   NOT AN ORDER       — the merchant has not been told and cannot see it.
 *
 * Every string the draft screen shows is written against that list. "Order
 * placed" would be a lie in three separate ways.
 *
 * ALL OF IT IS DERIVED SERVER-SIDE. The client sends a revision, an address id
 * and an idempotency key; it sends no prices, no totals and no commission
 * rate, because a client that can name a price can name zero.
 */

export type OrderDraftRequest = {
  /** The revision the customer's validation was taken against. */
  readonly cartRevision: number;
  readonly addressId: string;
  /**
   * Stable across retries of the SAME attempt, new for a new attempt.
   *
   * A double tap, a dropped response and an app resumed from the background
   * are all the same request; without this they are three orders.
   */
  readonly idempotencyKey: string;
  readonly customerNote: string | null;
};

export type OrderDraft = {
  readonly id: string;
  /** `AKL-XXXX-XXXX`, generated by the database. Readable down a phone line. */
  readonly reference: string;
  readonly currency: CurrencyCode;
  readonly itemsSubtotal: Money;
  readonly deliveryFee: Money;
  readonly total: Money;
  readonly createdAt: string;
};

/**
 * Every way the server can refuse, named.
 *
 * These mirror the exceptions `create_order_draft` raises. They are a closed
 * set so a screen can say what went wrong in the customer's own language
 * rather than surfacing a Postgres message, and so a new server-side refusal
 * that nobody mapped shows up as `unknown` instead of as a blank screen.
 */
export const ORDER_DRAFT_FAILURES = [
  'not_authenticated',
  'cart_empty',
  'stale_cart_revision',
  'merchant_not_enabled',
  'merchant_not_accepting',
  'address_not_found',
  'address_incomplete',
  'outside_delivery_area',
  'product_delisted',
  'product_out_of_stock',
  'price_changed',
  'below_minimum',
  /** The refusal did not match anything above. Never silently permissive. */
  'unknown',
] as const;
export type OrderDraftFailure = (typeof ORDER_DRAFT_FAILURES)[number];

export class OrderDraftRefused extends Error {
  constructor(readonly failure: OrderDraftFailure) {
    super(`order draft refused: ${failure}`);
    this.name = 'OrderDraftRefused';
  }
}

export interface OrderDraftRepository {
  create(request: OrderDraftRequest): Promise<OrderDraft>;
}

/**
 * Reads the refusal out of whatever the driver hands back.
 *
 * `raise exception 'below_minimum'` arrives as a message that CONTAINS the
 * token rather than equals it, so this looks for a known token instead of
 * matching the whole string — and falls back to `unknown` rather than
 * guessing, because an unrecognised refusal is still a refusal.
 */
export function refusalFrom(message: string | null | undefined): OrderDraftFailure {
  if (!message) return 'unknown';
  for (const failure of ORDER_DRAFT_FAILURES) {
    if (failure !== 'unknown' && message.includes(failure)) return failure;
  }
  return 'unknown';
}

/**
 * A guest has no draft to make.
 *
 * Not an empty implementation for symmetry: a draft is owned by an account,
 * and `create_order_draft` reads `auth.uid()`. Everything upstream already
 * blocks on `not_authenticated`; this is the backstop for the case where
 * something upstream did not.
 */
export class LocalOrderDraftRepository implements OrderDraftRepository {
  async create(): Promise<OrderDraft> {
    throw new OrderDraftRefused('not_authenticated');
  }
}

export class SupabaseOrderDraftRepository implements OrderDraftRepository {
  constructor(
    private readonly client: SupabaseClient<Database>,
    private readonly userId: string,
  ) {}

  async create(request: OrderDraftRequest): Promise<OrderDraft> {
    const { data: orderId, error } = await this.client.rpc('create_order_draft', {
      p_cart_revision: request.cartRevision,
      p_address_id: request.addressId,
      p_idempotency_key: request.idempotencyKey,
      p_customer_note: request.customerNote,
    });

    if (error) throw new OrderDraftRefused(refusalFrom(error.message));
    if (!orderId) throw new OrderDraftRefused('unknown');

    // Read back rather than trust what we sent: the totals on the row are the
    // server's, computed from the catalogue, and they are what the customer
    // will be asked to pay.
    const { data, error: readError } = await this.client
      .from('orders')
      .select(
        'id, reference, currency, items_subtotal_minor, delivery_fee_minor, created_at',
      )
      .eq('id', orderId)
      .eq('user_id', this.userId)
      .single();

    if (readError) throw toAppError(readError, 'database');

    const currency = data.currency as CurrencyCode;
    return {
      id: data.id,
      reference: data.reference,
      currency,
      itemsSubtotal: { amountMinor: data.items_subtotal_minor, currency },
      deliveryFee: { amountMinor: data.delivery_fee_minor, currency },
      total: {
        amountMinor: data.items_subtotal_minor + data.delivery_fee_minor,
        currency,
      },
      createdAt: data.created_at,
    };
  }
}
