import type { SupabaseClient } from '@supabase/supabase-js';

import { toAppError } from '@/lib/errors';
import type { Database, PaymentIntentRow } from '@/lib/supabase/database.types';
import {
  REFUND_ATTEMPT_STATES,
  type OrderFulfilmentState,
  type OrderRefundStatus,
  type PaymentMethod,
  type PaymentState,
} from '@/types/commerce';
import type { CurrencyCode, Money } from '@/types/domain';

import type { PaymentAttempt, PaymentIntentState } from './payment-intent';

/**
 * THE UNPAID ORDER DRAFT.
 *
 * The last step Commerce-4 goes to. A draft is a real `orders` row in
 * `fulfilment_state = 'draft'`, `payment_state = 'unpaid'`, with server-priced
 * items — and it is NOT any of the following:
 *
 *   NOT A PAYMENT      — nothing has been charged and no provider was called.
 *   NOT A RESERVATION  — no stock is held; the shelf can still move underneath.
 *   NOT AN ORDER       — the merchant has not been told and cannot see it.
 *
 * Every string the draft screen shows is written against that list. "Order
 * placed" would be a lie in three separate ways.
 *
 * ALL OF IT IS DERIVED SERVER-SIDE. The client sends a revision, an address id
 * and an idempotency key; it sends no prices, no totals and no commission
 * rate, because a client that can name a price can name zero.
 */

export type OrderDraftRequest = {
  /** The revision the customer's validation was taken against. */
  readonly cartRevision: number;
  readonly addressId: string;
  /**
   * Stable across retries of the SAME attempt, new for a new attempt.
   *
   * A double tap, a dropped response and an app resumed from the background
   * are all the same request; without this they are three orders.
   */
  readonly idempotencyKey: string;
  readonly customerNote: string | null;
};

export type OrderDraft = {
  readonly id: string;
  /** `AKL-XXXX-XXXX`, generated by the database. Readable down a phone line. */
  readonly reference: string;
  readonly currency: CurrencyCode;
  readonly itemsSubtotal: Money;
  readonly deliveryFee: Money;
  readonly total: Money;
  readonly createdAt: string;
};

/**
 * Every way the server can refuse, named.
 *
 * These mirror the exceptions `create_order_draft` raises. They are a closed
 * set so a screen can say what went wrong in the customer's own language
 * rather than surfacing a Postgres message, and so a new server-side refusal
 * that nobody mapped shows up as `unknown` instead of as a blank screen.
 */
export const ORDER_DRAFT_FAILURES = [
  'not_authenticated',
  'cart_empty',
  'stale_cart_revision',
  'merchant_not_enabled',
  'merchant_not_accepting',
  'address_not_found',
  'address_incomplete',
  'outside_delivery_area',
  'product_delisted',
  'product_out_of_stock',
  'price_changed',
  'below_minimum',
  /** The refusal did not match anything above. Never silently permissive. */
  'unknown',
] as const;
export type OrderDraftFailure = (typeof ORDER_DRAFT_FAILURES)[number];

export class OrderDraftRefused extends Error {
  constructor(readonly failure: OrderDraftFailure) {
    super(`order draft refused: ${failure}`);
    this.name = 'OrderDraftRefused';
  }
}

/**
 * The order as the payment screen needs it.
 *
 * Small on purpose. The full `Order` type carries items, adjustments,
 * substitutions and events; a screen asking "has this been paid for" needs
 * none of them, and fetching them would make the status poll expensive.
 */
export type OrderSummary = {
  readonly id: string;
  readonly reference: string;
  readonly currency: CurrencyCode;
  readonly itemsSubtotal: Money;
  readonly deliveryFee: Money;
  readonly total: Money;
  readonly payment: PaymentState;
  readonly fulfilment: OrderFulfilmentState;
  readonly paymentMethod: PaymentMethod | null;
  /** After this, `begin_payment` refuses. Read, never recomputed. */
  readonly draftExpiresAt: string | null;
  readonly paidAt: string | null;
  readonly createdAt: string;
};

/** What the client asks for. Notice there is no amount: there cannot be one. */
export type BeginPaymentRequest = {
  readonly orderId: string;
  readonly method: 'card' | 'wallet';
  /** Stable across retries of the SAME attempt; new for a new attempt. */
  readonly idempotencyKey: string;
};

export type BeginPaymentResult = {
  readonly intentId: string;
  readonly provider: string;
  readonly amountMinor: number;
  readonly currency: string;
  /** Where to send the customer. Everything that matters happens there. */
  readonly checkoutUrl: string;
};

/** Every way beginning a payment can be refused, named. */
export const PAYMENT_REFUSALS = [
  'not_authenticated',
  'order_not_found',
  'already_paid',
  'payment_in_flight',
  'attempt_in_flight',
  'order_not_payable',
  'draft_expired',
  'merchant_not_enabled',
  'merchant_not_accepting',
  'product_delisted',
  'product_out_of_stock',
  'price_changed',
  'amount_not_payable',
  'method_not_supported',
  'idempotency_key_reused',
  /** The provider could not be reached, or is not configured. */
  'payment_unavailable',
  'unknown',
] as const;
export type PaymentRefusal = (typeof PAYMENT_REFUSALS)[number];

export class PaymentRefused extends Error {
  constructor(readonly refusal: PaymentRefusal) {
    super(`payment refused: ${refusal}`);
    this.name = 'PaymentRefused';
  }
}

export function paymentRefusalFrom(value: unknown): PaymentRefusal {
  const text = typeof value === 'string' ? value : JSON.stringify(value ?? '');
  for (const refusal of PAYMENT_REFUSALS) {
    if (refusal !== 'unknown' && text.includes(refusal)) return refusal;
  }
  return 'unknown';
}

/** One thing the shop could not supply, and what happened instead. */
export type OrderSubstitutionView = {
  readonly id: string;
  /** Which line it belongs to. Matching on the NAME would pair the wrong one
   *  the first time an order contains two lines of the same product. */
  readonly orderItemId: string;
  readonly originalProductName: string;
  readonly originalUnitPrice: Money;
  readonly replacementProductName: string | null;
  readonly replacementUnitPrice: Money | null;
  readonly quantity: number;
  readonly decision:
    | 'pending_customer'
    | 'approved'
    | 'rejected'
    | 'auto_approved'
    | 'removed';
  readonly expiresAt: string | null;
};

/**
 * What happened to an order, for the customer.
 *
 * `events` are the REAL rows the database wrote. The tracking screen renders
 * them rather than animating a guess: a customer told their order is being
 * picked while it sits in a queue remembers that.
 */
export type OrderTracking = {
  readonly order: OrderSummary;
  readonly items: readonly {
    readonly id: string;
    readonly name: string;
    readonly nameAr: string | null;
    readonly quantity: number;
    readonly lineTotal: Money;
  }[];
  readonly substitutions: readonly OrderSubstitutionView[];
  readonly events: readonly {
    readonly id: string;
    readonly kind: string;
    readonly to: string | null;
    readonly note: string | null;
    readonly at: string;
  }[];
  /** Five facts, kept apart. A calculated refund is not a paid one. */
  readonly captured: Money;
  readonly fulfilledGoods: Money;
  readonly refunded: Money;
  readonly refundRequired: Money;
  /**
   * The refund as an EVENT rather than an arithmetic result.
   *
   * `refundRequired` above says what the ledger owes. This says whether
   * anybody has tried to pay it, and how that went — which is the difference
   * between a screen that says "you are owed 45.00" forever and one that says
   * "we are sending it back". Null until the first attempt exists.
   */
  readonly refund: OrderRefundStatus | null;
  readonly riderName: string | null;
};

export interface OrderDraftRepository {
  create(request: OrderDraftRequest): Promise<OrderDraft>;
  get(orderId: string): Promise<OrderSummary | null>;
  /** Every order this account has, newest first. Paid ones and the rest. */
  list(): Promise<readonly OrderSummary[]>;
  /** Every attempt against this order, newest first. History, not a status. */
  attempts(orderId: string): Promise<readonly PaymentAttempt[]>;
  /** One attempt by id, subject to RLS. An id from a URL proves nothing. */
  attempt(intentId: string): Promise<PaymentAttempt | null>;
  beginPayment(request: BeginPaymentRequest): Promise<BeginPaymentResult>;
  cancelPayment(intentId: string): Promise<void>;
  /**
   * The simulator, for demo-merchant orders only.
   *
   * On the interface rather than tucked behind a cast because the alternative
   * is a screen reaching past the repository, and a payment screen that knows
   * which implementation it has is a payment screen that can be lied to.
   */
  simulatePayment(intentId: string, outcome: 'succeeded' | 'failed' | 'pending'): Promise<void>;
  /** True only when the basket cleared was the one actually paid for. */
  clearPaidCart(orderId: string): Promise<boolean>;
  /**
   * What happened to this order, as the customer may see it.
   *
   * The SAME reads the merchant makes, answered by the same RLS from the other
   * side: `orders: owner reads` rather than the membership policy.
   */
  tracking(orderId: string): Promise<OrderTracking | null>;
  /** Take the replacement, or have the line removed and refunded. */
  decideSubstitution(substitutionId: string, accept: boolean): Promise<void>;
}

/**
 * Reads the refusal out of whatever the driver hands back.
 *
 * `raise exception 'below_minimum'` arrives as a message that CONTAINS the
 * token rather than equals it, so this looks for a known token instead of
 * matching the whole string — and falls back to `unknown` rather than
 * guessing, because an unrecognised refusal is still a refusal.
 */
export function refusalFrom(message: string | null | undefined): OrderDraftFailure {
  if (!message) return 'unknown';
  for (const failure of ORDER_DRAFT_FAILURES) {
    if (failure !== 'unknown' && message.includes(failure)) return failure;
  }
  return 'unknown';
}

/**
 * A guest has no draft to make.
 *
 * Not an empty implementation for symmetry: a draft is owned by an account,
 * and `create_order_draft` reads `auth.uid()`. Everything upstream already
 * blocks on `not_authenticated`; this is the backstop for the case where
 * something upstream did not.
 */
export class LocalOrderDraftRepository implements OrderDraftRepository {
  async create(): Promise<OrderDraft> {
    throw new OrderDraftRefused('not_authenticated');
  }

  // A guest has no orders, so reading is EMPTY rather than an error: a screen
  // that asks "do I have an order" and gets a thrown exception has to special-
  // case guests everywhere. Anything that would MOVE money refuses instead.
  async get(): Promise<OrderSummary | null> {
    return null;
  }

  async list(): Promise<readonly OrderSummary[]> {
    return [];
  }

  async attempts(): Promise<readonly PaymentAttempt[]> {
    return [];
  }

  async attempt(): Promise<PaymentAttempt | null> {
    return null;
  }

  async beginPayment(): Promise<BeginPaymentResult> {
    throw new PaymentRefused('not_authenticated');
  }

  async cancelPayment(): Promise<void> {
    throw new PaymentRefused('not_authenticated');
  }

  async simulatePayment(): Promise<void> {
    throw new PaymentRefused('not_authenticated');
  }

  async clearPaidCart(): Promise<boolean> {
    return false;
  }

  async tracking(): Promise<OrderTracking | null> {
    return null;
  }

  async decideSubstitution(): Promise<void> {
    throw new PaymentRefused('not_authenticated');
  }
}

export class SupabaseOrderDraftRepository implements OrderDraftRepository {
  constructor(
    private readonly client: SupabaseClient<Database>,
    private readonly userId: string,
  ) {}

  async create(request: OrderDraftRequest): Promise<OrderDraft> {
    const { data: orderId, error } = await this.client.rpc('create_order_draft', {
      p_cart_revision: request.cartRevision,
      p_address_id: request.addressId,
      p_idempotency_key: request.idempotencyKey,
      p_customer_note: request.customerNote,
    });

    if (error) throw new OrderDraftRefused(refusalFrom(error.message));
    if (!orderId) throw new OrderDraftRefused('unknown');

    // Read back rather than trust what we sent: the totals on the row are the
    // server's, computed from the catalogue, and they are what the customer
    // will be asked to pay.
    const { data, error: readError } = await this.client
      .from('orders')
      .select('id, reference, currency, items_subtotal_minor, delivery_fee_minor, created_at')
      .eq('id', orderId)
      .eq('user_id', this.userId)
      .single();

    if (readError) throw toAppError(readError, 'database');

    const currency = data.currency as CurrencyCode;
    return {
      id: data.id,
      reference: data.reference,
      currency,
      itemsSubtotal: { amountMinor: data.items_subtotal_minor, currency },
      deliveryFee: { amountMinor: data.delivery_fee_minor, currency },
      total: {
        amountMinor: data.items_subtotal_minor + data.delivery_fee_minor,
        currency,
      },
      createdAt: data.created_at,
    };
  }

  async get(orderId: string): Promise<OrderSummary | null> {
    const { data, error } = await this.client
      .from('orders')
      // One literal, not a concatenation: supabase-js infers the row type from
      // the select string, and a `+` turns that into `string` and the result
      // into an error union.
      .select('id, reference, currency, items_subtotal_minor, delivery_fee_minor, payment_state, fulfilment_state, payment_method, draft_expires_at, paid_at, created_at')
      .eq('id', orderId)
      .eq('user_id', this.userId)
      .maybeSingle();

    if (error) throw toAppError(error, 'database');
    if (!data) return null;

    const currency = data.currency as CurrencyCode;
    return {
      id: data.id,
      reference: data.reference,
      currency,
      itemsSubtotal: { amountMinor: data.items_subtotal_minor, currency },
      deliveryFee: { amountMinor: data.delivery_fee_minor, currency },
      total: {
        amountMinor: data.items_subtotal_minor + data.delivery_fee_minor,
        currency,
      },
      payment: data.payment_state,
      fulfilment: data.fulfilment_state,
      paymentMethod: data.payment_method,
      draftExpiresAt: data.draft_expires_at,
      paidAt: data.paid_at,
      createdAt: data.created_at,
    };
  }

  async list(): Promise<readonly OrderSummary[]> {
    const { data, error } = await this.client
      .from('orders')
      .select('id, reference, currency, items_subtotal_minor, delivery_fee_minor, payment_state, fulfilment_state, payment_method, draft_expires_at, paid_at, created_at')
      .eq('user_id', this.userId)
      .order('created_at', { ascending: false })
      .limit(50);

    if (error) throw toAppError(error, 'database');

    return (data ?? []).map((row) => {
      const currency = row.currency as CurrencyCode;
      return {
        id: row.id,
        reference: row.reference,
        currency,
        itemsSubtotal: { amountMinor: row.items_subtotal_minor, currency },
        deliveryFee: { amountMinor: row.delivery_fee_minor, currency },
        total: {
          amountMinor: row.items_subtotal_minor + row.delivery_fee_minor,
          currency,
        },
        payment: row.payment_state,
        fulfilment: row.fulfilment_state,
        paymentMethod: row.payment_method,
        draftExpiresAt: row.draft_expires_at,
        paidAt: row.paid_at,
        createdAt: row.created_at,
      };
    });
  }

  async attempts(orderId: string): Promise<readonly PaymentAttempt[]> {
    // RLS restricts this to the caller's own attempts; the filter states the
    // intent without making anybody read a policy to see it.
    const { data, error } = await this.client
      .from('payment_intents')
      .select('*')
      .eq('order_id', orderId)
      .eq('user_id', this.userId)
      .order('created_at', { ascending: false });

    if (error) throw toAppError(error, 'database');
    return (data ?? []).map(toAttempt);
  }

  async attempt(intentId: string): Promise<PaymentAttempt | null> {
    const { data, error } = await this.client
      .from('payment_intents')
      .select('*')
      .eq('id', intentId)
      .eq('user_id', this.userId)
      .maybeSingle();

    if (error) throw toAppError(error, 'database');
    return data ? toAttempt(data) : null;
  }

  /**
   * Begins a payment THROUGH THE EDGE FUNCTION, never by calling the RPC here.
   *
   * The function runs `begin_payment` with the caller's own JWT — so the
   * database still answers ownership and derives the amount — and then uses the
   * provider secret key, which is the part that cannot exist in this bundle.
   */
  async beginPayment(request: BeginPaymentRequest): Promise<BeginPaymentResult> {
    const { data, error } = await this.client.functions.invoke('payments-begin', {
      body: {
        orderId: request.orderId,
        method: request.method,
        idempotencyKey: request.idempotencyKey,
      },
    });

    if (error) {
      // `functions.invoke` puts the body on the error for a non-2xx, and the
      // refusal code is in it. A generic "something went wrong" here would
      // throw away the one thing the screen can act on.
      const context = (error as { context?: { body?: unknown } }).context?.body;
      throw new PaymentRefused(paymentRefusalFrom(context ?? error.message));
    }

    const result = data as Record<string, unknown> | null;
    if (!result || typeof result.checkoutUrl !== 'string') {
      throw new PaymentRefused(paymentRefusalFrom(result));
    }

    return {
      intentId: String(result.intentId),
      provider: String(result.provider),
      amountMinor: Number(result.amountMinor),
      currency: String(result.currency),
      checkoutUrl: result.checkoutUrl,
    };
  }

  async cancelPayment(intentId: string): Promise<void> {
    const { error } = await this.client.rpc('cancel_payment_intent', {
      p_intent_id: intentId,
    });
    if (error) throw new PaymentRefused(paymentRefusalFrom(error.message));
  }

  async simulatePayment(
    intentId: string,
    outcome: 'succeeded' | 'failed' | 'pending',
  ): Promise<void> {
    const { error } = await this.client.functions.invoke('payments-simulate', {
      body: { intentId, outcome },
    });
    if (error) throw new PaymentRefused(paymentRefusalFrom(error.message));
  }

  async clearPaidCart(orderId: string): Promise<boolean> {
    const { data, error } = await this.client.rpc('clear_paid_cart', {
      p_order_id: orderId,
    });
    if (error) throw toAppError(error, 'database');
    return data === true;
  }

  async tracking(orderId: string): Promise<OrderTracking | null> {
    const summary = await this.get(orderId);
    if (!summary) return null;

    const [items, subs, events, position, refund, rider] = await Promise.all([
      this.client.from('order_items').select('*').eq('order_id', orderId),
      this.client
        .from('order_substitutions')
        .select('*')
        .eq('order_id', orderId)
        .order('created_at', { ascending: true }),
      this.client
        .from('order_events')
        .select('*')
        .eq('order_id', orderId)
        .order('at', { ascending: true }),
      this.client.rpc('order_refund_position', { p_order_id: orderId }),
      this.client.rpc('order_refund_status', { p_order_id: orderId }),
      this.client.from('orders').select('rider_name').eq('id', orderId).maybeSingle(),
    ]);

    const currency = summary.currency;
    const financial = (position.data ?? [])[0];
    const money = (amountMinor: number): Money => ({ amountMinor, currency });

    return {
      order: summary,
      items: (items.data ?? []).map((item) => ({
        id: item.id,
        name: item.product_name,
        nameAr: item.product_name_ar,
        quantity: item.quantity,
        lineTotal: money(item.line_total_minor),
      })),
      substitutions: (subs.data ?? []).map((sub) => ({
        id: sub.id,
        orderItemId: sub.order_item_id,
        originalProductName: sub.original_product_name,
        originalUnitPrice: money(sub.original_unit_price_minor),
        replacementProductName: sub.replacement_product_name,
        replacementUnitPrice:
          sub.replacement_unit_price_minor === null
            ? null
            : money(sub.replacement_unit_price_minor),
        quantity: sub.quantity,
        decision: sub.decision,
        expiresAt: sub.expires_at,
      })),
      events: (events.data ?? []).map((event) => ({
        id: event.id,
        kind: event.kind,
        to: event.to_value,
        note: event.note,
        at: event.at,
      })),
      captured: money(financial?.captured_minor ?? 0),
      fulfilledGoods: money(financial?.fulfilled_goods_minor ?? 0),
      refunded: money(financial?.refunded_minor ?? 0),
      refundRequired: money(financial?.refund_required_minor ?? 0),
      refund: toRefundStatus((refund.data ?? [])[0], currency),
      riderName: rider.data?.rider_name ?? null,
    };
  }

  async decideSubstitution(substitutionId: string, accept: boolean): Promise<void> {
    const { error } = await this.client.rpc('decide_substitution', {
      p_substitution_id: substitutionId,
      p_accept: accept,
    });
    if (error) throw toAppError(error, 'database');
  }
}

function toAttempt(row: PaymentIntentRow): PaymentAttempt {
  return {
    id: row.id,
    orderId: row.order_id,
    provider: row.provider,
    method: row.method,
    amountMinor: row.amount_minor,
    currency: row.currency as CurrencyCode,
    state: row.state as PaymentIntentState,
    checkoutUrl: row.checkout_url,
    failureCode: row.failure_code,
    failureMessage: row.failure_message,
    createdAt: row.created_at,
    settledAt: row.settled_at,
  };
}

/**
 * The refund row, as the app reads it.
 *
 * `attempt_state` comes back as plain text rather than the enum, because the
 * left join that produces it may have no row at all — so the narrowing happens
 * here, once, against the list the types declare, rather than in every screen
 * that wants to know whether a refund is moving.
 */
function toRefundStatus(
  row:
    | {
        currency: string;
        captured_minor: number;
        refunded_minor: number;
        refund_required_minor: number;
        attempt_state: string | null;
        attempt_amount_minor: number | null;
        needs_review: boolean;
        last_error_code: string | null;
        requested_at: string | null;
        settled_at: string | null;
      }
    | undefined,
  fallbackCurrency: CurrencyCode,
): OrderRefundStatus | null {
  if (!row) return null;

  const state = REFUND_ATTEMPT_STATES.find((value) => value === row.attempt_state) ?? null;

  return {
    currency: (row.currency as CurrencyCode) ?? fallbackCurrency,
    capturedMinor: row.captured_minor,
    refundedMinor: row.refunded_minor,
    refundRequiredMinor: row.refund_required_minor,
    attemptState: state,
    attemptAmountMinor: row.attempt_amount_minor,
    needsReview: row.needs_review === true,
    lastErrorCode: row.last_error_code,
    requestedAt: row.requested_at,
    settledAt: row.settled_at,
  };
}
