import type { Recipe } from '@/types/domain';

/**
 * Curated recipe set.
 *
 * Purpose is threefold:
 *   1. the app is fully usable before any backend exists (Phase 1–2),
 *   2. Discover collections have real content on a cold database, and
 *   3. `scripts/generate-seed.ts` compiles them into `supabase/seed.sql`.
 *
 * Quantities are written for `baseServings`; the app scales them at render
 * time. Images are Unsplash URLs sized for a phone hero — swap for a CDN
 * bucket before launch (see PROJECT_STATUS.md § Remaining work).
 *
 * NOTE: `import type` only, so the seed generator can load this with Node's
 * type-stripping loader.
 */

const IMG = (id: string) => `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=900&q=70`;

export const RECIPE_FIXTURES: Recipe[] = [
  {
    id: 'rcp-koshari',
    slug: 'koshari',
    title: 'Koshari',
    description:
      'Egypt in a bowl: rice, lentils and pasta under spiced tomato sauce and a mountain of crisp onions.',
    imageUrl: IMG('1512058564366-18510be2db19'),
    source: 'curated',
    cuisine: 'egyptian',
    mealTypes: ['lunch', 'dinner'],
    difficulty: 'medium',
    prepMinutes: 15,
    cookMinutes: 40,
    baseServings: 4,
    nutrition: { calories: 610, proteinGrams: 19, carbsGrams: 108, fatGrams: 12, fiberGrams: 11 },
    allergens: ['gluten'],
    dietTags: ['vegetarian', 'vegan', 'halal'],
    requiredAppliances: ['stove'],
    tags: ['egyptian', 'budget', 'under-100', 'comfort', 'batch-cook'],
    createdAt: '2026-01-01T00:00:00.000Z',
    ingredients: [
      { id: 'koshari-1', ingredientId: null, name: 'rice', quantity: 300, unit: 'g', preparation: 'rinsed', isOptional: false, sortOrder: 1 },
      { id: 'koshari-2', ingredientId: null, name: 'red lentils', quantity: 200, unit: 'g', preparation: null, isOptional: false, sortOrder: 2 },
      { id: 'koshari-3', ingredientId: null, name: 'pasta', quantity: 150, unit: 'g', preparation: 'small elbows', isOptional: false, sortOrder: 3 },
      { id: 'koshari-4', ingredientId: null, name: 'onions', quantity: 3, unit: 'piece', preparation: 'thinly sliced', isOptional: false, sortOrder: 4 },
      { id: 'koshari-5', ingredientId: null, name: 'tomato paste', quantity: 3, unit: 'tbsp', preparation: null, isOptional: false, sortOrder: 5 },
      { id: 'koshari-6', ingredientId: null, name: 'garlic', quantity: 4, unit: 'clove', preparation: 'crushed', isOptional: false, sortOrder: 6 },
      { id: 'koshari-7', ingredientId: null, name: 'vinegar', quantity: 30, unit: 'ml', preparation: null, isOptional: false, sortOrder: 7 },
      { id: 'koshari-8', ingredientId: null, name: 'cumin', quantity: 2, unit: 'tsp', preparation: null, isOptional: false, sortOrder: 8 },
      { id: 'koshari-9', ingredientId: null, name: 'vegetable oil', quantity: 120, unit: 'ml', preparation: 'for frying', isOptional: false, sortOrder: 9 },
      { id: 'koshari-10', ingredientId: null, name: 'chickpeas', quantity: 150, unit: 'g', preparation: 'cooked', isOptional: true, sortOrder: 10 },
      { id: 'koshari-11', ingredientId: null, name: 'chili flakes', quantity: 1, unit: 'tsp', preparation: null, isOptional: true, sortOrder: 11 },
    ],
    steps: [
      { id: 'koshari-s1', stepNumber: 1, instruction: 'Fry the sliced onions in oil over medium heat until deep golden and crisp, about 15 minutes. Lift onto paper and keep the oil.', durationMinutes: 15, ingredientRefs: ['onions', 'vegetable oil'], safetyNote: null },
      { id: 'koshari-s2', stepNumber: 2, instruction: 'Simmer the lentils in plenty of water for 15 minutes until just tender, then drain.', durationMinutes: 15, ingredientRefs: ['red lentils'], safetyNote: null },
      { id: 'koshari-s3', stepNumber: 3, instruction: 'Cook the rice with a spoon of the onion oil and a good pinch of salt until fluffy. Boil the pasta separately until al dente.', durationMinutes: 18, ingredientRefs: ['rice', 'pasta'], safetyNote: null },
      { id: 'koshari-s4', stepNumber: 4, instruction: 'For the sauce, fry the garlic for 30 seconds, add tomato paste, cumin and 250ml water. Simmer 10 minutes, then stir in the vinegar.', durationMinutes: 12, ingredientRefs: ['garlic', 'tomato paste', 'cumin', 'vinegar'], safetyNote: null },
      { id: 'koshari-s5', stepNumber: 5, instruction: 'Layer rice, lentils and pasta in bowls. Ladle over the sauce and finish with the crisp onions and chickpeas.', durationMinutes: 5, ingredientRefs: ['chickpeas'], safetyNote: null },
    ],
  },
  {
    id: 'rcp-shakshuka',
    slug: 'shakshuka',
    title: 'Tomato & Feta Shakshuka',
    description: 'Eggs poached in a garlicky tomato sauce with crumbled white cheese. Ready before the bread is toasted.',
    imageUrl: IMG('1590412200988-a436970781fa'),
    source: 'curated',
    cuisine: 'egyptian',
    mealTypes: ['breakfast', 'dinner'],
    difficulty: 'easy',
    prepMinutes: 5,
    cookMinutes: 15,
    baseServings: 2,
    nutrition: { calories: 380, proteinGrams: 22, carbsGrams: 18, fatGrams: 25, fiberGrams: 4 },
    allergens: ['eggs', 'dairy'],
    dietTags: ['vegetarian', 'halal'],
    requiredAppliances: ['stove'],
    tags: ['quick', 'breakfast', 'high-protein', 'under-100', 'beginner'],
    createdAt: '2026-01-01T00:00:00.000Z',
    ingredients: [
      { id: 'shak-1', ingredientId: null, name: 'eggs', quantity: 4, unit: 'piece', preparation: null, isOptional: false, sortOrder: 1 },
      { id: 'shak-2', ingredientId: null, name: 'tomatoes', quantity: 4, unit: 'piece', preparation: 'chopped', isOptional: false, sortOrder: 2 },
      { id: 'shak-3', ingredientId: null, name: 'onions', quantity: 1, unit: 'piece', preparation: 'diced', isOptional: false, sortOrder: 3 },
      { id: 'shak-4', ingredientId: null, name: 'garlic', quantity: 3, unit: 'clove', preparation: 'sliced', isOptional: false, sortOrder: 4 },
      { id: 'shak-5', ingredientId: null, name: 'white cheese', quantity: 80, unit: 'g', preparation: 'crumbled', isOptional: false, sortOrder: 5 },
      { id: 'shak-6', ingredientId: null, name: 'cumin', quantity: 1, unit: 'tsp', preparation: null, isOptional: false, sortOrder: 6 },
      { id: 'shak-7', ingredientId: null, name: 'olive oil', quantity: 30, unit: 'ml', preparation: null, isOptional: false, sortOrder: 7 },
      { id: 'shak-8', ingredientId: null, name: 'baladi bread', quantity: 2, unit: 'piece', preparation: 'to serve', isOptional: true, sortOrder: 8 },
      { id: 'shak-9', ingredientId: null, name: 'coriander', quantity: 1, unit: 'bunch', preparation: 'chopped', isOptional: true, sortOrder: 9 },
    ],
    steps: [
      { id: 'shak-s1', stepNumber: 1, instruction: 'Soften the onion in olive oil for 4 minutes, then add the garlic and cumin and cook another minute.', durationMinutes: 5, ingredientRefs: ['onions', 'garlic', 'cumin', 'olive oil'], safetyNote: null },
      { id: 'shak-s2', stepNumber: 2, instruction: 'Add the tomatoes and a pinch of salt. Simmer 8 minutes until the sauce thickens and darkens.', durationMinutes: 8, ingredientRefs: ['tomatoes'], safetyNote: null },
      { id: 'shak-s3', stepNumber: 3, instruction: 'Make four wells and crack an egg into each. Cover and cook 4–5 minutes.', durationMinutes: 5, ingredientRefs: ['eggs'], safetyNote: 'Cook eggs until the whites are completely set. Runny yolks are only safe with pasteurised eggs.' },
      { id: 'shak-s4', stepNumber: 4, instruction: 'Scatter over the white cheese and coriander and take it straight to the table with bread.', durationMinutes: 1, ingredientRefs: ['white cheese', 'coriander', 'baladi bread'], safetyNote: null },
    ],
  },
  {
    id: 'rcp-creamy-chicken-pasta',
    slug: 'creamy-chicken-pasta',
    title: 'Creamy Chicken Pasta',
    description: 'Weeknight pasta in one pan — seared chicken, garlic cream and enough parmesan-style cheese to matter.',
    imageUrl: IMG('1621996346565-e3dbc646d9a9'),
    source: 'curated',
    cuisine: 'italian',
    mealTypes: ['dinner'],
    difficulty: 'easy',
    prepMinutes: 10,
    cookMinutes: 20,
    baseServings: 3,
    nutrition: { calories: 650, proteinGrams: 48, carbsGrams: 62, fatGrams: 22, fiberGrams: 4 },
    allergens: ['gluten', 'dairy'],
    dietTags: ['halal'],
    requiredAppliances: ['stove'],
    tags: ['quick', 'high-protein', 'comfort', 'italian', 'beginner'],
    createdAt: '2026-01-01T00:00:00.000Z',
    ingredients: [
      { id: 'ccp-1', ingredientId: null, name: 'chicken breast', quantity: 450, unit: 'g', preparation: 'cut into strips', isOptional: false, sortOrder: 1 },
      { id: 'ccp-2', ingredientId: null, name: 'pasta', quantity: 300, unit: 'g', preparation: null, isOptional: false, sortOrder: 2 },
      { id: 'ccp-3', ingredientId: null, name: 'cooking cream', quantity: 200, unit: 'ml', preparation: null, isOptional: false, sortOrder: 3 },
      { id: 'ccp-4', ingredientId: null, name: 'garlic', quantity: 4, unit: 'clove', preparation: 'minced', isOptional: false, sortOrder: 4 },
      { id: 'ccp-5', ingredientId: null, name: 'roumy cheese', quantity: 60, unit: 'g', preparation: 'grated', isOptional: false, sortOrder: 5 },
      { id: 'ccp-6', ingredientId: null, name: 'butter', quantity: 20, unit: 'g', preparation: null, isOptional: false, sortOrder: 6 },
      { id: 'ccp-7', ingredientId: null, name: 'black pepper', quantity: 1, unit: 'tsp', preparation: null, isOptional: false, sortOrder: 7 },
      { id: 'ccp-8', ingredientId: null, name: 'parsley', quantity: 1, unit: 'bunch', preparation: 'chopped', isOptional: true, sortOrder: 8 },
    ],
    steps: [
      { id: 'ccp-s1', stepNumber: 1, instruction: 'Boil the pasta in well-salted water. Reserve a cup of the water before draining.', durationMinutes: 10, ingredientRefs: ['pasta'], safetyNote: null },
      { id: 'ccp-s2', stepNumber: 2, instruction: 'Season the chicken and sear in butter over high heat until golden on both sides.', durationMinutes: 7, ingredientRefs: ['chicken breast', 'butter', 'black pepper'], safetyNote: 'Cook chicken until it reaches 74°C / 165°F and no pink remains. Wash hands and the board after handling raw poultry.' },
      { id: 'ccp-s3', stepNumber: 3, instruction: 'Lower the heat, add the garlic for 30 seconds, then pour in the cream and let it bubble for 2 minutes.', durationMinutes: 3, ingredientRefs: ['garlic', 'cooking cream'], safetyNote: null },
      { id: 'ccp-s4', stepNumber: 4, instruction: 'Toss in the pasta with a splash of its water and the grated cheese until glossy. Finish with parsley.', durationMinutes: 3, ingredientRefs: ['roumy cheese', 'parsley'], safetyNote: null },
    ],
  },
  {
    id: 'rcp-foul-eggs',
    slug: 'foul-with-eggs',
    title: 'Foul with Eggs & Olive Oil',
    description: 'The breakfast that runs the country. Warm fava beans, cumin, lemon and a soft-boiled egg on top.',
    imageUrl: IMG('1528735602780-2552fd46c7af'),
    source: 'curated',
    cuisine: 'egyptian',
    mealTypes: ['breakfast'],
    difficulty: 'easy',
    prepMinutes: 5,
    cookMinutes: 10,
    baseServings: 2,
    nutrition: { calories: 420, proteinGrams: 24, carbsGrams: 44, fatGrams: 17, fiberGrams: 14 },
    allergens: ['eggs', 'gluten'],
    dietTags: ['vegetarian', 'halal'],
    requiredAppliances: ['stove'],
    tags: ['egyptian', 'breakfast', 'budget', 'under-100', 'high-protein', 'beginner'],
    createdAt: '2026-01-01T00:00:00.000Z',
    ingredients: [
      { id: 'foul-1', ingredientId: null, name: 'fava beans', quantity: 400, unit: 'g', preparation: 'cooked', isOptional: false, sortOrder: 1 },
      { id: 'foul-2', ingredientId: null, name: 'eggs', quantity: 2, unit: 'piece', preparation: null, isOptional: false, sortOrder: 2 },
      { id: 'foul-3', ingredientId: null, name: 'olive oil', quantity: 30, unit: 'ml', preparation: null, isOptional: false, sortOrder: 3 },
      { id: 'foul-4', ingredientId: null, name: 'lemon', quantity: 1, unit: 'piece', preparation: 'juiced', isOptional: false, sortOrder: 4 },
      { id: 'foul-5', ingredientId: null, name: 'cumin', quantity: 1, unit: 'tsp', preparation: null, isOptional: false, sortOrder: 5 },
      { id: 'foul-6', ingredientId: null, name: 'baladi bread', quantity: 2, unit: 'piece', preparation: null, isOptional: false, sortOrder: 6 },
      { id: 'foul-7', ingredientId: null, name: 'tomatoes', quantity: 1, unit: 'piece', preparation: 'diced', isOptional: true, sortOrder: 7 },
      { id: 'foul-8', ingredientId: null, name: 'chili flakes', quantity: 1, unit: 'tsp', preparation: null, isOptional: true, sortOrder: 8 },
    ],
    steps: [
      { id: 'foul-s1', stepNumber: 1, instruction: 'Warm the fava beans in a pan with a splash of their liquid, mashing about half of them.', durationMinutes: 6, ingredientRefs: ['fava beans'], safetyNote: null },
      { id: 'foul-s2', stepNumber: 2, instruction: 'Boil the eggs for 7 minutes for a just-set yolk, then peel under cold water.', durationMinutes: 7, ingredientRefs: ['eggs'], safetyNote: 'Boil eggs for at least 7 minutes so the white is fully set.' },
      { id: 'foul-s3', stepNumber: 3, instruction: 'Season the foul with cumin, salt and lemon juice, then pour olive oil generously over the top.', durationMinutes: 2, ingredientRefs: ['cumin', 'lemon', 'olive oil'], safetyNote: null },
      { id: 'foul-s4', stepNumber: 4, instruction: 'Halve the eggs onto the beans, scatter tomato and chilli, and scoop it all up with warm bread.', durationMinutes: 1, ingredientRefs: ['tomatoes', 'chili flakes', 'baladi bread'], safetyNote: null },
    ],
  },
  {
    id: 'rcp-molokhia-chicken',
    slug: 'molokhia-with-chicken',
    title: 'Molokhia with Chicken',
    description: 'Silky green molokhia over rice, with poached chicken and a hit of garlic-coriander taqleya.',
    imageUrl: IMG('1547592180-85f173990554'),
    source: 'curated',
    cuisine: 'egyptian',
    mealTypes: ['lunch', 'dinner'],
    difficulty: 'medium',
    prepMinutes: 15,
    cookMinutes: 45,
    baseServings: 4,
    nutrition: { calories: 540, proteinGrams: 42, carbsGrams: 52, fatGrams: 16, fiberGrams: 6 },
    allergens: [],
    dietTags: ['halal'],
    requiredAppliances: ['stove'],
    tags: ['egyptian', 'comfort', 'high-protein', 'sunday-lunch'],
    createdAt: '2026-01-01T00:00:00.000Z',
    ingredients: [
      { id: 'mol-1', ingredientId: null, name: 'chicken thighs', quantity: 700, unit: 'g', preparation: null, isOptional: false, sortOrder: 1 },
      { id: 'mol-2', ingredientId: null, name: 'molokhia', quantity: 400, unit: 'g', preparation: 'frozen, chopped', isOptional: false, sortOrder: 2 },
      { id: 'mol-3', ingredientId: null, name: 'garlic', quantity: 8, unit: 'clove', preparation: 'crushed', isOptional: false, sortOrder: 3 },
      { id: 'mol-4', ingredientId: null, name: 'ground coriander', quantity: 2, unit: 'tsp', preparation: null, isOptional: false, sortOrder: 4 },
      { id: 'mol-5', ingredientId: null, name: 'rice', quantity: 300, unit: 'g', preparation: null, isOptional: false, sortOrder: 5 },
      { id: 'mol-6', ingredientId: null, name: 'onions', quantity: 1, unit: 'piece', preparation: 'halved', isOptional: false, sortOrder: 6 },
      { id: 'mol-7', ingredientId: null, name: 'bay leaf', quantity: 2, unit: 'piece', preparation: null, isOptional: false, sortOrder: 7 },
      { id: 'mol-8', ingredientId: null, name: 'butter', quantity: 30, unit: 'g', preparation: null, isOptional: false, sortOrder: 8 },
      { id: 'mol-9', ingredientId: null, name: 'lemon', quantity: 1, unit: 'piece', preparation: 'wedges to serve', isOptional: true, sortOrder: 9 },
    ],
    steps: [
      { id: 'mol-s1', stepNumber: 1, instruction: 'Simmer the chicken with the onion and bay leaves in 1.5L water for 35 minutes. Skim, then lift out the chicken and keep the broth.', durationMinutes: 35, ingredientRefs: ['chicken thighs', 'onions', 'bay leaf'], safetyNote: 'Poultry must reach 74°C / 165°F throughout. The juices should run clear.' },
      { id: 'mol-s2', stepNumber: 2, instruction: 'Cook the rice while the chicken simmers.', durationMinutes: 18, ingredientRefs: ['rice'], safetyNote: null },
      { id: 'mol-s3', stepNumber: 3, instruction: 'Bring 1L of the broth to a gentle simmer and stir in the molokhia. Keep it just below the boil for 5 minutes — hard boiling splits it.', durationMinutes: 6, ingredientRefs: ['molokhia'], safetyNote: null },
      { id: 'mol-s4', stepNumber: 4, instruction: 'For the taqleya, fry the garlic and ground coriander in butter until fragrant and golden, then tip the whole lot into the molokhia. It will hiss.', durationMinutes: 3, ingredientRefs: ['garlic', 'ground coriander', 'butter'], safetyNote: null },
      { id: 'mol-s5', stepNumber: 5, instruction: 'Serve the molokhia over rice with the chicken alongside and lemon to squeeze.', durationMinutes: 2, ingredientRefs: ['lemon'], safetyNote: null },
    ],
  },
  {
    id: 'rcp-air-fryer-chicken',
    slug: 'air-fryer-spiced-chicken',
    title: 'Air Fryer Spiced Chicken',
    description: 'Twenty minutes, one appliance, no oil splatter. Crisp outside, still juicy inside.',
    imageUrl: IMG('1598515214211-89d3c73ae83b'),
    source: 'curated',
    cuisine: 'mediterranean',
    mealTypes: ['lunch', 'dinner'],
    difficulty: 'easy',
    prepMinutes: 8,
    cookMinutes: 18,
    baseServings: 2,
    nutrition: { calories: 410, proteinGrams: 52, carbsGrams: 6, fatGrams: 19, fiberGrams: 1 },
    allergens: [],
    dietTags: ['halal', 'keto'],
    requiredAppliances: ['air_fryer'],
    tags: ['air-fryer', 'high-protein', 'quick', 'healthy', 'beginner'],
    createdAt: '2026-01-01T00:00:00.000Z',
    ingredients: [
      { id: 'afc-1', ingredientId: null, name: 'chicken thighs', quantity: 500, unit: 'g', preparation: null, isOptional: false, sortOrder: 1 },
      { id: 'afc-2', ingredientId: null, name: 'paprika', quantity: 2, unit: 'tsp', preparation: null, isOptional: false, sortOrder: 2 },
      { id: 'afc-3', ingredientId: null, name: 'cumin', quantity: 1, unit: 'tsp', preparation: null, isOptional: false, sortOrder: 3 },
      { id: 'afc-4', ingredientId: null, name: 'garlic', quantity: 3, unit: 'clove', preparation: 'crushed', isOptional: false, sortOrder: 4 },
      { id: 'afc-5', ingredientId: null, name: 'olive oil', quantity: 20, unit: 'ml', preparation: null, isOptional: false, sortOrder: 5 },
      { id: 'afc-6', ingredientId: null, name: 'lemon', quantity: 1, unit: 'piece', preparation: 'juiced', isOptional: false, sortOrder: 6 },
      { id: 'afc-7', ingredientId: null, name: 'yogurt', quantity: 100, unit: 'g', preparation: 'to serve', isOptional: true, sortOrder: 7 },
    ],
    steps: [
      { id: 'afc-s1', stepNumber: 1, instruction: 'Toss the chicken with oil, lemon juice, garlic, paprika, cumin and salt. Leave 5 minutes if you have it.', durationMinutes: 8, ingredientRefs: ['chicken thighs', 'olive oil', 'lemon', 'garlic', 'paprika', 'cumin'], safetyNote: 'Marinate in the fridge, never on the counter, and discard any marinade that touched raw chicken.' },
      { id: 'afc-s2', stepNumber: 2, instruction: 'Air fry at 200°C for 18 minutes, turning once halfway.', durationMinutes: 18, ingredientRefs: [], safetyNote: 'Check the thickest piece reaches 74°C / 165°F before serving.' },
      { id: 'afc-s3', stepNumber: 3, instruction: 'Rest for 3 minutes, then serve with cold yogurt.', durationMinutes: 3, ingredientRefs: ['yogurt'], safetyNote: null },
    ],
  },
  {
    id: 'rcp-lentil-soup',
    slug: 'egyptian-lentil-soup',
    title: 'Egyptian Lentil Soup',
    description: 'Cheap, filling and quietly excellent. Blended red lentils with cumin and a squeeze of lemon.',
    imageUrl: IMG('1547592166-23ac45744acd'),
    source: 'curated',
    cuisine: 'egyptian',
    mealTypes: ['lunch', 'dinner'],
    difficulty: 'easy',
    prepMinutes: 8,
    cookMinutes: 30,
    baseServings: 4,
    nutrition: { calories: 290, proteinGrams: 16, carbsGrams: 44, fatGrams: 6, fiberGrams: 12 },
    allergens: [],
    dietTags: ['vegetarian', 'vegan', 'halal'],
    requiredAppliances: ['stove', 'blender'],
    tags: ['egyptian', 'budget', 'under-100', 'healthy', 'beginner', 'batch-cook'],
    createdAt: '2026-01-01T00:00:00.000Z',
    ingredients: [
      { id: 'ls-1', ingredientId: null, name: 'red lentils', quantity: 250, unit: 'g', preparation: 'rinsed', isOptional: false, sortOrder: 1 },
      { id: 'ls-2', ingredientId: null, name: 'onions', quantity: 1, unit: 'piece', preparation: 'chopped', isOptional: false, sortOrder: 2 },
      { id: 'ls-3', ingredientId: null, name: 'carrots', quantity: 2, unit: 'piece', preparation: 'chopped', isOptional: false, sortOrder: 3 },
      { id: 'ls-4', ingredientId: null, name: 'potatoes', quantity: 1, unit: 'piece', preparation: 'diced', isOptional: false, sortOrder: 4 },
      { id: 'ls-5', ingredientId: null, name: 'cumin', quantity: 2, unit: 'tsp', preparation: null, isOptional: false, sortOrder: 5 },
      { id: 'ls-6', ingredientId: null, name: 'lemon', quantity: 1, unit: 'piece', preparation: 'wedges to serve', isOptional: false, sortOrder: 6 },
      { id: 'ls-7', ingredientId: null, name: 'vegetable oil', quantity: 20, unit: 'ml', preparation: null, isOptional: false, sortOrder: 7 },
    ],
    steps: [
      { id: 'ls-s1', stepNumber: 1, instruction: 'Soften the onion, carrot and potato in oil for 6 minutes.', durationMinutes: 6, ingredientRefs: ['onions', 'carrots', 'potatoes', 'vegetable oil'], safetyNote: null },
      { id: 'ls-s2', stepNumber: 2, instruction: 'Add the lentils, cumin and 1.2L water. Simmer 25 minutes until everything collapses.', durationMinutes: 25, ingredientRefs: ['red lentils', 'cumin'], safetyNote: null },
      { id: 'ls-s3', stepNumber: 3, instruction: 'Blend until completely smooth, loosening with hot water if needed. Season well.', durationMinutes: 3, ingredientRefs: [], safetyNote: 'Blend hot liquid in batches with the lid vented, or it will erupt.' },
      { id: 'ls-s4', stepNumber: 4, instruction: 'Serve with lemon wedges and, if you like, fried bread croutons.', durationMinutes: 2, ingredientRefs: ['lemon'], safetyNote: null },
    ],
  },
  {
    id: 'rcp-tuna-pasta-salad',
    slug: 'tuna-pasta-salad',
    title: 'Cold Tuna Pasta Salad',
    description: 'No-cook-but-the-pasta lunch. Tuna, lemon, cucumber and enough protein to get you to dinner.',
    imageUrl: IMG('1512621776951-a57141f2eefd'),
    source: 'curated',
    cuisine: 'mediterranean',
    mealTypes: ['lunch', 'snack'],
    difficulty: 'easy',
    prepMinutes: 10,
    cookMinutes: 10,
    baseServings: 2,
    nutrition: { calories: 480, proteinGrams: 34, carbsGrams: 58, fatGrams: 13, fiberGrams: 5 },
    allergens: ['gluten', 'fish'],
    dietTags: ['pescatarian', 'halal'],
    requiredAppliances: ['stove'],
    tags: ['quick', 'high-protein', 'healthy', 'under-100', 'beginner', 'no-oven'],
    createdAt: '2026-01-01T00:00:00.000Z',
    ingredients: [
      { id: 'tps-1', ingredientId: null, name: 'pasta', quantity: 200, unit: 'g', preparation: null, isOptional: false, sortOrder: 1 },
      { id: 'tps-2', ingredientId: null, name: 'canned tuna', quantity: 2, unit: 'can', preparation: 'drained', isOptional: false, sortOrder: 2 },
      { id: 'tps-3', ingredientId: null, name: 'cucumber', quantity: 1, unit: 'piece', preparation: 'diced', isOptional: false, sortOrder: 3 },
      { id: 'tps-4', ingredientId: null, name: 'tomatoes', quantity: 2, unit: 'piece', preparation: 'diced', isOptional: false, sortOrder: 4 },
      { id: 'tps-5', ingredientId: null, name: 'lemon', quantity: 1, unit: 'piece', preparation: 'juiced', isOptional: false, sortOrder: 5 },
      { id: 'tps-6', ingredientId: null, name: 'olive oil', quantity: 30, unit: 'ml', preparation: null, isOptional: false, sortOrder: 6 },
      { id: 'tps-7', ingredientId: null, name: 'green onion', quantity: 1, unit: 'bunch', preparation: 'sliced', isOptional: true, sortOrder: 7 },
    ],
    steps: [
      { id: 'tps-s1', stepNumber: 1, instruction: 'Boil the pasta, drain and rinse under cold water so it stops cooking.', durationMinutes: 10, ingredientRefs: ['pasta'], safetyNote: null },
      { id: 'tps-s2', stepNumber: 2, instruction: 'Whisk the lemon juice with olive oil, salt and pepper.', durationMinutes: 2, ingredientRefs: ['lemon', 'olive oil'], safetyNote: null },
      { id: 'tps-s3', stepNumber: 3, instruction: 'Fold everything together and chill for 10 minutes if you can wait.', durationMinutes: 4, ingredientRefs: ['canned tuna', 'cucumber', 'tomatoes', 'green onion'], safetyNote: 'Keep it refrigerated and eat within two days.' },
    ],
  },
  {
    id: 'rcp-cheese-toastie',
    slug: 'egyptian-cheese-toastie',
    title: 'Grilled Cheese & Tomato Toastie',
    description: 'Four ingredients, five minutes, dangerously good at midnight.',
    imageUrl: IMG('1528736235302-52922df5c122'),
    source: 'curated',
    cuisine: 'american',
    mealTypes: ['snack', 'breakfast'],
    difficulty: 'easy',
    prepMinutes: 3,
    cookMinutes: 6,
    baseServings: 1,
    nutrition: { calories: 430, proteinGrams: 19, carbsGrams: 38, fatGrams: 23, fiberGrams: 3 },
    allergens: ['gluten', 'dairy'],
    dietTags: ['vegetarian', 'halal'],
    requiredAppliances: ['stove'],
    tags: ['quick', 'late-night', 'budget', 'under-100', 'beginner', 'snack'],
    createdAt: '2026-01-01T00:00:00.000Z',
    ingredients: [
      { id: 'gct-1', ingredientId: null, name: 'sliced bread', quantity: 2, unit: 'slice', preparation: null, isOptional: false, sortOrder: 1 },
      { id: 'gct-2', ingredientId: null, name: 'mozzarella', quantity: 60, unit: 'g', preparation: 'grated', isOptional: false, sortOrder: 2 },
      { id: 'gct-3', ingredientId: null, name: 'tomatoes', quantity: 1, unit: 'piece', preparation: 'sliced thin', isOptional: false, sortOrder: 3 },
      { id: 'gct-4', ingredientId: null, name: 'butter', quantity: 10, unit: 'g', preparation: 'softened', isOptional: false, sortOrder: 4 },
      { id: 'gct-5', ingredientId: null, name: 'black pepper', quantity: 1, unit: 'pinch', preparation: null, isOptional: true, sortOrder: 5 },
    ],
    steps: [
      { id: 'gct-s1', stepNumber: 1, instruction: 'Butter the outsides of both slices. Pile the cheese and tomato inside and press together.', durationMinutes: 3, ingredientRefs: ['sliced bread', 'butter', 'mozzarella', 'tomatoes'], safetyNote: null },
      { id: 'gct-s2', stepNumber: 2, instruction: 'Cook in a dry pan over medium-low heat, 3 minutes a side, pressing down, until deep gold and molten inside.', durationMinutes: 6, ingredientRefs: ['black pepper'], safetyNote: null },
    ],
  },
  {
    id: 'rcp-kofta-tagine',
    slug: 'kofta-tagine',
    title: 'Kofta in Tomato Tagine',
    description: 'Beef kofta baked in a thick tomato sauce with potatoes. Sunday food on a Tuesday.',
    imageUrl: IMG('1544025162-d76694265947'),
    source: 'curated',
    cuisine: 'egyptian',
    mealTypes: ['dinner'],
    difficulty: 'medium',
    prepMinutes: 20,
    cookMinutes: 40,
    baseServings: 4,
    nutrition: { calories: 620, proteinGrams: 38, carbsGrams: 34, fatGrams: 36, fiberGrams: 5 },
    allergens: [],
    dietTags: ['halal'],
    requiredAppliances: ['oven', 'stove'],
    tags: ['egyptian', 'comfort', 'high-protein', 'oven'],
    createdAt: '2026-01-01T00:00:00.000Z',
    ingredients: [
      { id: 'kt-1', ingredientId: null, name: 'ground beef', quantity: 600, unit: 'g', preparation: null, isOptional: false, sortOrder: 1 },
      { id: 'kt-2', ingredientId: null, name: 'onions', quantity: 2, unit: 'piece', preparation: 'one grated, one sliced', isOptional: false, sortOrder: 2 },
      { id: 'kt-3', ingredientId: null, name: 'parsley', quantity: 1, unit: 'bunch', preparation: 'finely chopped', isOptional: false, sortOrder: 3 },
      { id: 'kt-4', ingredientId: null, name: 'potatoes', quantity: 3, unit: 'piece', preparation: 'thickly sliced', isOptional: false, sortOrder: 4 },
      { id: 'kt-5', ingredientId: null, name: 'tomatoes', quantity: 4, unit: 'piece', preparation: 'blended', isOptional: false, sortOrder: 5 },
      { id: 'kt-6', ingredientId: null, name: 'tomato paste', quantity: 2, unit: 'tbsp', preparation: null, isOptional: false, sortOrder: 6 },
      { id: 'kt-7', ingredientId: null, name: 'garlic', quantity: 4, unit: 'clove', preparation: 'crushed', isOptional: false, sortOrder: 7 },
      { id: 'kt-8', ingredientId: null, name: 'cumin', quantity: 2, unit: 'tsp', preparation: null, isOptional: false, sortOrder: 8 },
      { id: 'kt-9', ingredientId: null, name: 'vegetable oil', quantity: 40, unit: 'ml', preparation: null, isOptional: false, sortOrder: 9 },
    ],
    steps: [
      { id: 'kt-s1', stepNumber: 1, instruction: 'Mix the beef with grated onion, parsley, cumin, salt and pepper. Shape into fingers.', durationMinutes: 12, ingredientRefs: ['ground beef', 'onions', 'parsley', 'cumin'], safetyNote: 'Wash hands and surfaces after handling raw mince, and keep it away from anything eaten raw.' },
      { id: 'kt-s2', stepNumber: 2, instruction: 'Brown the kofta quickly in oil, then set aside. Fry the potato slices in the same pan until golden.', durationMinutes: 12, ingredientRefs: ['vegetable oil', 'potatoes'], safetyNote: null },
      { id: 'kt-s3', stepNumber: 3, instruction: 'Fry the sliced onion and garlic, add tomato paste, blended tomatoes and 200ml water. Simmer 8 minutes.', durationMinutes: 10, ingredientRefs: ['garlic', 'tomato paste', 'tomatoes'], safetyNote: null },
      { id: 'kt-s4', stepNumber: 4, instruction: 'Layer potatoes and kofta in a baking dish, pour over the sauce and bake at 200°C for 25 minutes.', durationMinutes: 25, ingredientRefs: [], safetyNote: 'Ground beef must reach 71°C / 160°F all the way through.' },
    ],
  },
  {
    id: 'rcp-oats-banana',
    slug: 'banana-peanut-oats',
    title: 'Banana & Peanut Butter Oats',
    description: 'Five minutes, one bowl, holds you until lunch. Sweet without adding sugar.',
    imageUrl: IMG('1517673400267-0251440c45dc'),
    source: 'curated',
    cuisine: 'american',
    mealTypes: ['breakfast'],
    difficulty: 'easy',
    prepMinutes: 2,
    cookMinutes: 5,
    baseServings: 1,
    nutrition: { calories: 450, proteinGrams: 17, carbsGrams: 58, fatGrams: 17, fiberGrams: 8 },
    allergens: ['gluten', 'peanuts', 'dairy'],
    dietTags: ['vegetarian', 'halal'],
    requiredAppliances: ['stove'],
    tags: ['quick', 'breakfast', 'budget', 'under-100', 'beginner', 'healthy'],
    createdAt: '2026-01-01T00:00:00.000Z',
    ingredients: [
      { id: 'bpo-1', ingredientId: null, name: 'oats', quantity: 60, unit: 'g', preparation: null, isOptional: false, sortOrder: 1 },
      { id: 'bpo-2', ingredientId: null, name: 'milk', quantity: 250, unit: 'ml', preparation: null, isOptional: false, sortOrder: 2 },
      { id: 'bpo-3', ingredientId: null, name: 'bananas', quantity: 1, unit: 'piece', preparation: 'sliced', isOptional: false, sortOrder: 3 },
      { id: 'bpo-4', ingredientId: null, name: 'peanut butter', quantity: 1, unit: 'tbsp', preparation: null, isOptional: false, sortOrder: 4 },
      { id: 'bpo-5', ingredientId: null, name: 'cinnamon', quantity: 1, unit: 'pinch', preparation: null, isOptional: true, sortOrder: 5 },
      { id: 'bpo-6', ingredientId: null, name: 'honey', quantity: 1, unit: 'tsp', preparation: null, isOptional: true, sortOrder: 6 },
    ],
    steps: [
      { id: 'bpo-s1', stepNumber: 1, instruction: 'Simmer the oats in milk with a pinch of salt for 4 minutes, stirring, until creamy.', durationMinutes: 5, ingredientRefs: ['oats', 'milk'], safetyNote: null },
      { id: 'bpo-s2', stepNumber: 2, instruction: 'Stir in half the banana so it melts into the oats. Top with the rest, peanut butter, cinnamon and honey.', durationMinutes: 2, ingredientRefs: ['bananas', 'peanut butter', 'cinnamon', 'honey'], safetyNote: null },
    ],
  },
  {
    id: 'rcp-veg-fried-rice',
    slug: 'quick-vegetable-fried-rice',
    title: 'Quick Vegetable Fried Rice',
    description: 'The best thing to do with yesterday’s rice. Fifteen minutes, one pan, whatever vegetables you have.',
    imageUrl: IMG('1603133872878-684f208fb84b'),
    source: 'curated',
    cuisine: 'asian',
    mealTypes: ['lunch', 'dinner'],
    difficulty: 'easy',
    prepMinutes: 8,
    cookMinutes: 10,
    baseServings: 2,
    nutrition: { calories: 470, proteinGrams: 16, carbsGrams: 68, fatGrams: 14, fiberGrams: 6 },
    allergens: ['eggs'],
    dietTags: ['vegetarian', 'halal'],
    requiredAppliances: ['stove'],
    tags: ['quick', 'budget', 'under-100', 'asian', 'leftovers', 'beginner'],
    createdAt: '2026-01-01T00:00:00.000Z',
    ingredients: [
      { id: 'vfr-1', ingredientId: null, name: 'rice', quantity: 400, unit: 'g', preparation: 'cooked and cooled', isOptional: false, sortOrder: 1 },
      { id: 'vfr-2', ingredientId: null, name: 'eggs', quantity: 2, unit: 'piece', preparation: 'beaten', isOptional: false, sortOrder: 2 },
      { id: 'vfr-3', ingredientId: null, name: 'carrots', quantity: 1, unit: 'piece', preparation: 'diced small', isOptional: false, sortOrder: 3 },
      { id: 'vfr-4', ingredientId: null, name: 'green peas', quantity: 100, unit: 'g', preparation: null, isOptional: false, sortOrder: 4 },
      { id: 'vfr-5', ingredientId: null, name: 'garlic', quantity: 3, unit: 'clove', preparation: 'minced', isOptional: false, sortOrder: 5 },
      { id: 'vfr-6', ingredientId: null, name: 'green onion', quantity: 1, unit: 'bunch', preparation: 'sliced', isOptional: false, sortOrder: 6 },
      { id: 'vfr-7', ingredientId: null, name: 'vegetable oil', quantity: 30, unit: 'ml', preparation: null, isOptional: false, sortOrder: 7 },
    ],
    steps: [
      { id: 'vfr-s1', stepNumber: 1, instruction: 'Scramble the eggs quickly in hot oil and set aside.', durationMinutes: 2, ingredientRefs: ['eggs', 'vegetable oil'], safetyNote: null },
      { id: 'vfr-s2', stepNumber: 2, instruction: 'Stir-fry the carrot and peas for 3 minutes, then add the garlic for 30 seconds.', durationMinutes: 4, ingredientRefs: ['carrots', 'green peas', 'garlic'], safetyNote: null },
      { id: 'vfr-s3', stepNumber: 3, instruction: 'Add the cold rice, breaking up clumps, and fry hard for 4 minutes until it starts to catch.', durationMinutes: 4, ingredientRefs: ['rice'], safetyNote: 'Only use rice that was cooled quickly and refrigerated, and reheat it once until piping hot.' },
      { id: 'vfr-s4', stepNumber: 4, instruction: 'Fold the egg back in with the green onions and season.', durationMinutes: 1, ingredientRefs: ['green onion'], safetyNote: null },
    ],
  },
  {
    id: 'rcp-bamya',
    slug: 'okra-stew',
    title: 'Okra Stew with Beef',
    description: 'Slow-cooked bamya in garlicky tomato, the way it should be. Serve with rice and bread.',
    imageUrl: IMG('1574484284002-952d92456975'),
    source: 'curated',
    cuisine: 'egyptian',
    mealTypes: ['lunch', 'dinner'],
    difficulty: 'medium',
    prepMinutes: 15,
    cookMinutes: 75,
    baseServings: 4,
    nutrition: { calories: 520, proteinGrams: 36, carbsGrams: 30, fatGrams: 28, fiberGrams: 8 },
    allergens: [],
    dietTags: ['halal'],
    requiredAppliances: ['stove'],
    tags: ['egyptian', 'comfort', 'high-protein', 'slow'],
    createdAt: '2026-01-01T00:00:00.000Z',
    ingredients: [
      { id: 'bam-1', ingredientId: null, name: 'beef cubes', quantity: 600, unit: 'g', preparation: null, isOptional: false, sortOrder: 1 },
      { id: 'bam-2', ingredientId: null, name: 'okra', quantity: 500, unit: 'g', preparation: 'trimmed', isOptional: false, sortOrder: 2 },
      { id: 'bam-3', ingredientId: null, name: 'tomatoes', quantity: 4, unit: 'piece', preparation: 'blended', isOptional: false, sortOrder: 3 },
      { id: 'bam-4', ingredientId: null, name: 'tomato paste', quantity: 2, unit: 'tbsp', preparation: null, isOptional: false, sortOrder: 4 },
      { id: 'bam-5', ingredientId: null, name: 'garlic', quantity: 6, unit: 'clove', preparation: 'crushed', isOptional: false, sortOrder: 5 },
      { id: 'bam-6', ingredientId: null, name: 'onions', quantity: 1, unit: 'piece', preparation: 'chopped', isOptional: false, sortOrder: 6 },
      { id: 'bam-7', ingredientId: null, name: 'coriander', quantity: 1, unit: 'bunch', preparation: 'chopped', isOptional: false, sortOrder: 7 },
      { id: 'bam-8', ingredientId: null, name: 'vegetable oil', quantity: 40, unit: 'ml', preparation: null, isOptional: false, sortOrder: 8 },
      { id: 'bam-9', ingredientId: null, name: 'lemon', quantity: 1, unit: 'piece', preparation: 'juiced', isOptional: true, sortOrder: 9 },
    ],
    steps: [
      { id: 'bam-s1', stepNumber: 1, instruction: 'Brown the beef hard in oil, then add the onion and cook until soft.', durationMinutes: 10, ingredientRefs: ['beef cubes', 'vegetable oil', 'onions'], safetyNote: 'Keep raw beef separate from anything served uncooked.' },
      { id: 'bam-s2', stepNumber: 2, instruction: 'Add water to cover and simmer, covered, for 50 minutes until the beef gives way.', durationMinutes: 50, ingredientRefs: [], safetyNote: null },
      { id: 'bam-s3', stepNumber: 3, instruction: 'Stir in the blended tomatoes, paste and half the garlic. Add the okra and simmer 20 minutes without stirring much.', durationMinutes: 20, ingredientRefs: ['tomatoes', 'tomato paste', 'garlic', 'okra'], safetyNote: null },
      { id: 'bam-s4', stepNumber: 4, instruction: 'Fry the remaining garlic with the coriander and tip it in. Finish with lemon juice.', durationMinutes: 3, ingredientRefs: ['coriander', 'lemon'], safetyNote: null },
    ],
  },
  {
    id: 'rcp-zucchini-eggs',
    slug: 'zucchini-egg-skillet',
    title: 'Zucchini & Egg Skillet',
    description: 'Cheap, green and quick. What to make when the fridge is nearly empty.',
    imageUrl: IMG('1482049016688-2d3e1b311543'),
    source: 'curated',
    cuisine: 'mediterranean',
    mealTypes: ['breakfast', 'lunch'],
    difficulty: 'easy',
    prepMinutes: 5,
    cookMinutes: 12,
    baseServings: 2,
    nutrition: { calories: 300, proteinGrams: 20, carbsGrams: 12, fatGrams: 20, fiberGrams: 4 },
    allergens: ['eggs'],
    dietTags: ['vegetarian', 'halal', 'keto'],
    requiredAppliances: ['stove'],
    tags: ['quick', 'budget', 'under-100', 'healthy', 'beginner', 'low-carb'],
    createdAt: '2026-01-01T00:00:00.000Z',
    ingredients: [
      { id: 'ze-1', ingredientId: null, name: 'zucchini', quantity: 2, unit: 'piece', preparation: 'sliced', isOptional: false, sortOrder: 1 },
      { id: 'ze-2', ingredientId: null, name: 'eggs', quantity: 4, unit: 'piece', preparation: 'beaten', isOptional: false, sortOrder: 2 },
      { id: 'ze-3', ingredientId: null, name: 'onions', quantity: 1, unit: 'piece', preparation: 'sliced', isOptional: false, sortOrder: 3 },
      { id: 'ze-4', ingredientId: null, name: 'garlic', quantity: 2, unit: 'clove', preparation: 'sliced', isOptional: false, sortOrder: 4 },
      { id: 'ze-5', ingredientId: null, name: 'olive oil', quantity: 25, unit: 'ml', preparation: null, isOptional: false, sortOrder: 5 },
      { id: 'ze-6', ingredientId: null, name: 'white cheese', quantity: 50, unit: 'g', preparation: 'crumbled', isOptional: true, sortOrder: 6 },
    ],
    steps: [
      { id: 'ze-s1', stepNumber: 1, instruction: 'Fry the onion and zucchini in olive oil over medium-high heat for 8 minutes until browned at the edges.', durationMinutes: 8, ingredientRefs: ['onions', 'zucchini', 'olive oil'], safetyNote: null },
      { id: 'ze-s2', stepNumber: 2, instruction: 'Add the garlic for 30 seconds, then pour in the eggs and stir gently until just set.', durationMinutes: 4, ingredientRefs: ['garlic', 'eggs'], safetyNote: 'Cook until the eggs are set with no runny liquid.' },
      { id: 'ze-s3', stepNumber: 3, instruction: 'Crumble the cheese over and serve straight from the pan.', durationMinutes: 1, ingredientRefs: ['white cheese'], safetyNote: null },
    ],
  },
];

export const RECIPES_BY_ID = new Map(RECIPE_FIXTURES.map((recipe) => [recipe.id, recipe]));

/** Discover collections. `tag` is matched against `Recipe.tags`. */
export const COLLECTIONS = [
  { slug: 'quick', tag: 'quick', labelKey: 'discover.collectionQuick', emoji: '⚡' },
  { slug: 'under-100', tag: 'under-100', labelKey: 'discover.collectionUnder100', emoji: '💸' },
  { slug: 'high-protein', tag: 'high-protein', labelKey: 'discover.collectionHighProtein', emoji: '💪' },
  { slug: 'healthy', tag: 'healthy', labelKey: 'discover.collectionHealthy', emoji: '🥗' },
  { slug: 'egyptian', tag: 'egyptian', labelKey: 'discover.collectionEgyptian', emoji: '🇪🇬' },
  { slug: 'italian', tag: 'italian', labelKey: 'discover.collectionItalian', emoji: '🍝' },
  { slug: 'asian', tag: 'asian', labelKey: 'discover.collectionAsian', emoji: '🍜' },
  { slug: 'breakfast', tag: 'breakfast', labelKey: 'discover.collectionBreakfast', emoji: '🍳' },
  { slug: 'late-night', tag: 'late-night', labelKey: 'discover.collectionLateNight', emoji: '🌙' },
  { slug: 'air-fryer', tag: 'air-fryer', labelKey: 'discover.collectionAirFryer', emoji: '🔥' },
  { slug: 'beginner', tag: 'beginner', labelKey: 'discover.collectionBeginner', emoji: '🌱' },
  { slug: 'comfort', tag: 'comfort', labelKey: 'discover.collectionTrending', emoji: '🍲' },
] as const;

export type CollectionSlug = (typeof COLLECTIONS)[number]['slug'];
