// GENERATED by `npm run images:index`. Do not edit.
//
// Literal `require` calls, because Metro bundles what it can SEE — a path
// computed at runtime resolves to nothing at all.

export type LocalRecipeImage = {
  /** The bundled asset. Passed straight to `expo-image`. */
  source: number;
  creator: string;
  license: string;
  attribution: string | null;
  sourcePage: string;
};

export const LOCAL_RECIPE_IMAGES: Record<string, LocalRecipeImage> = {
  "aloo-gobi": {
    source: require('../../../assets/recipes/aloo-gobi.jpg') as number,
    creator: "Sapanabehl",
    license: "CC-BY-SA-4.0",
    attribution: "Sapanabehl · CC-BY-SA-4.0 · Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Aloo_Ghobi.jpg",
  },
  "bamia-vegetarian": {
    source: require('../../../assets/recipes/bamia-vegetarian.jpg') as number,
    creator: "Tamorlan",
    license: "CC-BY-SA-3.0",
    attribution: "Tamorlan · CC-BY-SA-3.0 · Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Bamia-Ocras_tomate_(cropped).JPG",
  },
  "banana-bread": {
    source: require('../../../assets/recipes/banana-bread.jpg') as number,
    creator: "Shisma",
    license: "CC-BY-4.0",
    attribution: "Shisma · CC-BY-4.0 · Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Banana_bread_slices.jpg",
  },
  "basbousa": {
    source: require('../../../assets/recipes/basbousa.jpg') as number,
    creator: "stu_spivack",
    license: "CC-BY-SA-2.0",
    attribution: "stu_spivack · CC-BY-SA-2.0 · Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Basboosa.jpg",
  },
  "batata-harra": {
    source: require('../../../assets/recipes/batata-harra.jpg') as number,
    creator: "secretlondon123 from London, England",
    license: "CC-BY-SA-2.0",
    attribution: "secretlondon123 from London, England · CC-BY-SA-2.0 · Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Batata_harra.jpg",
  },
  "beef-burger-homemade": {
    source: require('../../../assets/recipes/beef-burger-homemade.jpg') as number,
    creator: "thienzieyung",
    license: "CC-BY-2.0",
    attribution: "thienzieyung · CC-BY-2.0 · Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Beef_Burger_In_Kota_Kinabalu,_Malaysia.jpg",
  },
  "beef-tacos": {
    source: require('../../../assets/recipes/beef-tacos.jpg') as number,
    creator: "Horacio Cambeiro",
    license: "CC-BY-SA-3.0",
    attribution: "Horacio Cambeiro · CC-BY-SA-3.0 · Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Argentine-style_hand-chopped_roasted_beef_tacos,_with_mozzarella,_caramelized_onions,_and_salsas.jpg",
  },
  "bessara": {
    source: require('../../../assets/recipes/bessara.jpg') as number,
    creator: "Ruby Josephine Smith",
    license: "CC-BY-SA-4.0",
    attribution: "Ruby Josephine Smith · CC-BY-SA-4.0 · Wikimedia Commons",
    sourcePage: "https://commons.wikimedia.org/wiki/File:Bissara_Moroccan_split_pea_and_fava_bean_soup.jpg",
  },
};
