// GENERATED by `npm run images:index`. Do not edit.
//
// Literal `require` calls, because Metro bundles what it can SEE — a path
// computed at runtime resolves to nothing at all.

export type LocalRecipeImage = {
  /** The bundled asset. Passed straight to `expo-image`. */
  source: number;
  creator: string;
  license: string;
  attribution: string | null;
  sourcePage: string;
};

export const LOCAL_RECIPE_IMAGES: Record<string, LocalRecipeImage> = {
};
