/**
 * What the family heuristic actually believes.
 *
 * A "family word" names a set of ingredients rather than one — `chicken` is
 * seven rows. Most families are INFERRED: a token appearing in the canonical
 * name of two or more ingredients. That rule is cheap and self-maintaining,
 * and it is also a heuristic, which means it invents meanings nobody asked
 * for. `white` appears in `white cheese`, `white beans`, `white pepper` and
 * `egg white`, so on the token rule alone "without white" rules out four
 * unrelated foods.
 *
 * The question this answers is not "is the rule perfect" — it is not — but
 * "which of these meanings do we actually intend, and which are accidents we
 * are one bad query away from shipping?". It prints every inferred family so
 * that judgement can be made by reading rather than by guessing, and it flags
 * the ones whose members span food groups, because those are where an
 * accidental family does visible harm.
 *
 * Changes nothing. Ships nothing.
 *
 *     npm run audit:families
 */
import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import {
  DECLARED_FAMILIES,
  declaredFamilyMembers,
  inferredFamilies,
} from '../src/features/ingredients/families.ts';

/**
 * A coarse kitchen grouping, kept deliberately crude.
 *
 * It exists only to answer "do these members belong to the same kind of
 * food?", which is the difference between a family that is merely broad and
 * one that is incoherent. The benchmark has a finer version of this;
 * duplicating a rough one here keeps a test fixture out of a reporting script.
 */
const GROUP_BY_CATEGORY: Record<string, string> = {
  vegetables: 'produce',
  fruit: 'produce',
  spices: 'seasoning',
  sauces: 'seasoning',
  dairy: 'dairy',
  protein: 'protein',
  carbs: 'staple',
  bakery: 'staple',
  pantry: 'pantry',
  frozen: 'frozen',
  other: 'other',
};

const inferred = inferredFamilies();

type Row = {
  token: string;
  members: string[];
  groups: string[];
  spansGroups: boolean;
};

const rows: Row[] = inferred.map(({ token, members }) => {
  const groups = [...new Set(members.map((m) => GROUP_BY_CATEGORY[m.category] ?? m.category))];
  return {
    token,
    members: members.map((m) => m.slug),
    groups: groups.sort(),
    spansGroups: groups.length > 1,
  };
});

const crossGroup = rows.filter((row) => row.spansGroups);

const lines: string[] = [
  '# Family-word audit',
  '',
  '**Generated by `npm run audit:families`. Do not edit by hand.**',
  '',
  'A family word names a SET of ingredients rather than one, and is consulted',
  'only by search, exclusion and requirement — never by pantry matching. See',
  '`src/features/ingredients/families.ts`.',
  '',
  `| | |`,
  `|---|---|`,
  `| Declared families | ${DECLARED_FAMILIES.length} |`,
  `| Inferred families | ${rows.length} |`,
  `| …whose members span food groups | ${crossGroup.length} |`,
  '',
  '## Declared',
  '',
  'Curated: the words in both languages, and the exact members. These beat the',
  'inferred rule.',
  '',
  '| Concept | Terms | Members |',
  '|---|---|---|',
];

for (const family of DECLARED_FAMILIES) {
  lines.push(
    `| ${family.concept} | ${family.terms.map((t) => `\`${t}\``).join(' ')} | ` +
      `${declaredFamilyMembers(family)
        .map((m) => `\`${m.slug}\``)
        .join(', ')} |`,
  );
}

lines.push(
  '',
  '## Inferred, spanning more than one food group',
  '',
  'These are the ones to read carefully. A token shared across food groups is',
  'usually an adjective doing duty as a noun — a colour, a texture, a state —',
  'rather than a real parent concept.',
  '',
  '| Token | Groups | Members |',
  '|---|---|---|',
);

for (const row of crossGroup) {
  lines.push(
    `| \`${row.token}\` | ${row.groups.join(', ')} | ${row.members.map((s) => `\`${s}\``).join(', ')} |`,
  );
}

lines.push(
  '',
  '## Inferred, within one food group',
  '',
  '| Token | Group | Members |',
  '|---|---|---|',
);

for (const row of rows.filter((entry) => !entry.spansGroups)) {
  lines.push(
    `| \`${row.token}\` | ${row.groups[0]} | ${row.members.map((s) => `\`${s}\``).join(', ')} |`,
  );
}

lines.push('');

const out = resolve(import.meta.dirname, '..', 'FAMILY_AUDIT.md');
writeFileSync(out, lines.join('\n'));
console.log(
  `${DECLARED_FAMILIES.length} declared families, ${rows.length} inferred ` +
    `(${crossGroup.length} spanning food groups).`,
);
console.log(`-> ${out}`);
