/**
 * Turns the image manifest into a module the bundler can see.
 *
 *     npm run images:index
 *
 * Metro cannot `require()` a path it works out at runtime — every asset has to
 * appear as a literal in the source, or it is simply not in the bundle. So the
 * manifest (data) becomes a generated module of literal `require` calls
 * (code), exactly as the ingredient and recipe catalogues do.
 *
 * The alternative is a remote URL per recipe, which is the hotlinking this
 * pipeline exists to avoid.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dirname, '..');
const MANIFEST = join(ROOT, 'data', 'images', 'manifest.json');
const OUTPUT = join(ROOT, 'src', 'features', 'recipes', 'image-assets.generated.ts');

type ImageRecord = {
  recipeSlug: string;
  path: string;
  sourcePage: string;
  originalUrl: string;
  creator: string;
  license: string;
  attribution: string | null;
};

function main(): void {
  const manifest = existsSync(MANIFEST)
    ? (JSON.parse(readFileSync(MANIFEST, 'utf8')) as { images: ImageRecord[] })
    : { images: [] };

  const entries = [...manifest.images].sort((a, b) => a.recipeSlug.localeCompare(b.recipeSlug));

  const lines = [
    '// GENERATED by `npm run images:index`. Do not edit.',
    '//',
    '// Literal `require` calls, because Metro bundles what it can SEE — a path',
    '// computed at runtime resolves to nothing at all.',
    '',
    'export type LocalRecipeImage = {',
    '  /** The bundled asset. Passed straight to `expo-image`. */',
    '  source: number;',
    '  creator: string;',
    '  license: string;',
    '  attribution: string | null;',
    '  sourcePage: string;',
    '};',
    '',
    'export const LOCAL_RECIPE_IMAGES: Record<string, LocalRecipeImage> = {',
  ];

  for (const image of entries) {
    lines.push(
      `  ${JSON.stringify(image.recipeSlug)}: {`,
      `    source: require('../../../assets/recipes/${image.path}') as number,`,
      `    creator: ${JSON.stringify(image.creator)},`,
      `    license: ${JSON.stringify(image.license)},`,
      `    attribution: ${JSON.stringify(image.attribution)},`,
      `    sourcePage: ${JSON.stringify(image.sourcePage)},`,
      '  },',
    );
  }

  lines.push('};', '');
  writeFileSync(OUTPUT, lines.join('\n'));
  console.log(`image-assets.generated.ts written: ${entries.length} bundled photograph(s)`);
}

main();
