/**
 * The human-review surface for staged photography.
 *
 *     npm run images:review-candidates   # writes PHOTO_CANDIDATE_REVIEW.md
 *
 * WHY THIS PAGE EXISTS. Every mechanical check the acquisition runs reads a
 * title, a licence, a category and a pixel count. None of them can see the
 * picture. The record of that gap is `data/images/rejected.json`: an aerial
 * photograph of the Turkish town of Menemen for the dish named after it, a
 * grape vine for stuffed vine leaves, breaded oysters for scrambled eggs,
 * a branded milkshake cup with somebody else's trademark across it. Each one
 * passed every automatic test.
 *
 * So the last check is a person looking at the photograph, and this is what
 * they look at. The image references are relative repository paths, which
 * means GitHub renders them inline — the review happens by scrolling one page,
 * not by opening forty files.
 *
 * TO REJECT ONE: add its Commons title to `data/images/rejected.json` with the
 * reason, delete the staged file and its manifest entry, and re-run the
 * acquisition. The refusal is permanent and applies to production too; the
 * fetchers will never choose that file again and both validators refuse a
 * manifest containing it.
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dirname, '..');
const CANDIDATE_DIR = join(ROOT, 'data', 'recipe-candidates');
const MANIFEST = join(ROOT, 'data', 'images', 'candidate-manifest.json');
const OUTPUT = join(ROOT, 'PHOTO_CANDIDATE_REVIEW.md');

type Candidate = {
  slug: string;
  name: string;
  nameAr: string;
  cuisine: string;
  coreIngredients: string[];
  note?: string;
};
type Batch = { batch: string; intent: string; candidates: Candidate[] };
type Record_ = {
  candidateSlug: string;
  batch: string;
  path: string;
  sourcePage: string;
  creator: string;
  license: string;
  attribution: string | null;
  width: number;
  height: number;
  bytes: number;
};
type Manifest = {
  images: Record_[];
  skipped: { candidateSlug: string; batch: string; reason: string }[];
};

function batches(): Batch[] {
  if (!existsSync(CANDIDATE_DIR)) return [];
  return readdirSync(CANDIDATE_DIR)
    .filter((name) => name.endsWith('.json'))
    .sort()
    .map((name) => JSON.parse(readFileSync(join(CANDIDATE_DIR, name), 'utf8')) as Batch);
}

function manifest(): Manifest {
  if (!existsSync(MANIFEST)) return { images: [], skipped: [] };
  return JSON.parse(readFileSync(MANIFEST, 'utf8')) as Manifest;
}

function main(): void {
  const all = batches();
  const staged = manifest();
  const byslug = new Map(staged.images.map((entry) => [entry.candidateSlug, entry]));
  const skippedBySlug = new Map(staged.skipped.map((entry) => [entry.candidateSlug, entry.reason]));

  const lines: string[] = [
    '# Candidate photography — review before any of this ships',
    '',
    '**Generated by `npm run images:review-candidates`. Do not edit by hand.**',
    '',
    'None of these photographs is published. They are staged in',
    '`assets/recipe-candidates/`, which the app does not bundle and does not index.',
    'A staged photograph reaches a recipe card only through `npm run images:promote`,',
    'by name, after its recipe exists.',
    '',
    '**A photograph passing the automatic checks does not prove it depicts the right',
    'dish.** The checks read a title, a licence, a category and a pixel count. They',
    'cannot see the picture. `data/images/rejected.json` is the record of what that',
    'misses: an aerial view of the Turkish town of Menemen for the dish named after',
    'it, a grape vine for stuffed vine leaves, breaded oysters for scrambled eggs.',
    'Every one passed every automatic test.',
    '',
    '### To reject one',
    '',
    'Add its Commons title to `data/images/rejected.json` with the reason, delete the',
    'staged file and its manifest entry, and re-run the acquisition. The refusal is',
    'permanent, applies to production as well, and both validators refuse a manifest',
    'that contains a refused file.',
    '',
  ];

  for (const batch of all) {
    const withImage = batch.candidates.filter((entry) => byslug.has(entry.slug));
    const without = batch.candidates.filter((entry) => !byslug.has(entry.slug));

    lines.push(
      `## ${batch.batch}`,
      '',
      batch.intent,
      '',
      `**${withImage.length} of ${batch.candidates.length} have a candidate photograph.**`,
      '',
    );

    for (const candidate of withImage) {
      const image = byslug.get(candidate.slug)!;
      lines.push(
        `### ${candidate.name} · ${candidate.nameAr}`,
        '',
        `\`${candidate.slug}\` · ${candidate.cuisine} · ` +
          `${candidate.coreIngredients.map((slug) => `\`${slug}\``).join(', ')}`,
        '',
        ...(candidate.note ? [candidate.note, ''] : []),
        `![${candidate.name}](assets/recipe-candidates/${image.path})`,
        '',
        '| | |',
        '|---|---|',
        `| Creator | ${image.creator} |`,
        `| Licence | ${image.license} |`,
        `| Attribution | ${image.attribution ?? '_none required_'} |`,
        `| Source | ${image.sourcePage} |`,
        `| Size | ${image.width}×${image.height}, ${Math.round(image.bytes / 1024)} KB |`,
        '',
        '- [ ] This is a photograph of this dish, and I would put it on the card.',
        '',
      );
    }

    if (without.length > 0) {
      lines.push(
        `### No acceptable image (${without.length})`,
        '',
        'These keep nothing. A generic photograph of something else is not a',
        'substitute — it tells the user something false about what they are cooking.',
        '',
        '| Dish | Why |',
        '|---|---|',
      );
      for (const candidate of without) {
        const reason = skippedBySlug.get(candidate.slug) ?? '_not attempted yet_';
        lines.push(`| ${candidate.name} (\`${candidate.slug}\`) | ${reason.replace(/\|/g, '\\|')} |`);
      }
      lines.push('');
    }
  }

  writeFileSync(OUTPUT, `${lines.join('\n')}\n`);

  const total = all.reduce((sum, batch) => sum + batch.candidates.length, 0);
  console.log(
    `PHOTO_CANDIDATE_REVIEW.md written: ${staged.images.length} of ${total} candidate(s) ` +
      'have a photograph to look at.',
  );
}

main();
